
// generate I/O (EL)
exports.inputs1 = [
  { addr: 'E0.0', label: 'EOM1' },
  { addr: 'E0.1', label: 'EZM1' },
  { addr: 'E0.2', label: 'AMM1' },
  { addr: 'E0.3', label: 'EOM2' },
  { addr: 'E0.4', label: 'EZM2' },
  { addr: 'E0.5', label: 'AMM2' },
  { addr: 'E0.6', label: 'FTXV' },
  { addr: 'E0.7', label: 'FTXH' },
  { addr: 'E1.0', label: 'BA' },
  { addr: 'E1.1', label: 'BB' },
  { addr: 'E1.2', label: 'BC' },
  { addr: 'E1.3', label: 'BD' },
  { addr: 'E1.4', label: 'BSTR' },
  { addr: 'E1.5', label: 'BOK' },
  { addr: 'E1.6', label: 'BDAT' },
  { addr: 'E1.7', label: 'FPU' },
  { addr: 'E2.0', label: 'MNA' },
  { addr: 'E2.1', label: 'MNB' },
  { addr: 'E2.2', label: 'EXPV' },
  { addr: 'E2.3', label: 'EFB' },
  { addr: 'E2.4', label: 'FSBK' },
  { addr: 'E2.5', label: 'ASBK' },
  { addr: 'E2.6', label: 'RTA' },
  { addr: 'E2.7', label: 'FKBA' },
  { addr: 'E3.0', label: 'EBZA' },
  { addr: 'E3.1', label: 'EBOA' },
  { addr: 'E3.2', label: 'FBBA' },
  { addr: 'E3.3', label: 'FPA' },
  { addr: 'E3.4', label: 'IVE' },
  { addr: 'E3.5', label: 'KEZE' },
  { addr: 'E3.6', label: 'KEXPV' },
  { addr: 'E3.7', label: 'RXU' },
  { addr: 'E4.0', label: 'A' },
  { addr: 'E4.1', label: 'B' },
  { addr: 'E4.2', label: 'C' },
  { addr: 'E4.3', label: 'D' },
  { addr: 'E4.4', label: 'OK' },
  { addr: 'E4.5', label: 'S2' },
  { addr: 'E4.6', label: 'S2' },
  { addr: 'E4.7', label: 'S2' },
  { addr: 'E5.0', label: 'BA' },
  { addr: 'E5.1', label: 'BB' },
  { addr: 'E5.2', label: 'BC' },
  { addr: 'E5.3', label: 'BD' },
  { addr: 'E5.4', label: 'BSTR' },
  { addr: 'E5.5', label: 'BOK' },
  { addr: 'E5.6', label: 'BDAT' },
  { addr: 'E5.7', label: 'UC' },
  { addr: 'E6.0', label: 'FAL' },
  { addr: 'E6.1', label: '' },
  { addr: 'E6.2', label: 'KXPE' },
  { addr: 'E6.3', label: 'KXPU' },
  { addr: 'E6.4', label: '' },
  { addr: 'E6.5', label: '' },
  { addr: 'E6.6', label: '' },
  { addr: 'E6.7', label: '' },
  { addr: 'E7.0', label: 'IV1' },
  { addr: 'E7.1', label: 'TJ1' },
  { addr: 'E7.2', label: 'SA' },
  { addr: 'E7.3', label: 'RSI' },
  { addr: 'E7.4', label: 'DB32' },
  { addr: 'E7.5', label: 'DBHZ' },
  { addr: 'E7.6', label: '' },
  { addr: 'E7.7', label: '' },
  { addr: 'E8.0', label: 'EBZE' },
  { addr: 'E8.1', label: 'EBOE' },
  { addr: 'E8.2', label: 'FBBE' },
  { addr: 'E8.3', label: 'RXE' },
  { addr: 'E8.4', label: 'SBK1' },
  { addr: 'E8.5', label: 'ASBK' },
  { addr: 'E8.6', label: 'RTA' },
  { addr: 'E8.7', label: 'FKBA' },
  { addr: 'E9.0', label: 'EPZV' },
  { addr: 'E9.1', label: 'EPZH' },
  { addr: 'E9.2', label: 'FTA2' },
  { addr: 'E9.3', label: 'FTA3' },
  { addr: 'E9.4', label: 'FXR' },
  { addr: 'E9.5', label: 'FXL' },
  { addr: 'E9.6', label: 'FDR3' },
  { addr: 'E9.7', label: 'FDL3' },
  { addr: 'E10.0', label: '' },
  { addr: 'E10.1', label: '' },
  { addr: 'E10.2', label: '' },
  { addr: 'E10.3', label: '' },
  { addr: 'E10.4', label: 'FPE' },
  { addr: 'E10.5', label: 'FDR1' },
  { addr: 'E10.6', label: 'FDL1' },
  { addr: 'E10.7', label: 'FTA1' },
  { addr: 'E11.0', label: 'FTA2' },
  { addr: 'E11.1', label: 'FTA3' },
  { addr: 'E11.2', label: 'FLP1' },
  { addr: 'E11.3', label: 'FLP2' },
  { addr: 'E11.4', label: 'FLA1' },
  { addr: 'E11.5', label: 'FLA2' },
  { addr: 'E11.6', label: 'FDR2' },
  { addr: 'E11.7', label: 'FDL2' }
]
exports.inputs2 = [
  { addr: 'E24.0', label: 'AGL' },
  { addr: 'E24.1', label: 'ACR' },
  { addr: 'E24.2', label: 'FTCR' },
  { addr: 'E24.3', label: '' },
  { addr: 'E24.4', label: '' },
  { addr: 'E24.5', label: '' },
  { addr: 'E24.6', label: '' },
  { addr: 'E24.7', label: '' },
  { addr: 'E25.0', label: '' },
  { addr: 'E25.1', label: '' },
  { addr: 'E25.2', label: 'AMM' },
  { addr: 'E25.3', label: 'EOM' },
  { addr: 'E25.4', label: 'EZM' },
  { addr: 'E25.5', label: 'EMC' },
  { addr: 'E25.6', label: 'FTXV' },
  { addr: 'E25.7', label: 'FTXH' }
]
exports.inputs3 = [
  { addr: 'E26.0', label: 'A' },
  { addr: 'E26.1', label: 'B' },
  { addr: 'E26.2', label: 'C' },
  { addr: 'E26.3', label: 'D' },
  { addr: 'E26.4', label: 'OK' },
  { addr: 'E26.5', label: 'S2' },
  { addr: 'E26.6', label: 'S2' },
  { addr: 'E26.7', label: 'S2' },
  { addr: 'E27.0', label: 'MNA' },
  { addr: 'E27.1', label: 'MNB' },
  { addr: 'E27.2', label: 'EFA' },
  { addr: 'E27.3', label: 'EFB' },
  { addr: 'E27.4', label: 'IV' },
  { addr: 'E27.5', label: 'FFBK' },
  { addr: 'E27.6', label: 'ASBK' },
  { addr: 'E27.7', label: 'RTA' },
  { addr: 'E28.0', label: 'MDR' },
  { addr: 'E28.1', label: 'MDL' },
  { addr: 'E28.2', label: 'EDR' },
  { addr: 'E28.3', label: 'EDL' },
  { addr: 'E28.4', label: 'AD' },
  { addr: 'E28.5', label: 'KEZE' },
  { addr: 'E28.6', label: 'KEXPV' },
  { addr: 'E28.7', label: 'UC' },
  { addr: 'E29.0', label: 'EOM1' },
  { addr: 'E29.1', label: 'EZM1' },
  { addr: 'E29.2', label: 'AMM' },
  { addr: 'E29.3', label: 'EOM2' },
  { addr: 'E29.4', label: 'EZM2' },
  { addr: 'E29.5', label: 'FRE' },
  { addr: 'E29.6', label: 'EXD' },
  { addr: 'E29.7', label: '' }
]
// generate I/O (SH)
exports.inputs4 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'OK' },
  { addr: 'E0.5', label: 'S2' },
  { addr: 'E0.6', label: 'S2' },
  { addr: 'E0.7', label: 'S2' },
  { addr: 'E1.0', label: 'FTV' },
  { addr: 'E1.1', label: 'FTH' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: 'FEMV' },
  { addr: 'E1.5', label: 'FEMH' },
  { addr: 'E1.6', label: 'FTXV' },
  { addr: 'E1.7', label: 'FTXH' },
  { addr: 'E2.0', label: 'RMV' },
  { addr: 'E2.1', label: 'RMH' },
  { addr: 'E2.2', label: 'RES' },
  { addr: 'E2.3', label: 'REH' },
  { addr: 'E2.4', label: 'RCVH' },
  { addr: 'E2.5', label: 'REAV' },
  { addr: 'E2.6', label: 'REAH' },
  { addr: 'E2.7', label: 'REP' },
  { addr: 'E3.0', label: 'IV' },
  { addr: 'E3.1', label: 'TJ' },
  { addr: 'E3.2', label: 'SA' },
  { addr: 'E3.3', label: 'RSI' },
  { addr: 'E3.4', label: 'DB32' },
  { addr: 'E3.5', label: 'DBHZ' },
  { addr: 'E3.6', label: 'FTM' },
  { addr: 'E3.7', label: 'UC' }
]
exports.inputs5 = [
  { addr: 'E4.0', label: 'MNR' },
  { addr: 'E4.1', label: 'MNL' },
  { addr: 'E4.2', label: '' },
  { addr: 'E4.3', label: 'ACRE' },
  { addr: 'E4.4', label: 'FTCRE' },
  { addr: 'E4.5', label: 'FTCR' },
  { addr: 'E4.6', label: 'AH' },
  { addr: 'E4.7', label: 'MTC' }
]
// generate I/O (EL)
exports.outputs1 = [
  { addr: 'A4.0', label: 'SBK1' },
  { addr: 'A4.1', label: 'KBA' },
  { addr: 'A4.2', label: 'KXPA' },
  { addr: 'A4.3', label: 'SBZE' },
  { addr: 'A4.4', label: 'SBOE' },
  { addr: 'A4.5', label: '' },
  { addr: 'A4.6', label: '' },
  { addr: 'A4.7', label: 'SBK1' },
  { addr: 'A5.0', label: 'L1' },
  { addr: 'A5.1', label: 'L2' },
  { addr: 'A5.2', label: 'L3' },
  { addr: 'A5.3', label: 'L4' },
  { addr: 'A5.4', label: 'L5' },
  { addr: 'A5.5', label: 'RFE' },
  { addr: 'A5.6', label: 'RLN' },
  { addr: 'A5.7', label: 'KEM' },
  { addr: 'A6.0', label: 'SBK2' },
  { addr: 'A6.1', label: 'KBAe' },
  { addr: 'A6.2', label: 'KXPE' },
  { addr: 'A6.3', label: 'SBZA' },
  { addr: 'A6.4', label: 'SBOA' },
  { addr: 'A6.5', label: 'RFA' },
  { addr: 'A6.6', label: 'RLN' },
  { addr: 'A6.7', label: 'SBK2' },
  { addr: 'A7.0', label: 'SMA1' },
  { addr: 'A7.1', label: 'SMB1' },
  { addr: 'A7.2', label: 'SMA2' },
  { addr: 'A7.3', label: 'SMB2' },
  { addr: 'A7.4', label: '' },
  { addr: 'A7.5', label: 'LCSH' },
  { addr: 'A7.6', label: 'LA' },
  { addr: 'A7.7', label: 'LC' },
  { addr: 'A8.0', label: 'DYA' },
  { addr: 'A8.1', label: 'DYB' },
  { addr: 'A8.2', label: 'DYC' },
  { addr: 'A8.3', label: 'DYD' },
  { addr: 'A8.4', label: 'AD1' },
  { addr: 'A8.5', label: 'AD2' },
  { addr: 'A8.6', label: 'AD3' },
  { addr: 'A8.7', label: 'STR' },
  { addr: 'A9.0', label: 'LK' },
  { addr: 'A9.1', label: 'LE' },
  { addr: 'A9.2', label: 'LB' },
  { addr: 'A9.3', label: 'RDY' },
  { addr: 'A9.4', label: 'RST' },
  { addr: 'A9.5', label: '' },
  { addr: 'A9.6', label: '' },
  { addr: 'A9.7', label: '' },
  { addr: 'A10.0', label: '' },
  { addr: 'A10.1', label: '' },
  { addr: 'A10.2', label: '' },
  { addr: 'A10.3', label: '' },
  { addr: 'A10.4', label: '' },
  { addr: 'A10.5', label: '' },
  { addr: 'A10.6', label: '' },
  { addr: 'A10.7', label: '' },
  { addr: 'A11.0', label: 'LK' },
  { addr: 'A11.1', label: 'LE' },
  { addr: 'A11.2', label: 'LB' },
  { addr: 'A11.3', label: 'RDY' },
  { addr: 'A11.4', label: 'RST' },
  { addr: 'A11.5', label: '' },
  { addr: 'A11.6', label: '' },
  { addr: 'A11.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A24.0', label: 'SMA' },
  { addr: 'A24.1', label: 'SMB' },
  { addr: 'A24.2', label: 'TCR' },
  { addr: 'A24.3', label: 'TLS' },
  { addr: 'A24.4', label: '' },
  { addr: 'A24.5', label: '' },
  { addr: 'A24.6', label: '' },
  { addr: 'A24.7', label: '' },
  { addr: 'A25.0', label: '' },
  { addr: 'A25.1', label: '' },
  { addr: 'A25.2', label: '' },
  { addr: 'A25.3', label: '' },
  { addr: 'A25.4', label: '' },
  { addr: 'A25.5', label: '' },
  { addr: 'A25.6', label: '' },
  { addr: 'A25.7', label: '' }
]
exports.outputs3 = [
  { addr: 'A26.0', label: 'KQA' },
  { addr: 'A26.1', label: 'SBK1' },
  { addr: 'A26.2', label: 'SBK2' },
  { addr: 'A26.3', label: 'KBA' },
  { addr: 'A26.4', label: 'SMA1' },
  { addr: 'A26.5', label: 'SMB1' },
  { addr: 'A26.6', label: 'SMA2' },
  { addr: 'A26.7', label: 'SMB2' },
  { addr: 'A27.0', label: 'TD' },
  { addr: 'A27.1', label: '' },
  { addr: 'A27.2', label: '' },
  { addr: 'A27.3', label: '' },
  { addr: 'A27.4', label: '' },
  { addr: 'A27.5', label: '' },
  { addr: 'A27.6', label: '' },
  { addr: 'A27.7', label: 'KEM' },
  { addr: 'A28.0', label: 'DYA' },
  { addr: 'A28.1', label: 'DYB' },
  { addr: 'A28.2', label: 'DYC' },
  { addr: 'A28.3', label: 'DYD' },
  { addr: 'A28.4', label: 'AD1' },
  { addr: 'A28.5', label: 'AD2' },
  { addr: 'A28.6', label: 'AD3' },
  { addr: 'A28.7', label: 'ST3' },
  { addr: 'A29.0', label: '' },
  { addr: 'A29.1', label: '' },
  { addr: 'A29.2', label: '' },
  { addr: 'A29.3', label: '' },
  { addr: 'A29.4', label: '' },
  { addr: 'A29.5', label: '' },
  { addr: 'A29.6', label: '' },
  { addr: 'A29.7', label: 'LC' }
]
// generate I/O (SH)
exports.outputs4 = [
  { addr: 'A0.0', label: 'DYA' },
  { addr: 'A0.1', label: 'DYB' },
  { addr: 'A0.2', label: 'DYC' },
  { addr: 'A0.3', label: 'DYD' },
  { addr: 'A0.4', label: 'AD1' },
  { addr: 'A0.5', label: 'AD2' },
  { addr: 'A0.6', label: 'AD3' },
  { addr: 'A0.7', label: 'STR' },
  { addr: 'A1.0', label: 'T101' },
  { addr: 'A1.1', label: 'T2' },
  { addr: 'A1.2', label: 'TRA' },
  { addr: 'A1.3', label: 'TRB' },
  { addr: 'A1.4', label: 'KCS' },
  { addr: 'A1.5', label: 'KCV' },
  { addr: 'A1.6', label: 'KCH' },
  { addr: 'A1.7', label: 'TCR' }
]
exports.outputs5 = [
  { addr: 'A4.0', label: 'KBA' },
  { addr: 'A4.1', label: 'TCRE' },
  { addr: 'A4.2', label: '' },
  { addr: 'A4.3', label: '' },
  { addr: 'A4.4', label: 'T102' },
  { addr: 'A4.5', label: 'T10F' },
  { addr: 'A4.6', label: 'LA' },
  { addr: 'A4.7', label: 'LC' }
]
// generate Alarms
exports.ALARMS = [
  { id: 1, key: '', query: {} },
  { id: 2, key: '', query: {} },
  { id: 3, key: '', query: {} },
  { id: 4, key: '', query: {} },
  { id: 5, key: '', query: {} },
  { id: 6, key: '', query: {} },
  { id: 7, key: '', query: {} },
  { id: 8, key: '', query: {} },
  { id: 9, key: '', query: {} },
  { id: 10, key: '', query: {} },
  { id: 11, key: '', query: {} },
  { id: 12, key: '', query: {} },
  { id: 13, key: '', query: {} },
  { id: 14, key: '', query: {} },
  { id: 15, key: '', query: {} },
  { id: 16, key: '', query: {} },
  { id: 17, key: '', query: {} },
  { id: 18, key: '', query: {} },
  { id: 19, key: '', query: {} },
  { id: 20, key: '', query: {} },
  { id: 21, key: '', query: {} },
  { id: 22, key: '', query: {} },
  { id: 23, key: '', query: {} },
  { id: 24, key: '', query: {} },
  { id: 25, key: '', query: {} },
  { id: 26, key: '', query: {} },
  { id: 27, key: '', query: {} },
  { id: 28, key: '', query: {} },
  { id: 29, key: '', query: {} },
  { id: 30, key: '', query: {} },
  { id: 31, key: '', query: {} },
  { id: 32, key: '', query: {} },
  { id: 33, key: '', query: {} },
  { id: 34, key: '', query: {} },
  { id: 35, key: '', query: {} },
  { id: 36, key: '', query: {} },
  { id: 37, key: '', query: {} },
  { id: 38, key: '', query: {} },
  { id: 39, key: '', query: {} },
  { id: 40, key: '', query: {} },
  { id: 41, key: '', query: {} },
  { id: 42, key: '', query: {} },
  { id: 43, key: '', query: {} },
  { id: 44, key: '', query: {} },
  { id: 45, key: '', query: {} },
  { id: 46, key: '', query: {} },
  { id: 47, key: '', query: {} },
  { id: 48, key: '', query: {} },
  { id: 49, key: '', query: {} },
  { id: 50, key: '', query: {} },
  { id: 51, key: '', query: {} },
  { id: 52, key: '', query: {} },
  { id: 53, key: '', query: {} },
  { id: 54, key: '', query: {} },
  { id: 55, key: '', query: {} },
  { id: 56, key: '', query: {} },
  { id: 57, key: '', query: {} },
  { id: 58, key: '', query: {} },
  { id: 59, key: '', query: {} },
  { id: 60, key: '', query: {} },
  { id: 61, key: '', query: {} },
  { id: 62, key: '', query: {} },
  { id: 63, key: '', query: {} },
  { id: 64, key: '', query: {} },
  { id: 65, key: '', query: {} },
  { id: 66, key: '', query: {} },
  { id: 67, key: '', query: {} },
  { id: 68, key: '', query: {} },
  { id: 69, key: '', query: {} },
  { id: 70, key: '', query: {} },
  { id: 71, key: '', query: {} },
  { id: 72, key: '', query: {} },
  { id: 73, key: '', query: {} },
  { id: 74, key: '', query: {} },
  { id: 75, key: '', query: {} },
  { id: 76, key: '', query: {} },
  { id: 77, key: '', query: {} },
  { id: 78, key: '', query: {} },
  { id: 79, key: '', query: {} },
  { id: 80, key: '', query: {} },
  { id: 81, key: '', query: {} },
  { id: 82, key: '', query: {} },
  { id: 83, key: '', query: {} },
  { id: 84, key: '', query: {} },
  { id: 85, key: '', query: {} },
  { id: 86, key: '', query: {} },
  { id: 87, key: '', query: {} },
  { id: 88, key: '', query: {} },
  { id: 89, key: '', query: {} },
  { id: 90, key: '', query: {} },
  { id: 91, key: '', query: {} },
  { id: 92, key: '', query: {} },
  { id: 93, key: '', query: {} },
  { id: 94, key: '', query: {} },
  { id: 95, key: '', query: {} },
  { id: 96, key: '', query: {} },
  { id: 97, key: '', query: {} },
  { id: 98, key: '', query: {} },
  { id: 99, key: '', query: {} },
  { id: 100, key: '', query: {} },
  { id: 101, key: '', query: {} },
  { id: 102, key: '', query: {} },
  { id: 103, key: '', query: {} },
  { id: 104, key: '', query: {} },
  { id: 105, key: '', query: {} },
  { id: 106, key: '', query: {} },
  { id: 107, key: '', query: {} },
  { id: 108, key: '', query: {} },
  { id: 109, key: '', query: {} },
  { id: 110, key: '', query: {} },
  { id: 111, key: '', query: {} },
  { id: 112, key: '', query: {} },
  { id: 113, key: '', query: {} },
  { id: 114, key: '', query: {} },
  { id: 115, key: '', query: {} },
  { id: 116, key: '', query: {} },
  { id: 117, key: '', query: {} },
  { id: 118, key: '', query: {} },
  { id: 119, key: '', query: {} },
  { id: 120, key: '', query: {} },
  { id: 121, key: '', query: {} },
  { id: 122, key: '', query: {} },
  { id: 123, key: '', query: {} },
  { id: 124, key: '', query: {} },
  { id: 125, key: '', query: {} },
  { id: 126, key: '', query: {} },
  { id: 127, key: '', query: {} },
  { id: 128, key: '', query: {} }
]

exports.DEVICES = [
  { id: 0, key: 'operator' },
  { id: 1, key: 'EL' },
  { id: 2, key: 'E' },
  { id: 3, key: 'U' }
]
exports.MODES = [
  { id: 0, key: 'mode-no' },
  { id: 1, key: 'mode-data-edit' },
  { id: 2, key: 'mode-data-read' },
  { id: 3, key: 'mode-eme-1' },
  { id: 4, key: 'mode-eme-2' },
  { id: 5, key: 'mode-no' },
  { id: 6, key: 'mode-step' },
  { id: 7, key: 'mode-preset' },
  { id: 8, key: 'mode-auto' }
]
exports.OPERATIONS = [
  { id: 0, key: 'op-no' },
  { id: 1, key: 'op-alarm-on' },
  { id: 2, key: 'op-alarm-off' },
  { id: 3, key: 'op-switch-mode' },
  { id: 4, key: 'op-change-pin' },
  { id: 5, key: 'op-stall-in' },
  { id: 6, key: 'op-stall-out' },
  { id: 7, key: 'op-shuffle-in' },
  { id: 8, key: 'op-shuffle-out' },
  { id: 9, key: 'op-stall-rsv' },
  { id: 10, key: 'op-req-exit' },
  { id: 11, key: 'op-req-entry' },
  { id: 12, key: 'op-no' },
  { id: 13, key: 'op-no' },
  { id: 14, key: 'op-no' },
  { id: 15, key: 'op-no' },
  { id: 95, key: 'op-stall-in' },
  { id: 96, key: 'op-stall-out' },
  { id: 97, key: 'op-stall-lck' },
  { id: 98, key: 'op-shuffle-in' },
  { id: 99, key: 'op-shuffle-out' }
]
