exports.inputs1 = [
  { addr: 'E0.0', label: 'RSI' },
  { addr: 'E0.1', label: 'SA1' },
  { addr: 'E0.2', label: 'SA2' },
  { addr: 'E0.3', label: '' },
  { addr: 'E0.4', label: '' },
  { addr: 'E0.5', label: '' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' },
  { addr: 'E2.0', label: '' },
  { addr: 'E2.1', label: '' },
  { addr: 'E2.2', label: '' },
  { addr: 'E2.3', label: '' },
  { addr: 'E2.4', label: '' },
  { addr: 'E2.5', label: '' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: '' },
  { addr: 'E3.0', label: '' },
  { addr: 'E3.1', label: '' },
  { addr: 'E3.2', label: '' },
  { addr: 'E3.3', label: '' },
  { addr: 'E3.4', label: '' },
  { addr: 'E3.5', label: '' },
  { addr: 'E3.6', label: '' },
  { addr: 'E3.7', label: '' }
]
exports.inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: 'IV1' },
  { addr: 'E101.1', label: 'TJ1' },
  { addr: 'E101.2', label: 'TLK' },
  { addr: 'E101.3', label: 'RSI' },
  { addr: 'E101.4', label: 'SA' },
  { addr: 'E101.5', label: 'UC' },
  { addr: 'E101.6', label: '' },
  { addr: 'E101.7', label: '' },
  { addr: 'E102.0', label: '' },
  { addr: 'E102.1', label: '' },
  { addr: 'E102.2', label: '' },
  { addr: 'E102.3', label: '' },
  { addr: 'E102.4', label: 'FSBK' },
  { addr: 'E102.5', label: 'ASBK' },
  { addr: 'E102.6', label: 'RTA' },
  { addr: 'E102.7', label: 'AMC' },
  { addr: 'E103.0', label: 'EBZE' },
  { addr: 'E103.1', label: 'EBOE' },
  { addr: 'E103.2', label: 'FBBE' },
  { addr: 'E103.3', label: 'APBE' },
  { addr: 'E103.4', label: 'EZE' },
  { addr: 'E103.5', label: 'EOE' },
  { addr: 'E103.6', label: 'FBE' },
  { addr: 'E103.7', label: 'APE' },
  { addr: 'E104.0', label: 'EBZA' },
  { addr: 'E104.1', label: 'EBOA' },
  { addr: 'E104.2', label: 'FBBA' },
  { addr: 'E104.3', label: 'APBA' },
  { addr: 'E104.4', label: 'EZA' },
  { addr: 'E104.5', label: 'EOA' },
  { addr: 'E104.6', label: 'FBA' },
  { addr: 'E104.7', label: 'APA' },
  { addr: 'E105.0', label: 'FPE' },
  { addr: 'E105.1', label: 'FLP' },
  { addr: 'E105.2', label: 'FDR' },
  { addr: 'E105.3', label: 'FDL' },
  { addr: 'E105.4', label: 'FLA' },
  { addr: 'E105.5', label: 'FTA1' },
  { addr: 'E105.6', label: 'FTA2' },
  { addr: 'E105.7', label: 'RXE' },
  { addr: 'E106.0', label: 'FPA' },
  { addr: 'E106.1', label: 'RXA' },
  { addr: 'E106.2', label: 'FRSX' },
  { addr: 'E106.3', label: 'FRDX' },
  { addr: 'E106.4', label: '' },
  { addr: 'E106.5', label: '' },
  { addr: 'E106.6', label: '' },
  { addr: 'E106.7', label: '' },
  { addr: 'E107.0', label: 'ECA' },
  { addr: 'E107.1', label: 'ECB' },
  { addr: 'E107.2', label: '' },
  { addr: 'E107.3', label: '' },
  { addr: 'E107.4', label: '' },
  { addr: 'E107.5', label: '' },
  { addr: 'E107.6', label: 'EPZV' },
  { addr: 'E107.7', label: 'EPZH' },
  { addr: 'E108.0', label: '' },
  { addr: 'E108.1', label: '' },
  { addr: 'E108.2', label: '' },
  { addr: 'E108.3', label: '' },
  { addr: 'E108.4', label: '' },
  { addr: 'E108.5', label: '' },
  { addr: 'E108.6', label: '' },
  { addr: 'E108.7', label: '' },
  { addr: 'E109.0', label: '' },
  { addr: 'E109.1', label: '' },
  { addr: 'E109.2', label: '' },
  { addr: 'E109.3', label: '' },
  { addr: 'E109.4', label: '' },
  { addr: 'E109.5', label: '' },
  { addr: 'E109.6', label: '' },
  { addr: 'E109.7', label: '' }
]
exports.inputs3 = [
  { addr: 'E110.0', label: 'AGK' },
  { addr: 'E110.1', label: 'TL' },
  { addr: 'E110.2', label: 'AMM' },
  { addr: 'E110.3', label: '' },
  { addr: 'E110.4', label: '' },
  { addr: 'E110.5', label: 'EOM' },
  { addr: 'E110.6', label: 'EZM' },
  { addr: 'E110.7', label: 'EMC' },
  { addr: 'E111.0', label: '' },
  { addr: 'E111.1', label: '' },
  { addr: 'E111.2', label: '' },
  { addr: 'E111.3', label: '' },
  { addr: 'E111.4', label: '' },
  { addr: 'E111.5', label: '' },
  { addr: 'E111.6', label: '' },
  { addr: 'E111.7', label: '' }
]
exports.inputs4 = [
  { addr: 'E120.0', label: 'A' },
  { addr: 'E120.1', label: 'B' },
  { addr: 'E120.2', label: 'C' },
  { addr: 'E120.3', label: 'D' },
  { addr: 'E120.4', label: 'OK' },
  { addr: 'E120.5', label: 'S2' },
  { addr: 'E120.6', label: 'S2' },
  { addr: 'E120.7', label: 'S2' },
  { addr: 'E121.0', label: 'EM' },
  { addr: 'E121.1', label: 'FTXV' },
  { addr: 'E121.2', label: 'FTXH' },
  { addr: 'E121.3', label: 'FTAC' },
  { addr: 'E121.4', label: '' },
  { addr: 'E121.5', label: '' },
  { addr: 'E121.6', label: '' },
  { addr: 'E121.7', label: '' },
  { addr: 'E122.0', label: 'RMV' },
  { addr: 'E122.1', label: 'RMH' },
  { addr: 'E122.2', label: 'RES' },
  { addr: 'E122.3', label: 'REH' },
  { addr: 'E122.4', label: 'RCV' },
  { addr: 'E122.5', label: 'REAV' },
  { addr: 'E122.6', label: 'REAH' },
  { addr: 'E122.7', label: 'RCH' },
  { addr: 'E123.0', label: 'IV2' },
  { addr: 'E123.1', label: 'TJ2' },
  { addr: 'E123.2', label: 'SA' },
  { addr: 'E123.3', label: 'RSI' },
  { addr: 'E123.4', label: 'DB32' },
  { addr: 'E123.5', label: 'DBHZ' },
  { addr: 'E123.6', label: '' },
  { addr: 'E123.7', label: 'UC' },
  { addr: 'E124.0', label: 'AH' },
  { addr: 'E124.1', label: 'MTC' },
  { addr: 'E124.2', label: '' },
  { addr: 'E124.3', label: '' },
  { addr: 'E124.4', label: '' },
  { addr: 'E124.5', label: '' },
  { addr: 'E124.6', label: '' },
  { addr: 'E124.7', label: '' },
  { addr: 'E125.0', label: '' },
  { addr: 'E125.1', label: '' },
  { addr: 'E125.2', label: '' },
  { addr: 'E125.3', label: '' },
  { addr: 'E125.4', label: '' },
  { addr: 'E125.5', label: '' },
  { addr: 'E125.6', label: '' },
  { addr: 'E125.7', label: '' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'TRGU' },
  { addr: 'A0.1', label: 'TRG1' },
  { addr: 'A0.2', label: 'TRG2' },
  { addr: 'A0.3', label: '' },
  { addr: 'A0.4', label: '' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' },
  { addr: 'A2.0', label: '' },
  { addr: 'A2.1', label: '' },
  { addr: 'A2.2', label: '' },
  { addr: 'A2.3', label: '' },
  { addr: 'A2.4', label: '' },
  { addr: 'A2.5', label: '' },
  { addr: 'A2.6', label: '' },
  { addr: 'A2.7', label: '' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A100.0', label: 'SBK1' },
  { addr: 'A100.1', label: 'SBK2' },
  { addr: 'A100.2', label: '' },
  { addr: 'A100.3', label: '' },
  { addr: 'A100.4', label: 'KBA' },
  { addr: 'A100.5', label: 'KST' },
  { addr: 'A100.6', label: 'LA' },
  { addr: 'A100.7', label: 'LC' },
  { addr: 'A101.0', label: 'DYA' },
  { addr: 'A101.1', label: 'DYB' },
  { addr: 'A101.2', label: 'DYC' },
  { addr: 'A101.3', label: 'DYD' },
  { addr: 'A101.4', label: 'AD1' },
  { addr: 'A101.5', label: 'AD2' },
  { addr: 'A101.6', label: 'AD3' },
  { addr: 'A101.7', label: 'STR' },
  { addr: 'A102.0', label: 'SCA' },
  { addr: 'A102.1', label: 'SCB' },
  { addr: 'A102.2', label: 'SPE' },
  { addr: 'A102.3', label: 'SPBE' },
  { addr: 'A102.4', label: 'SPA' },
  { addr: 'A102.5', label: 'SPBA' },
  { addr: 'A102.6', label: '' },
  { addr: 'A102.7', label: '' },
  { addr: 'A103.0', label: 'RFA' },
  { addr: 'A103.1', label: 'RFE' },
  { addr: 'A103.2', label: 'L5' },
  { addr: 'A103.3', label: 'L4' },
  { addr: 'A103.4', label: 'L3' },
  { addr: 'A103.5', label: 'L2' },
  { addr: 'A103.6', label: 'L1' },
  { addr: 'A103.7', label: '' },
  { addr: 'A104.0', label: 'SBZE' },
  { addr: 'A104.1', label: 'SBOE' },
  { addr: 'A104.2', label: 'SZE' },
  { addr: 'A104.3', label: 'SOE' },
  { addr: 'A104.4', label: 'SBZA' },
  { addr: 'A104.5', label: 'SBOA' },
  { addr: 'A104.6', label: 'SZA' },
  { addr: 'A104.7', label: 'SOA' },
  { addr: 'A105.0', label: '' },
  { addr: 'A105.1', label: '' },
  { addr: 'A105.2', label: '' },
  { addr: 'A105.3', label: '' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: '' },
  { addr: 'A106.0', label: '' },
  { addr: 'A106.1', label: '' },
  { addr: 'A106.2', label: '' },
  { addr: 'A106.3', label: '' },
  { addr: 'A106.4', label: '' },
  { addr: 'A106.5', label: '' },
  { addr: 'A106.6', label: '' },
  { addr: 'A106.7', label: '' },
  { addr: 'A107.0', label: '' },
  { addr: 'A107.1', label: '' },
  { addr: 'A107.2', label: '' },
  { addr: 'A107.3', label: '' },
  { addr: 'A107.4', label: '' },
  { addr: 'A107.5', label: '' },
  { addr: 'A107.6', label: '' },
  { addr: 'A107.7', label: '' }
]
exports.outputs3 = [
  { addr: 'A110.0', label: 'SMA' },
  { addr: 'A110.1', label: 'SMB' },
  { addr: 'A110.2', label: 'LA' },
  { addr: 'A110.3', label: '' },
  { addr: 'A110.4', label: '' },
  { addr: 'A110.5', label: '' },
  { addr: 'A110.6', label: '' },
  { addr: 'A110.7', label: '' },
  { addr: 'A111.0', label: '' },
  { addr: 'A111.1', label: '' },
  { addr: 'A111.2', label: '' },
  { addr: 'A111.3', label: '' },
  { addr: 'A111.4', label: '' },
  { addr: 'A111.5', label: '' },
  { addr: 'A111.6', label: '' },
  { addr: 'A111.7', label: '' }
]
exports.outputs4 = [
  { addr: 'A120.0', label: 'DYA' },
  { addr: 'A120.1', label: 'DYB' },
  { addr: 'A120.2', label: 'DYC' },
  { addr: 'A120.3', label: 'DYD' },
  { addr: 'A120.4', label: 'AD1' },
  { addr: 'A120.5', label: 'AD2' },
  { addr: 'A120.6', label: 'AD3' },
  { addr: 'A120.7', label: 'STR' },
  { addr: 'A121.0', label: 'T101' },
  { addr: 'A121.1', label: 'T102' },
  { addr: 'A121.2', label: 'T2' },
  { addr: 'A121.3', label: 'T10F' },
  { addr: 'A121.4', label: 'TRA' },
  { addr: 'A121.5', label: 'TRB' },
  { addr: 'A121.6', label: 'LA' },
  { addr: 'A121.7', label: 'LC' },
  { addr: 'A122.0', label: 'KCS' },
  { addr: 'A122.1', label: 'KCV' },
  { addr: 'A122.2', label: 'KCH' },
  { addr: 'A122.3', label: 'KBA' },
  { addr: 'A122.4', label: 'KST' },
  { addr: 'A122.5', label: '' },
  { addr: 'A122.6', label: '' },
  { addr: 'A122.7', label: '' },
  { addr: 'A123.0', label: '' },
  { addr: 'A123.1', label: '' },
  { addr: 'A123.2', label: '' },
  { addr: 'A123.3', label: '' },
  { addr: 'A123.4', label: '' },
  { addr: 'A123.5', label: '' },
  { addr: 'A123.6', label: '' },
  { addr: 'A123.7', label: '' }
]
exports.EL = [
  { label: 'AL1', i18n: { key: 'al-sil-01', query: {} } },
  { label: 'AL2', i18n: { key: 'al-sil-01', query: {} } },
  { label: 'AL3', i18n: { key: 'al-sil-01', query: {} } },
  { label: 'AL4', i18n: { key: 'al-sil-02', query: {} } },
  { label: 'AL5', i18n: { key: 'al-sil-03', query: {} } },
  { label: 'AL6', i18n: { key: 'al-sil-04', query: {} } },
  { label: 'AL7', i18n: { key: 'al-v-to', query: {} } },
  { label: 'AL8', i18n: { key: 'al-h-to', query: {} } },
  { label: 'AL9', i18n: { key: 'al-flap-to', query: {} } },
  { label: 'AL10', i18n: { key: 'al-v-fdbk', query: {} } },
  { label: 'AL11', i18n: { key: 'al-v-fdbk', query: {} } },
  { label: 'AL12', i18n: { key: 'al-v-lck-to', query: {} } },
  { label: 'AL13', i18n: { key: 'al-spbe-to', query: {} } },
  { label: 'AL14', i18n: { key: 'al-spe-to', query: {} } },
  { label: 'AL15', i18n: { key: 'al-spba-to', query: {} } },
  { label: 'AL16', i18n: { key: 'al-spa-to', query: {} } },
  {
    label: 'AL17',
    i18n: { key: 'al-th', query: { name: 'ASBK' } }
  },
  {
    label: 'AL18',
    i18n: { key: 'al-th', query: { name: 'RTA' } }
  },
  {
    label: 'AL19',
    i18n: { key: 'al-th', query: { name: 'AMC' } }
  },
  {
    label: 'AL20',
    i18n: { key: 'al-th', query: { name: 'APBE' } }
  },
  {
    label: 'AL21',
    i18n: { key: 'al-th', query: { name: 'APE' } }
  },
  {
    label: 'AL22',
    i18n: { key: 'al-th', query: { name: 'APBA' } }
  },
  {
    label: 'AL23',
    i18n: { key: 'al-th', query: { name: 'APA' } }
  },
  {
    label: 'AL24',
    i18n: { key: 'al-th', query: { name: 'AGK' } }
  },
  {
    label: 'AL25',
    i18n: { key: 'al-th', query: { name: 'AMM' } }
  },
  { label: 'AL26', i18n: { key: 'al-tl', query: { name: 'TLK' } } },
  { label: 'AL27', i18n: { key: 'al-tl', query: { name: 'TL' } } },
  { label: 'AL28', i18n: { key: 'al-tl', query: { name: 'TJ1' } } },
  { label: 'AL29', i18n: { key: 'al-tl', query: { name: 'TJ2' } } },
  { label: 'AL30', i18n: { key: '', query: {} } },
  { label: 'AL31', i18n: { key: '', query: {} } },
  { label: 'AL32', i18n: { key: '', query: {} } },
  {
    label: 'AL33',
    i18n: { key: 'al-fc', query: { fc1: 'EOM', fc2: 'EZM' } }
  },
  { label: 'AL34', i18n: { key: 'al-sil-07', query: {} } },
  { label: 'AL35', i18n: { key: 'al-sil-10', query: {} } },
  { label: 'AL36', i18n: { key: 'al-sil-13', query: {} } },
  {
    label: 'AL37',
    i18n: { key: 'al-fc', query: { fc1: 'ECA', fc2: 'ECB' } }
  },
  {
    label: 'AL38',
    i18n: { key: 'al-fc', query: { fc1: 'EBZE', fc2: 'EBOE' } }
  },
  {
    label: 'AL39',
    i18n: { key: 'al-fc', query: { fc1: 'EZE', fc2: 'EOE' } }
  },
  {
    label: 'AL40',
    i18n: { key: 'al-fc', query: { fc1: 'EBZA', fc2: 'EBOA' } }
  },
  {
    label: 'AL41',
    i18n: { key: 'al-fc', query: { fc1: 'EZA', fc2: 'EOA' } }
  },
  { label: 'AL42', i18n: { key: '', query: {} } },
  { label: 'AL43', i18n: { key: '', query: {} } },
  { label: 'AL44', i18n: { key: '', query: {} } },
  { label: 'AL45', i18n: { key: '', query: {} } },
  { label: 'AL46', i18n: { key: '', query: {} } },
  { label: 'AL47', i18n: { key: '', query: {} } },
  { label: 'AL48', i18n: { key: '', query: {} } },
  { label: 'AL49', i18n: { key: 'al-lv', query: {} } },
  { label: 'AL50', i18n: { key: 'al-lv', query: {} } },
  { label: 'AL51', i18n: { key: 'al-lh', query: {} } },
  { label: 'AL52', i18n: { key: 'al-lh', query: {} } },
  { label: 'AL53', i18n: { key: 'al-lv-diff', query: {} } },
  { label: 'AL54', i18n: { key: 'al-lh-diff', query: {} } },
  { label: 'AL55', i18n: { key: '', query: {} } },
  { label: 'AL56', i18n: { key: '', query: {} } },
  { label: 'AL57', i18n: { key: '', query: {} } },
  { label: 'AL58', i18n: { key: '', query: {} } },
  { label: 'AL59', i18n: { key: '', query: {} } },
  { label: 'AL60', i18n: { key: '', query: {} } },
  { label: 'AL61', i18n: { key: '', query: {} } },
  { label: 'AL62', i18n: { key: '', query: {} } },
  { label: 'AL63', i18n: { key: '', query: {} } },
  { label: 'AL64', i18n: { key: '', query: {} } }
]
