exports.inputs1 = [
  { addr: 'E0.0', label: '' },
  { addr: 'E0.1', label: '' },
  { addr: 'E0.2', label: '' },
  { addr: 'E0.3', label: '' },
  { addr: 'E0.4', label: '' },
  { addr: 'E0.5', label: '' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' },
  { addr: 'E2.0', label: '' },
  { addr: 'E2.1', label: '' },
  { addr: 'E2.2', label: '' },
  { addr: 'E2.3', label: '' },
  { addr: 'E2.4', label: '' },
  { addr: 'E2.5', label: '' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: '' },
  { addr: 'E3.0', label: '' },
  { addr: 'E3.1', label: '' },
  { addr: 'E3.2', label: '' },
  { addr: 'E3.3', label: '' },
  { addr: 'E3.4', label: '' },
  { addr: 'E3.5', label: '' },
  { addr: 'E3.6', label: '' },
  { addr: 'E3.7', label: '' }
]
exports.inputs2 = [
  { addr: 'E100.0', label: '' },
  { addr: 'E100.1', label: '' },
  { addr: 'E100.2', label: '' },
  { addr: 'E100.3', label: '' },
  { addr: 'E100.4', label: '' },
  { addr: 'E100.5', label: '' },
  { addr: 'E100.6', label: '' },
  { addr: 'E100.7', label: '' },
  { addr: 'E101.0', label: '' },
  { addr: 'E101.1', label: '' },
  { addr: 'E101.2', label: '' },
  { addr: 'E101.3', label: '' },
  { addr: 'E101.4', label: '' },
  { addr: 'E101.5', label: '' },
  { addr: 'E101.6', label: '' },
  { addr: 'E101.7', label: '' },
  { addr: 'E102.0', label: '' },
  { addr: 'E102.1', label: '' },
  { addr: 'E102.2', label: '' },
  { addr: 'E102.3', label: '' },
  { addr: 'E102.4', label: '' },
  { addr: 'E102.5', label: '' },
  { addr: 'E102.6', label: '' },
  { addr: 'E102.7', label: '' },
  { addr: 'E103.0', label: '' },
  { addr: 'E103.1', label: '' },
  { addr: 'E103.2', label: '' },
  { addr: 'E103.3', label: '' },
  { addr: 'E103.4', label: '' },
  { addr: 'E103.5', label: '' },
  { addr: 'E103.6', label: '' },
  { addr: 'E103.7', label: '' },
  { addr: 'E104.0', label: '' },
  { addr: 'E104.1', label: '' },
  { addr: 'E104.2', label: '' },
  { addr: 'E104.3', label: '' },
  { addr: 'E104.4', label: '' },
  { addr: 'E104.5', label: '' },
  { addr: 'E104.6', label: '' },
  { addr: 'E104.7', label: '' },
  { addr: 'E105.0', label: '' },
  { addr: 'E105.1', label: '' },
  { addr: 'E105.2', label: '' },
  { addr: 'E105.3', label: '' },
  { addr: 'E105.4', label: '' },
  { addr: 'E105.5', label: '' },
  { addr: 'E105.6', label: '' },
  { addr: 'E105.7', label: '' },
  { addr: 'E106.0', label: '' },
  { addr: 'E106.1', label: '' },
  { addr: 'E106.2', label: '' },
  { addr: 'E106.3', label: '' },
  { addr: 'E106.4', label: '' },
  { addr: 'E106.5', label: '' },
  { addr: 'E106.6', label: '' },
  { addr: 'E106.7', label: '' },
  { addr: 'E107.0', label: '' },
  { addr: 'E107.1', label: '' },
  { addr: 'E107.2', label: '' },
  { addr: 'E107.3', label: '' },
  { addr: 'E107.4', label: '' },
  { addr: 'E107.5', label: '' },
  { addr: 'E107.6', label: '' },
  { addr: 'E107.7', label: '' },
  { addr: 'E108.0', label: '' },
  { addr: 'E108.1', label: '' },
  { addr: 'E108.2', label: '' },
  { addr: 'E108.3', label: '' },
  { addr: 'E108.4', label: '' },
  { addr: 'E108.5', label: '' },
  { addr: 'E108.6', label: '' },
  { addr: 'E108.7', label: '' },
  { addr: 'E109.0', label: '' },
  { addr: 'E109.1', label: '' },
  { addr: 'E109.2', label: '' },
  { addr: 'E109.3', label: '' },
  { addr: 'E109.4', label: '' },
  { addr: 'E109.5', label: '' },
  { addr: 'E109.6', label: '' },
  { addr: 'E109.7', label: '' }
]
exports.inputs3 = [
  { addr: 'E110.0', label: '' },
  { addr: 'E110.1', label: '' },
  { addr: 'E110.2', label: '' },
  { addr: 'E110.3', label: '' },
  { addr: 'E110.4', label: '' },
  { addr: 'E110.5', label: '' },
  { addr: 'E110.6', label: '' },
  { addr: 'E110.7', label: '' },
  { addr: 'E111.0', label: '' },
  { addr: 'E111.1', label: '' },
  { addr: 'E111.2', label: '' },
  { addr: 'E111.3', label: '' },
  { addr: 'E111.4', label: '' },
  { addr: 'E111.5', label: '' },
  { addr: 'E111.6', label: '' },
  { addr: 'E111.7', label: '' }
]
exports.inputs4 = [
  { addr: 'E120.0', label: '' },
  { addr: 'E120.1', label: '' },
  { addr: 'E120.2', label: '' },
  { addr: 'E120.3', label: '' },
  { addr: 'E120.4', label: '' },
  { addr: 'E120.5', label: '' },
  { addr: 'E120.6', label: '' },
  { addr: 'E120.7', label: '' },
  { addr: 'E121.0', label: '' },
  { addr: 'E121.1', label: '' },
  { addr: 'E121.2', label: '' },
  { addr: 'E121.3', label: '' },
  { addr: 'E121.4', label: '' },
  { addr: 'E121.5', label: '' },
  { addr: 'E121.6', label: '' },
  { addr: 'E121.7', label: '' },
  { addr: 'E122.0', label: 'RMV' },
  { addr: 'E122.1', label: 'RMH' },
  { addr: 'E122.2', label: 'RES' },
  { addr: 'E122.3', label: 'REH' },
  { addr: 'E122.4', label: 'RCV' },
  { addr: 'E122.5', label: 'REAV' },
  { addr: 'E122.6', label: 'REAH' },
  { addr: 'E122.7', label: 'RCH' },
  { addr: 'E123.0', label: '' },
  { addr: 'E123.1', label: '' },
  { addr: 'E123.2', label: '' },
  { addr: 'E123.3', label: '' },
  { addr: 'E123.4', label: '' },
  { addr: 'E123.5', label: '' },
  { addr: 'E123.6', label: '' },
  { addr: 'E123.7', label: '' },
  { addr: 'E124.0', label: '' },
  { addr: 'E124.1', label: '' },
  { addr: 'E124.2', label: '' },
  { addr: 'E124.3', label: '' },
  { addr: 'E124.4', label: '' },
  { addr: 'E124.5', label: '' },
  { addr: 'E124.6', label: '' },
  { addr: 'E124.7', label: '' },
  { addr: 'E125.0', label: '' },
  { addr: 'E125.1', label: '' },
  { addr: 'E125.2', label: '' },
  { addr: 'E125.3', label: '' },
  { addr: 'E125.4', label: '' },
  { addr: 'E125.5', label: '' },
  { addr: 'E125.6', label: '' },
  { addr: 'E125.7', label: '' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: '' },
  { addr: 'A0.1', label: '' },
  { addr: 'A0.2', label: '' },
  { addr: 'A0.3', label: '' },
  { addr: 'A0.4', label: '' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' },
  { addr: 'A2.0', label: '' },
  { addr: 'A2.1', label: '' },
  { addr: 'A2.2', label: '' },
  { addr: 'A2.3', label: '' },
  { addr: 'A2.4', label: '' },
  { addr: 'A2.5', label: '' },
  { addr: 'A2.6', label: '' },
  { addr: 'A2.7', label: '' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A100.0', label: '' },
  { addr: 'A100.1', label: '' },
  { addr: 'A100.2', label: '' },
  { addr: 'A100.3', label: '' },
  { addr: 'A100.4', label: '' },
  { addr: 'A100.5', label: '' },
  { addr: 'A100.6', label: '' },
  { addr: 'A100.7', label: '' },
  { addr: 'A101.0', label: '' },
  { addr: 'A101.1', label: '' },
  { addr: 'A101.2', label: '' },
  { addr: 'A101.3', label: '' },
  { addr: 'A101.4', label: '' },
  { addr: 'A101.5', label: '' },
  { addr: 'A101.6', label: '' },
  { addr: 'A101.7', label: '' },
  { addr: 'A102.0', label: '' },
  { addr: 'A102.1', label: '' },
  { addr: 'A102.2', label: '' },
  { addr: 'A102.3', label: '' },
  { addr: 'A102.4', label: '' },
  { addr: 'A102.5', label: '' },
  { addr: 'A102.6', label: '' },
  { addr: 'A102.7', label: '' },
  { addr: 'A103.0', label: '' },
  { addr: 'A103.1', label: '' },
  { addr: 'A103.2', label: '' },
  { addr: 'A103.3', label: '' },
  { addr: 'A103.4', label: '' },
  { addr: 'A103.5', label: '' },
  { addr: 'A103.6', label: '' },
  { addr: 'A103.7', label: '' },
  { addr: 'A104.0', label: '' },
  { addr: 'A104.1', label: '' },
  { addr: 'A104.2', label: '' },
  { addr: 'A104.3', label: '' },
  { addr: 'A104.4', label: '' },
  { addr: 'A104.5', label: '' },
  { addr: 'A104.6', label: '' },
  { addr: 'A104.7', label: '' },
  { addr: 'A105.0', label: '' },
  { addr: 'A105.1', label: '' },
  { addr: 'A105.2', label: '' },
  { addr: 'A105.3', label: '' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: '' },
  { addr: 'A106.0', label: '' },
  { addr: 'A106.1', label: '' },
  { addr: 'A106.2', label: '' },
  { addr: 'A106.3', label: '' },
  { addr: 'A106.4', label: '' },
  { addr: 'A106.5', label: '' },
  { addr: 'A106.6', label: '' },
  { addr: 'A106.7', label: '' },
  { addr: 'A107.0', label: '' },
  { addr: 'A107.1', label: '' },
  { addr: 'A107.2', label: '' },
  { addr: 'A107.3', label: '' },
  { addr: 'A107.4', label: '' },
  { addr: 'A107.5', label: '' },
  { addr: 'A107.6', label: '' },
  { addr: 'A107.7', label: '' }
]
exports.outputs3 = [
  { addr: 'A110.0', label: '' },
  { addr: 'A110.1', label: '' },
  { addr: 'A110.2', label: '' },
  { addr: 'A110.3', label: '' },
  { addr: 'A110.4', label: '' },
  { addr: 'A110.5', label: '' },
  { addr: 'A110.6', label: '' },
  { addr: 'A110.7', label: '' },
  { addr: 'A111.0', label: '' },
  { addr: 'A111.1', label: '' },
  { addr: 'A111.2', label: '' },
  { addr: 'A111.3', label: '' },
  { addr: 'A111.4', label: '' },
  { addr: 'A111.5', label: '' },
  { addr: 'A111.6', label: '' },
  { addr: 'A111.7', label: '' }
]
exports.outputs4 = [
  { addr: 'A120.0', label: '' },
  { addr: 'A120.1', label: '' },
  { addr: 'A120.2', label: '' },
  { addr: 'A120.3', label: '' },
  { addr: 'A120.4', label: '' },
  { addr: 'A120.5', label: '' },
  { addr: 'A120.6', label: '' },
  { addr: 'A120.7', label: '' },
  { addr: 'A121.0', label: '' },
  { addr: 'A121.1', label: '' },
  { addr: 'A121.2', label: 'T2' },
  { addr: 'A121.3', label: '' },
  { addr: 'A121.4', label: 'TRA' },
  { addr: 'A121.5', label: 'TRB' },
  { addr: 'A121.6', label: '' },
  { addr: 'A121.7', label: '' },
  { addr: 'A122.0', label: 'KCS' },
  { addr: 'A122.1', label: 'KCV' },
  { addr: 'A122.2', label: 'KCH' },
  { addr: 'A122.3', label: '' },
  { addr: 'A122.4', label: '' },
  { addr: 'A122.5', label: '' },
  { addr: 'A122.6', label: '' },
  { addr: 'A122.7', label: '' },
  { addr: 'A123.0', label: '' },
  { addr: 'A123.1', label: '' },
  { addr: 'A123.2', label: '' },
  { addr: 'A123.3', label: '' },
  { addr: 'A123.4', label: '' },
  { addr: 'A123.5', label: '' },
  { addr: 'A123.6', label: '' },
  { addr: 'A123.7', label: '' }
]
exports.alarms1 = [
  { class: '1', label: 'AL1', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL2', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL3', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL4', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL5', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL6', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL7', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL8', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL9', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL10', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL11', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL12', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL13', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL14', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL15', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL16', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL17', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL18', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL19', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL20', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL21', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL22', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL23', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL24', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL25', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL26', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL27', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL28', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL29', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL30', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL31', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL32', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL33', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL34', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL35', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL36', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL37', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL38', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL39', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL40', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL41', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL42', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL43', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL44', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL45', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL46', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL47', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL48', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL49', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL50', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL51', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL52', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL53', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL54', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL55', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL56', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL57', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL58', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL59', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL60', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL61', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL62', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL63', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL64', i18n: { key: '', query: {} } }
]
exports.alarms2 = [
  { class: '2', label: 'AL1', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL2', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL3', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL4', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL5', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL6', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL7', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL8', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL9', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL10', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL11', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL12', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL13', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL14', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL15', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL16', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL17', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL18', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL19', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL20', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL21', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL22', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL23', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL24', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL25', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL26', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL27', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL28', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL29', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL30', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL31', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL32', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL33', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL34', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL35', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL36', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL37', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL38', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL39', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL40', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL41', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL42', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL43', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL44', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL45', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL46', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL47', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL48', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL49', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL50', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL51', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL52', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL53', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL54', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL55', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL56', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL57', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL58', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL59', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL60', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL61', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL62', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL63', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL64', i18n: { key: '', query: {} } }
]
