exports.inputs1 = [
  { addr: 'E4.0', label: '' },
  { addr: 'E4.1', label: '' },
  { addr: 'E4.2', label: '' },
  { addr: 'E4.3', label: '' },
  { addr: 'E4.4', label: '' },
  { addr: 'E4.5', label: '' },
  { addr: 'E4.6', label: '' },
  { addr: 'E4.7', label: '' },
  { addr: 'E5.0', label: '' },
  { addr: 'E5.1', label: '' },
  { addr: 'E5.2', label: '' },
  { addr: 'E5.3', label: '' },
  { addr: 'E5.4', label: '' },
  { addr: 'E5.5', label: '' },
  { addr: 'E5.6', label: '' },
  { addr: 'E5.7', label: '' },
  { addr: 'E6.0', label: '' },
  { addr: 'E6.1', label: '' },
  { addr: 'E6.2', label: '' },
  { addr: 'E6.3', label: '' },
  { addr: 'E6.4', label: '' },
  { addr: 'E6.5', label: '' },
  { addr: 'E6.6', label: '' },
  { addr: 'E6.7', label: '' },
  { addr: 'E7.0', label: '' },
  { addr: 'E7.1', label: '' },
  { addr: 'E7.2', label: '' },
  { addr: 'E7.3', label: '' },
  { addr: 'E7.4', label: '' },
  { addr: 'E7.5', label: '' },
  { addr: 'E7.6', label: '' },
  { addr: 'E7.7', label: '' },
  { addr: 'E8.0', label: '' },
  { addr: 'E8.1', label: '' },
  { addr: 'E8.2', label: '' },
  { addr: 'E8.3', label: '' },
  { addr: 'E8.4', label: '' },
  { addr: 'E8.5', label: '' },
  { addr: 'E8.6', label: '' },
  { addr: 'E8.7', label: '' },
  { addr: 'E9.0', label: '' },
  { addr: 'E9.1', label: '' },
  { addr: 'E9.2', label: '' },
  { addr: 'E9.3', label: '' },
  { addr: 'E9.4', label: '' },
  { addr: 'E9.5', label: '' },
  { addr: 'E9.6', label: '' },
  { addr: 'E9.7', label: '' },
  { addr: 'E10.0', label: '' },
  { addr: 'E10.1', label: '' },
  { addr: 'E10.2', label: '' },
  { addr: 'E10.3', label: '' },
  { addr: 'E10.4', label: '' },
  { addr: 'E10.5', label: '' },
  { addr: 'E10.6', label: '' },
  { addr: 'E10.7', label: '' },
  { addr: 'E11.0', label: '' },
  { addr: 'E11.1', label: '' },
  { addr: 'E11.2', label: '' },
  { addr: 'E11.3', label: '' },
  { addr: 'E11.4', label: '' },
  { addr: 'E11.5', label: '' },
  { addr: 'E11.6', label: '' },
  { addr: 'E11.7', label: '' },
  { addr: 'E12.0', label: '' },
  { addr: 'E12.1', label: '' },
  { addr: 'E12.2', label: '' },
  { addr: 'E12.3', label: '' },
  { addr: 'E12.4', label: '' },
  { addr: 'E12.5', label: '' },
  { addr: 'E12.6', label: '' },
  { addr: 'E12.7', label: '' },
  { addr: 'E13.0', label: '' },
  { addr: 'E13.1', label: '' },
  { addr: 'E13.2', label: '' },
  { addr: 'E13.3', label: '' },
  { addr: 'E13.4', label: '' },
  { addr: 'E13.5', label: '' },
  { addr: 'E13.6', label: '' },
  { addr: 'E13.7', label: '' }
]
exports.inputs2 = [
  { addr: 'E14.0', label: '' },
  { addr: 'E14.1', label: '' },
  { addr: 'E14.2', label: '' },
  { addr: 'E14.3', label: '' },
  { addr: 'E14.4', label: '' },
  { addr: 'E14.5', label: '' },
  { addr: 'E14.6', label: '' },
  { addr: 'E14.7', label: '' },
  { addr: 'E15.0', label: '' },
  { addr: 'E15.1', label: '' },
  { addr: 'E15.2', label: '' },
  { addr: 'E15.3', label: '' },
  { addr: 'E15.4', label: '' },
  { addr: 'E15.5', label: '' },
  { addr: 'E15.6', label: '' },
  { addr: 'E15.7', label: '' },
  { addr: 'E16.0', label: '' },
  { addr: 'E16.1', label: '' },
  { addr: 'E16.2', label: '' },
  { addr: 'E16.3', label: '' },
  { addr: 'E16.4', label: '' },
  { addr: 'E16.5', label: '' },
  { addr: 'E16.6', label: '' },
  { addr: 'E16.7', label: '' },
  { addr: 'E17.0', label: '' },
  { addr: 'E17.1', label: '' },
  { addr: 'E17.2', label: '' },
  { addr: 'E17.3', label: '' },
  { addr: 'E17.4', label: '' },
  { addr: 'E17.5', label: '' },
  { addr: 'E17.6', label: '' },
  { addr: 'E17.7', label: '' }
]
exports.outputs1 = [
  { addr: 'A4.0', label: '' },
  { addr: 'A4.1', label: '' },
  { addr: 'A4.2', label: '' },
  { addr: 'A4.3', label: '' },
  { addr: 'A4.4', label: '' },
  { addr: 'A4.5', label: '' },
  { addr: 'A4.6', label: '' },
  { addr: 'A4.7', label: '' },
  { addr: 'A5.0', label: '' },
  { addr: 'A5.1', label: '' },
  { addr: 'A5.2', label: '' },
  { addr: 'A5.3', label: '' },
  { addr: 'A5.4', label: '' },
  { addr: 'A5.5', label: '' },
  { addr: 'A5.6', label: '' },
  { addr: 'A5.7', label: '' },
  { addr: 'A6.0', label: '' },
  { addr: 'A6.1', label: '' },
  { addr: 'A6.2', label: '' },
  { addr: 'A6.3', label: '' },
  { addr: 'A6.4', label: '' },
  { addr: 'A6.5', label: '' },
  { addr: 'A6.6', label: '' },
  { addr: 'A6.7', label: '' },
  { addr: 'A7.0', label: '' },
  { addr: 'A7.1', label: '' },
  { addr: 'A7.2', label: '' },
  { addr: 'A7.3', label: '' },
  { addr: 'A7.4', label: '' },
  { addr: 'A7.5', label: '' },
  { addr: 'A7.6', label: '' },
  { addr: 'A7.7', label: '' },
  { addr: 'A8.0', label: '' },
  { addr: 'A8.1', label: '' },
  { addr: 'A8.2', label: '' },
  { addr: 'A8.3', label: '' },
  { addr: 'A8.4', label: '' },
  { addr: 'A8.5', label: '' },
  { addr: 'A8.6', label: '' },
  { addr: 'A8.7', label: '' },
  { addr: 'A9.0', label: '' },
  { addr: 'A9.1', label: '' },
  { addr: 'A9.2', label: '' },
  { addr: 'A9.3', label: '' },
  { addr: 'A9.4', label: '' },
  { addr: 'A9.5', label: '' },
  { addr: 'A9.6', label: '' },
  { addr: 'A9.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A14.0', label: '' },
  { addr: 'A14.1', label: '' },
  { addr: 'A14.2', label: '' },
  { addr: 'A14.3', label: '' },
  { addr: 'A14.4', label: '' },
  { addr: 'A14.5', label: '' },
  { addr: 'A14.6', label: '' },
  { addr: 'A14.7', label: '' },
  { addr: 'A15.0', label: '' },
  { addr: 'A15.1', label: '' },
  { addr: 'A15.2', label: '' },
  { addr: 'A15.3', label: '' },
  { addr: 'A15.4', label: '' },
  { addr: 'A15.5', label: '' },
  { addr: 'A15.6', label: '' },
  { addr: 'A15.7', label: '' }
]
exports.alarms1 = [
  { class: '1', label: 'AL1', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL2', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL3', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL4', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL5', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL6', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL7', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL8', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL9', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL10', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL11', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL12', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL13', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL14', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL15', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL16', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL17', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL18', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL19', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL20', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL21', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL22', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL23', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL24', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL25', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL26', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL27', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL28', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL29', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL30', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL31', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL32', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL33', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL34', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL35', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL36', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL37', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL38', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL39', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL40', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL41', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL42', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL43', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL44', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL45', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL46', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL47', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL48', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL49', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL50', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL51', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL52', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL53', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL54', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL55', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL56', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL57', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL58', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL59', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL60', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL61', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL62', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL63', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL64', i18n: { key: '', query: {} } }
]
