exports.inputs1 = [
  { addr: 'E4.0', label: 'A' },
  { addr: 'E4.1', label: 'B' },
  { addr: 'E4.2', label: 'C' },
  { addr: 'E4.3', label: 'D' },
  { addr: 'E4.4', label: 'OK' },
  { addr: 'E4.5', label: 'S2' },
  { addr: 'E4.6', label: 'S2' },
  { addr: 'E4.7', label: 'S2' },
  { addr: 'E5.0', label: 'BA' },
  { addr: 'E5.1', label: 'BB' },
  { addr: 'E5.2', label: 'BC' },
  { addr: 'E5.3', label: 'BD' },
  { addr: 'E5.4', label: 'BSTR' },
  { addr: 'E5.5', label: 'BOK' },
  { addr: 'E5.6', label: 'BDAT' },
  { addr: 'E5.7', label: 'UC' },
  { addr: 'E6.0', label: 'EOM1' },
  { addr: 'E6.1', label: 'EZM1' },
  { addr: 'E6.2', label: 'EOM2' },
  { addr: 'E6.3', label: 'EZM2' },
  { addr: 'E6.4', label: 'EOM3' },
  { addr: 'E6.5', label: 'EZM3' },
  { addr: 'E6.6', label: 'EOM4' },
  { addr: 'E6.7', label: 'EZM4' },
  { addr: 'E7.0', label: 'AMM' },
  { addr: 'E7.1', label: '' },
  { addr: 'E7.2', label: '' },
  { addr: 'E7.3', label: 'RSI' },
  { addr: 'E7.4', label: 'DB32' },
  { addr: 'E7.5', label: 'DBHZ' },
  { addr: 'E7.6', label: '' },
  { addr: 'E7.7', label: '' },
  { addr: 'E8.0', label: 'KBA' },
  { addr: 'E8.1', label: 'KXPE' },
  { addr: 'E8.2', label: 'SA' },
  { addr: 'E8.3', label: 'IV1' },
  { addr: 'E8.4', label: 'KEZE' },
  { addr: 'E8.5', label: 'IV2' },
  { addr: 'E8.6', label: 'RTA' },
  { addr: 'E8.7', label: '' },
  { addr: 'E9.0', label: 'FE1' },
  { addr: 'E9.1', label: 'APE' },
  { addr: 'E9.2', label: 'AF9' },
  { addr: 'E9.3', label: 'ASH' },
  { addr: 'E9.4', label: 'AIV' },
  { addr: 'E9.5', label: 'S1' },
  { addr: 'E9.6', label: 'S1' },
  { addr: 'E9.7', label: 'S1' },
  { addr: 'E10.0', label: 'EZE' },
  { addr: 'E10.1', label: 'EOE' },
  { addr: 'E10.2', label: 'FBE' },
  { addr: 'E10.3', label: 'FPE' },
  { addr: 'E10.4', label: 'FDR1' },
  { addr: 'E10.5', label: 'FDL1' },
  { addr: 'E10.6', label: 'FTA1' },
  { addr: 'E10.7', label: 'FTA2' },
  { addr: 'E11.0', label: 'FLP' },
  { addr: 'E11.1', label: 'FLA' },
  { addr: 'E11.2', label: '' },
  { addr: 'E11.3', label: '' },
  { addr: 'E11.4', label: 'POD' },
  { addr: 'E11.5', label: 'RX' },
  { addr: 'E11.6', label: '' },
  { addr: 'E11.7', label: 'FAL' },
  { addr: 'E12.0', label: 'BA' },
  { addr: 'E12.1', label: 'BB' },
  { addr: 'E12.2', label: 'BC' },
  { addr: 'E12.3', label: 'BD' },
  { addr: 'E12.4', label: 'BSTR' },
  { addr: 'E12.5', label: 'BOK' },
  { addr: 'E12.6', label: 'BDAT' },
  { addr: 'E12.7', label: '' },
  { addr: 'E13.0', label: 'BA' },
  { addr: 'E13.1', label: 'BB' },
  { addr: 'E13.2', label: 'BC' },
  { addr: 'E13.3', label: 'BD' },
  { addr: 'E13.4', label: 'BSTR' },
  { addr: 'E13.5', label: 'BOK' },
  { addr: 'E13.6', label: 'BDAT' },
  { addr: 'E13.7', label: '' }
]
exports.inputs2 = [
  { addr: 'E14.0', label: 'RMV' },
  { addr: 'E14.1', label: 'RMH' },
  { addr: 'E14.2', label: 'RES' },
  { addr: 'E14.3', label: 'REH' },
  { addr: 'E14.4', label: 'RCV' },
  { addr: 'E14.5', label: 'REAV' },
  { addr: 'E14.6', label: 'REAH' },
  { addr: 'E14.7', label: 'RCH' },
  { addr: 'E15.0', label: 'ASBK' },
  { addr: 'E15.1', label: 'FSBK' },
  { addr: 'E15.2', label: 'MTC' },
  { addr: 'E15.3', label: 'ACR' },
  { addr: 'E15.4', label: 'ASDK' },
  { addr: 'E15.5', label: '' },
  { addr: 'E15.6', label: 'F24' },
  { addr: 'E15.7', label: 'TCR' },
  { addr: 'E16.0', label: 'FTXV' },
  { addr: 'E16.1', label: 'FTXH' },
  { addr: 'E16.2', label: 'EPZ' },
  { addr: 'E16.3', label: 'EM' },
  { addr: 'E16.4', label: 'ECA' },
  { addr: 'E16.5', label: 'ECB' },
  { addr: 'E16.6', label: 'AMC' },
  { addr: 'E16.7', label: 'AD' },
  { addr: 'E17.0', label: 'EXD' },
  { addr: 'E17.1', label: 'EMC' },
  { addr: 'E17.2', label: 'KEXPV' },
  { addr: 'E17.3', label: 'EXPV' },
  { addr: 'E17.4', label: 'AKKS' },
  { addr: 'E17.5', label: '' },
  { addr: 'E17.6', label: 'MNR' },
  { addr: 'E17.7', label: 'MNL' }
]
exports.outputs1 = [
  { addr: 'A4.0', label: 'KBA1' },
  { addr: 'A4.1', label: 'BLE' },
  { addr: 'A4.2', label: 'BLB' },
  { addr: 'A4.3', label: 'BRDY' },
  { addr: 'A4.4', label: 'BRST' },
  { addr: 'A4.5', label: 'KXPE' },
  { addr: 'A4.6', label: 'LA' },
  { addr: 'A4.7', label: 'LC' },
  { addr: 'A5.0', label: 'L1' },
  { addr: 'A5.1', label: 'L2' },
  { addr: 'A5.2', label: 'L3' },
  { addr: 'A5.3', label: 'L4' },
  { addr: 'A5.4', label: 'L5' },
  { addr: 'A5.5', label: 'RFE' },
  { addr: 'A5.6', label: 'RLN' },
  { addr: 'A5.7', label: 'RBE' },
  { addr: 'A6.0', label: 'DYA' },
  { addr: 'A6.1', label: 'DYB' },
  { addr: 'A6.2', label: 'DYC' },
  { addr: 'A6.3', label: 'DYD' },
  { addr: 'A6.4', label: 'AD1' },
  { addr: 'A6.5', label: 'AD2' },
  { addr: 'A6.6', label: 'AD3' },
  { addr: 'A6.7', label: 'STR' },
  { addr: 'A7.0', label: 'BLK' },
  { addr: 'A7.1', label: 'BLE' },
  { addr: 'A7.2', label: 'BLB' },
  { addr: 'A7.3', label: 'BRDY' },
  { addr: 'A7.4', label: 'BRST' },
  { addr: 'A7.5', label: '' },
  { addr: 'A7.6', label: 'TLIV' },
  { addr: 'A7.7', label: 'KEM' },
  { addr: 'A8.0', label: 'SMA1' },
  { addr: 'A8.1', label: 'SMB1' },
  { addr: 'A8.2', label: 'SMA2' },
  { addr: 'A8.3', label: 'SMB2' },
  { addr: 'A8.4', label: 'SMA3' },
  { addr: 'A8.5', label: 'SMB3' },
  { addr: 'A8.6', label: 'SMA4' },
  { addr: 'A8.7', label: 'SMB4' },
  { addr: 'A9.0', label: 'BLK' },
  { addr: 'A9.1', label: 'BLE' },
  { addr: 'A9.2', label: 'BLB' },
  { addr: 'A9.3', label: 'BRDY' },
  { addr: 'A9.4', label: 'BRST' },
  { addr: 'A9.5', label: 'KBA2' },
  { addr: 'A9.6', label: '' },
  { addr: 'A9.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A14.0', label: 'TD' },
  { addr: 'A14.1', label: 'TCR' },
  { addr: 'A14.2', label: '' },
  { addr: 'A14.3', label: '' },
  { addr: 'A14.4', label: 'KCS' },
  { addr: 'A14.5', label: 'KCV' },
  { addr: 'A14.6', label: 'KCH' },
  { addr: 'A14.7', label: 'SBK2' },
  { addr: 'A15.0', label: 'T10' },
  { addr: 'A15.1', label: 'T2' },
  { addr: 'A15.2', label: 'TRA' },
  { addr: 'A15.3', label: 'TRB' },
  { addr: 'A15.4', label: 'TCR' },
  { addr: 'A15.5', label: 'SCA' },
  { addr: 'A15.6', label: 'SCB' },
  { addr: 'A15.7', label: 'SBK1' }
]
exports.alarms1 = [
  { label: 'AL1', i18n: { key: 'al-v-to', query: {} } },
  { label: 'AL2', i18n: { key: 'al-h-to', query: {} } },
  { label: 'AL3', i18n: { key: 'al-sil-01', query: {} } },
  { label: 'AL4', i18n: { key: 'al-sil-01', query: {} } },
  { label: 'AL5', i18n: { key: 'al-sil-02', query: {} } },
  { label: 'AL6', i18n: { key: 'al-sil-03', query: {} } },
  { label: 'AL7', i18n: { key: 'al-sil-04', query: {} } },
  { label: 'AL8', i18n: { key: 'al-r-to', query: {} } },
  { label: 'AL9', i18n: { key: 'al-flap-to', query: {} } },
  { label: 'AL10', i18n: { key: 'al-v-lck-to', query: {} } },
  { label: 'AL11', i18n: { key: 'al-v-lck-to', query: {} } },
  { label: 'AL12', i18n: { key: 'al-v-lck-to', query: {} } },
  { label: 'AL13', i18n: { key: 'al-v-lck-to', query: {} } },
  { label: 'AL14', i18n: { key: 'al-sp-to', query: {} } },
  { label: 'AL15', i18n: { key: 'al-sp-to', query: {} } },
  { label: 'AL16', i18n: { key: '', query: {} } },
  { label: 'AL17', i18n: { key: 'al-th', query: { thermic: 'AMM' } } },
  { label: 'AL18', i18n: { key: 'al-th', query: { thermic: 'RTA' } } },
  { label: 'AL19', i18n: { key: 'al-th', query: { thermic: 'FE1' } } },
  { label: 'AL20', i18n: { key: 'al-th', query: { thermic: 'APE' } } },
  { label: 'AL21', i18n: { key: 'al-th', query: { thermic: 'AF9' } } },
  { label: 'AL22', i18n: { key: 'al-th', query: { thermic: 'ASH' } } },
  { label: 'AL23', i18n: { key: 'al-th', query: { thermic: 'AIV' } } },
  { label: 'AL24', i18n: { key: 'al-th', query: { thermic: 'ASBK1' } } },
  { label: 'AL25', i18n: { key: 'al-th', query: { thermic: 'MTC' } } },
  { label: 'AL26', i18n: { key: 'al-th', query: { thermic: 'ACR' } } },
  { label: 'AL27', i18n: { key: 'al-th', query: { thermic: 'ASBK2' } } },
  { label: 'AL28', i18n: { key: 'al-th', query: { thermic: 'F24' } } },
  { label: 'AL29', i18n: { key: 'al-th', query: { thermic: 'AMC' } } },
  { label: 'AL30', i18n: { key: 'al-th', query: { thermic: 'AD' } } },
  { label: 'AL31', i18n: { key: 'al-th', query: { thermic: 'AKKS' } } },
  { label: 'AL32', i18n: { key: '', query: {} } },
  { label: 'AL33', i18n: { key: 'al-v-lck-fc', query: {} } },
  { label: 'AL34', i18n: { key: 'al-sp-fc', query: {} } },
  { label: 'AL35', i18n: { key: 'al-flap-fc', query: {} } },
  { label: 'AL36', i18n: { key: 'al-sil-11', query: {} } },
  { label: 'AL37', i18n: { key: '', query: {} } },
  { label: 'AL38', i18n: { key: '', query: {} } },
  { label: 'AL39', i18n: { key: '', query: {} } },
  { label: 'AL40', i18n: { key: '', query: {} } },
  { label: 'AL41', i18n: { key: '', query: {} } },
  { label: 'AL42', i18n: { key: '', query: {} } },
  { label: 'AL43', i18n: { key: '', query: {} } },
  { label: 'AL44', i18n: { key: '', query: {} } },
  { label: 'AL45', i18n: { key: '', query: {} } },
  { label: 'AL46', i18n: { key: '', query: {} } },
  { label: 'AL47', i18n: { key: '', query: {} } },
  { label: 'AL48', i18n: { key: '', query: {} } },
  { label: 'AL49', i18n: { key: '', query: {} } },
  { label: 'AL50', i18n: { key: '', query: {} } },
  { label: 'AL51', i18n: { key: '', query: {} } },
  { label: 'AL52', i18n: { key: '', query: {} } },
  { label: 'AL53', i18n: { key: '', query: {} } },
  { label: 'AL54', i18n: { key: '', query: {} } },
  { label: 'AL55', i18n: { key: '', query: {} } },
  { label: 'AL56', i18n: { key: '', query: {} } },
  { label: 'AL57', i18n: { key: '', query: {} } },
  { label: 'AL58', i18n: { key: '', query: {} } },
  { label: 'AL59', i18n: { key: '', query: {} } },
  { label: 'AL60', i18n: { key: '', query: {} } },
  { label: 'AL61', i18n: { key: '', query: {} } },
  { label: 'AL62', i18n: { key: '', query: {} } },
  { label: 'AL63', i18n: { key: '', query: {} } },
  { label: 'AL64', i18n: { key: '', query: {} } }
]
