exports.inputs1 = [
  { addr: 'E0.0', label: 'SA1' },
  { addr: 'E0.1', label: 'SA2' },
  { addr: 'E0.2', label: 'SA3' },
  { addr: 'E0.3', label: 'SA4' },
  { addr: 'E0.4', label: 'FE' },
  { addr: 'E0.5', label: 'RSI' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' }
]
exports.inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'S2' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: '' },
  { addr: 'E101.0', label: 'UC' },
  { addr: 'E101.1', label: 'RSI' },
  { addr: 'E101.2', label: 'FE1' },
  { addr: 'E101.3', label: 'APB' },
  { addr: 'E101.4', label: 'AP' },
  { addr: 'E101.5', label: 'RTD' },
  { addr: 'E101.6', label: 'ASR' },
  { addr: 'E101.7', label: 'AMC' },
  { addr: 'E102.0', label: 'IV2' },
  { addr: 'E102.1', label: 'IV3' },
  { addr: 'E102.2', label: 'SRL' },
  { addr: 'E102.3', label: '' },
  { addr: 'E102.4', label: '' },
  { addr: 'E102.5', label: '' },
  { addr: 'E102.6', label: '' },
  { addr: 'E102.7', label: '' },
  { addr: 'E103.0', label: 'ECA' },
  { addr: 'E103.1', label: 'ECB' },
  { addr: 'E103.2', label: 'EZE' },
  { addr: 'E103.3', label: 'EOE' },
  { addr: 'E103.4', label: 'EBZE' },
  { addr: 'E103.5', label: 'EBOE' },
  { addr: 'E103.6', label: 'FREL' },
  { addr: 'E103.7', label: 'FRER' },
  { addr: 'E104.0', label: 'FBE' },
  { addr: 'E104.1', label: 'FBBE' },
  { addr: 'E104.2', label: 'FPE' },
  { addr: 'E104.3', label: 'FDR1' },
  { addr: 'E104.4', label: 'FDL1' },
  { addr: 'E104.5', label: 'FDR2' },
  { addr: 'E104.6', label: 'FDL2' },
  { addr: 'E104.7', label: 'FTA1' },
  { addr: 'E105.0', label: 'FTA2' },
  { addr: 'E105.1', label: '' },
  { addr: 'E105.2', label: 'FLP' },
  { addr: 'E105.3', label: 'FLA' },
  { addr: 'E105.4', label: 'EXDE' },
  { addr: 'E105.5', label: 'EXHE' },
  { addr: 'E105.6', label: '' },
  { addr: 'E105.7', label: '' },
  { addr: 'E106.0', label: 'EZA' },
  { addr: 'E106.1', label: 'EOA' },
  { addr: 'E106.2', label: 'EBZA' },
  { addr: 'E106.3', label: 'EBOA' },
  { addr: 'E106.4', label: 'FBA' },
  { addr: 'E106.5', label: 'FBBA' },
  { addr: 'E106.6', label: 'FPA' },
  { addr: 'E106.7', label: '' },
  { addr: 'E107.0', label: 'EXDA' },
  { addr: 'E107.1', label: 'EXHA' },
  { addr: 'E107.2', label: 'DB32' },
  { addr: 'E107.3', label: 'DBHZ' },
  { addr: 'E107.4', label: '' },
  { addr: 'E107.5', label: '' },
  { addr: 'E107.6', label: '' },
  { addr: 'E107.7', label: '' }
]
exports.inputs3 = [
  { addr: 'E110.0', label: 'RSI' },
  { addr: 'E110.1', label: 'FE1' },
  { addr: 'E110.2', label: 'IV1' },
  { addr: 'E110.3', label: 'RTA' },
  { addr: 'E110.4', label: 'ASBK' },
  { addr: 'E110.5', label: 'FSBK' },
  { addr: 'E110.6', label: 'SA' },
  { addr: 'E110.7', label: 'UC' },
  { addr: 'E111.0', label: 'A' },
  { addr: 'E111.1', label: 'B' },
  { addr: 'E111.2', label: 'C' },
  { addr: 'E111.3', label: 'D' },
  { addr: 'E111.4', label: 'OK' },
  { addr: 'E111.5', label: 'S2' },
  { addr: 'E111.6', label: 'S2' },
  { addr: 'E111.7', label: 'S2' },
  { addr: 'E112.0', label: 'ASH' },
  { addr: 'E112.1', label: 'AMM' },
  { addr: 'E112.2', label: 'FE1' },
  { addr: 'E112.3', label: '' },
  { addr: 'E112.4', label: '' },
  { addr: 'E112.5', label: '' },
  { addr: 'E112.6', label: '' },
  { addr: 'E112.7', label: '' },
  { addr: 'E113.0', label: 'EOM' },
  { addr: 'E113.1', label: 'EZM' },
  { addr: 'E113.2', label: 'EMC' },
  { addr: 'E113.3', label: 'EXV' },
  { addr: 'E113.4', label: '' },
  { addr: 'E113.5', label: '' },
  { addr: 'E113.6', label: '' },
  { addr: 'E113.7', label: '' },
  { addr: 'E114.0', label: 'A' },
  { addr: 'E114.1', label: 'B' },
  { addr: 'E114.2', label: 'C' },
  { addr: 'E114.3', label: 'D' },
  { addr: 'E114.4', label: 'OK' },
  { addr: 'E114.5', label: 'S2' },
  { addr: 'E114.6', label: 'S2' },
  { addr: 'E114.7', label: 'S2' },
  { addr: 'E115.0', label: 'UC' },
  { addr: 'E115.1', label: 'FE2' },
  { addr: 'E115.2', label: 'IV2' },
  { addr: 'E115.3', label: 'RSI' },
  { addr: 'E115.4', label: 'AH' },
  { addr: 'E115.5', label: 'MTC' },
  { addr: 'E115.6', label: 'ATF' },
  { addr: 'E115.7', label: 'SRL' },
  { addr: 'E116.0', label: 'RMV' },
  { addr: 'E116.1', label: 'RMH' },
  { addr: 'E116.2', label: 'RES' },
  { addr: 'E116.3', label: 'REH' },
  { addr: 'E116.4', label: 'RCV' },
  { addr: 'E116.5', label: 'REAV' },
  { addr: 'E116.6', label: 'REAH' },
  { addr: 'E116.7', label: 'RCH' },
  { addr: 'E117.0', label: 'DB32' },
  { addr: 'E117.1', label: 'DBHZ' },
  { addr: 'E117.2', label: 'EM' },
  { addr: 'E117.3', label: 'FTXV' },
  { addr: 'E117.4', label: 'FTXH' },
  { addr: 'E117.5', label: 'FTAC' },
  { addr: 'E117.6', label: '' },
  { addr: 'E117.7', label: '' }
]
exports.inputs4 = [
  { addr: 'E200.0', label: 'A' },
  { addr: 'E200.1', label: 'B' },
  { addr: 'E200.2', label: 'C' },
  { addr: 'E200.3', label: 'D' },
  { addr: 'E200.4', label: 'S2' },
  { addr: 'E200.5', label: 'S2' },
  { addr: 'E200.6', label: 'S2' },
  { addr: 'E200.7', label: '' },
  { addr: 'E201.0', label: 'UC' },
  { addr: 'E201.1', label: 'RSI' },
  { addr: 'E201.2', label: 'FE1' },
  { addr: 'E201.3', label: 'APB' },
  { addr: 'E201.4', label: 'AP' },
  { addr: 'E201.5', label: 'RTD' },
  { addr: 'E201.6', label: 'ASR' },
  { addr: 'E201.7', label: 'AMC' },
  { addr: 'E202.0', label: 'IV2' },
  { addr: 'E202.1', label: 'IV3' },
  { addr: 'E202.2', label: 'SRL' },
  { addr: 'E202.3', label: '' },
  { addr: 'E202.4', label: '' },
  { addr: 'E202.5', label: '' },
  { addr: 'E202.6', label: '' },
  { addr: 'E202.7', label: '' },
  { addr: 'E203.0', label: 'ECA' },
  { addr: 'E203.1', label: 'ECB' },
  { addr: 'E203.2', label: 'EZE' },
  { addr: 'E203.3', label: 'EOE' },
  { addr: 'E203.4', label: 'EBZE' },
  { addr: 'E203.5', label: 'EBOE' },
  { addr: 'E203.6', label: 'FREL' },
  { addr: 'E203.7', label: 'FRER' },
  { addr: 'E204.0', label: 'FBE' },
  { addr: 'E204.1', label: 'FBBE' },
  { addr: 'E204.2', label: 'FPE' },
  { addr: 'E204.3', label: 'FDR1' },
  { addr: 'E204.4', label: 'FDL1' },
  { addr: 'E204.5', label: 'FDR2' },
  { addr: 'E204.6', label: 'FDL2' },
  { addr: 'E204.7', label: 'FTA1' },
  { addr: 'E205.0', label: 'FTA2' },
  { addr: 'E205.1', label: '' },
  { addr: 'E205.2', label: 'FLP' },
  { addr: 'E205.3', label: 'FLA' },
  { addr: 'E205.4', label: 'EXDE' },
  { addr: 'E205.5', label: 'EXHE' },
  { addr: 'E205.6', label: '' },
  { addr: 'E205.7', label: '' },
  { addr: 'E206.0', label: 'EZA' },
  { addr: 'E206.1', label: 'EOA' },
  { addr: 'E206.2', label: 'EBZA' },
  { addr: 'E206.3', label: 'EBOA' },
  { addr: 'E206.4', label: 'FBA' },
  { addr: 'E206.5', label: 'FBBA' },
  { addr: 'E206.6', label: 'FPA' },
  { addr: 'E206.7', label: '' },
  { addr: 'E207.0', label: 'EXDA' },
  { addr: 'E207.1', label: 'EXHA' },
  { addr: 'E207.2', label: 'DB32' },
  { addr: 'E207.3', label: 'DBHZ' },
  { addr: 'E207.4', label: '' },
  { addr: 'E207.5', label: '' },
  { addr: 'E207.6', label: '' },
  { addr: 'E207.7', label: '' }
]
exports.inputs5 = [
  { addr: 'E210.0', label: 'RSI' },
  { addr: 'E210.1', label: 'FE1' },
  { addr: 'E210.2', label: 'IV1' },
  { addr: 'E210.3', label: 'RTA' },
  { addr: 'E210.4', label: 'ASBK' },
  { addr: 'E210.5', label: 'FSBK' },
  { addr: 'E210.6', label: 'SA' },
  { addr: 'E210.7', label: 'UC' },
  { addr: 'E211.0', label: 'A' },
  { addr: 'E211.1', label: 'B' },
  { addr: 'E211.2', label: 'C' },
  { addr: 'E211.3', label: 'D' },
  { addr: 'E211.4', label: 'OK' },
  { addr: 'E211.5', label: 'S2' },
  { addr: 'E211.6', label: 'S2' },
  { addr: 'E211.7', label: 'S2' },
  { addr: 'E212.0', label: 'ASH' },
  { addr: 'E212.1', label: 'AMM' },
  { addr: 'E212.2', label: 'FE1' },
  { addr: 'E212.3', label: '' },
  { addr: 'E212.4', label: '' },
  { addr: 'E212.5', label: '' },
  { addr: 'E212.6', label: '' },
  { addr: 'E212.7', label: '' },
  { addr: 'E213.0', label: 'EOM' },
  { addr: 'E213.1', label: 'EZM' },
  { addr: 'E213.2', label: 'EMC' },
  { addr: 'E213.3', label: 'EXV' },
  { addr: 'E213.4', label: '' },
  { addr: 'E213.5', label: '' },
  { addr: 'E213.6', label: '' },
  { addr: 'E213.7', label: '' },
  { addr: 'E214.0', label: 'A' },
  { addr: 'E214.1', label: 'B' },
  { addr: 'E214.2', label: 'C' },
  { addr: 'E214.3', label: 'D' },
  { addr: 'E214.4', label: 'OK' },
  { addr: 'E214.5', label: 'S2' },
  { addr: 'E214.6', label: 'S2' },
  { addr: 'E214.7', label: 'S2' },
  { addr: 'E215.0', label: 'UC' },
  { addr: 'E215.1', label: 'FE2' },
  { addr: 'E215.2', label: 'IV2' },
  { addr: 'E215.3', label: 'RSI' },
  { addr: 'E215.4', label: 'AH' },
  { addr: 'E215.5', label: 'MTC' },
  { addr: 'E215.6', label: 'ATF' },
  { addr: 'E215.7', label: 'SRL' },
  { addr: 'E216.0', label: 'RMV' },
  { addr: 'E216.1', label: 'RMH' },
  { addr: 'E216.2', label: 'RES' },
  { addr: 'E216.3', label: 'REH' },
  { addr: 'E216.4', label: 'RCV' },
  { addr: 'E216.5', label: 'REAV' },
  { addr: 'E216.6', label: 'REAH' },
  { addr: 'E216.7', label: 'RCH' },
  { addr: 'E217.0', label: 'DB32' },
  { addr: 'E217.1', label: 'DBHZ' },
  { addr: 'E217.2', label: 'EM' },
  { addr: 'E217.3', label: 'FTXV' },
  { addr: 'E217.4', label: 'FTXH' },
  { addr: 'E217.5', label: 'FTAC' },
  { addr: 'E217.6', label: '' },
  { addr: 'E217.7', label: '' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'LS1' },
  { addr: 'A0.1', label: 'LS2' },
  { addr: 'A0.2', label: 'LS3' },
  { addr: 'A0.3', label: 'LS4' },
  { addr: 'A0.4', label: 'LA' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A100.0', label: 'DYA' },
  { addr: 'A100.1', label: 'DYB' },
  { addr: 'A100.2', label: 'DYC' },
  { addr: 'A100.3', label: 'DYD' },
  { addr: 'A100.4', label: 'AD1' },
  { addr: 'A100.5', label: 'AD2' },
  { addr: 'A100.6', label: 'AD3' },
  { addr: 'A100.7', label: 'STR' },
  { addr: 'A101.0', label: 'LC' },
  { addr: 'A101.1', label: 'LA' },
  { addr: 'A101.2', label: 'KBA2' },
  { addr: 'A101.3', label: 'KBA3' },
  { addr: 'A101.4', label: 'TRBE' },
  { addr: 'A101.5', label: 'TRBA' },
  { addr: 'A101.6', label: 'SCA' },
  { addr: 'A101.7', label: 'SCB' },
  { addr: 'A102.0', label: 'SPE' },
  { addr: 'A102.1', label: 'SPBE' },
  { addr: 'A102.2', label: 'SPA' },
  { addr: 'A102.3', label: 'SPBA' },
  { addr: 'A102.4', label: '' },
  { addr: 'A102.5', label: '' },
  { addr: 'A102.6', label: '' },
  { addr: 'A102.7', label: '' },
  { addr: 'A103.0', label: 'SOE' },
  { addr: 'A103.1', label: 'SZE' },
  { addr: 'A103.2', label: 'SOA' },
  { addr: 'A103.3', label: 'SZA' },
  { addr: 'A103.4', label: 'SBOE' },
  { addr: 'A103.5', label: 'SBZE' },
  { addr: 'A103.6', label: 'SBOA' },
  { addr: 'A103.7', label: 'SBZA' },
  { addr: 'A104.0', label: '' },
  { addr: 'A104.1', label: 'RFE' },
  { addr: 'A104.2', label: 'RFA' },
  { addr: 'A104.3', label: 'L1' },
  { addr: 'A104.4', label: 'L2' },
  { addr: 'A104.5', label: 'L3' },
  { addr: 'A104.6', label: 'L4' },
  { addr: 'A104.7', label: 'L5' },
  { addr: 'A105.0', label: '' },
  { addr: 'A105.1', label: '' },
  { addr: 'A105.2', label: '' },
  { addr: 'A105.3', label: '' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: '' }
]
exports.outputs3 = [
  { addr: 'A110.0', label: 'LC' },
  { addr: 'A110.1', label: 'LA' },
  { addr: 'A110.2', label: 'KBA1' },
  { addr: 'A110.3', label: 'SBK1' },
  { addr: 'A110.4', label: 'SBK2' },
  { addr: 'A110.5', label: '' },
  { addr: 'A110.6', label: '' },
  { addr: 'A110.7', label: '' },
  { addr: 'A111.0', label: 'DYA' },
  { addr: 'A111.1', label: 'DYB' },
  { addr: 'A111.2', label: 'DYC' },
  { addr: 'A111.3', label: 'DYD' },
  { addr: 'A111.4', label: 'AD1' },
  { addr: 'A111.5', label: 'AD2' },
  { addr: 'A111.6', label: 'AD3' },
  { addr: 'A111.7', label: 'STR' },
  { addr: 'A112.0', label: 'SMA' },
  { addr: 'A112.1', label: 'SMB' },
  { addr: 'A112.2', label: 'LA' },
  { addr: 'A112.3', label: '' },
  { addr: 'A112.4', label: '' },
  { addr: 'A112.5', label: '' },
  { addr: 'A112.6', label: '' },
  { addr: 'A112.7', label: '' },
  { addr: 'A113.0', label: '' },
  { addr: 'A113.1', label: '' },
  { addr: 'A113.2', label: '' },
  { addr: 'A113.3', label: '' },
  { addr: 'A113.4', label: '' },
  { addr: 'A113.5', label: '' },
  { addr: 'A113.6', label: '' },
  { addr: 'A113.7', label: '' },
  { addr: 'A114.0', label: 'DYA' },
  { addr: 'A114.1', label: 'DYB' },
  { addr: 'A114.2', label: 'DYC' },
  { addr: 'A114.3', label: 'DYD' },
  { addr: 'A114.4', label: 'AD1' },
  { addr: 'A114.5', label: 'AD2' },
  { addr: 'A114.6', label: 'AD3' },
  { addr: 'A114.7', label: 'STR' },
  { addr: 'A115.0', label: 'LC' },
  { addr: 'A115.1', label: 'LA' },
  { addr: 'A115.2', label: 'KBA2' },
  { addr: 'A115.3', label: 'T101' },
  { addr: 'A115.4', label: 'T102' },
  { addr: 'A115.5', label: 'T2' },
  { addr: 'A115.6', label: 'TRA' },
  { addr: 'A115.7', label: 'TRB' },
  { addr: 'A116.0', label: 'T10F' },
  { addr: 'A116.1', label: 'KCS' },
  { addr: 'A116.2', label: 'KCV' },
  { addr: 'A116.3', label: 'KCH' },
  { addr: 'A116.4', label: '' },
  { addr: 'A116.5', label: '' },
  { addr: 'A116.6', label: '' },
  { addr: 'A116.7', label: '' },
  { addr: 'A117.0', label: '' },
  { addr: 'A117.1', label: '' },
  { addr: 'A117.2', label: '' },
  { addr: 'A117.3', label: '' },
  { addr: 'A117.4', label: '' },
  { addr: 'A117.5', label: '' },
  { addr: 'A117.6', label: '' },
  { addr: 'A117.7', label: '' }
]
exports.outputs4 = [
  { addr: 'A200.0', label: 'DYA' },
  { addr: 'A200.1', label: 'DYB' },
  { addr: 'A200.2', label: 'DYC' },
  { addr: 'A200.3', label: 'DYD' },
  { addr: 'A200.4', label: 'AD1' },
  { addr: 'A200.5', label: 'AD2' },
  { addr: 'A200.6', label: 'AD3' },
  { addr: 'A200.7', label: 'STR' },
  { addr: 'A201.0', label: 'LC' },
  { addr: 'A201.1', label: 'LA' },
  { addr: 'A201.2', label: 'KBA2' },
  { addr: 'A201.3', label: 'KBA3' },
  { addr: 'A201.4', label: 'TRBE' },
  { addr: 'A201.5', label: 'TRBA' },
  { addr: 'A201.6', label: 'SCA' },
  { addr: 'A201.7', label: 'SCB' },
  { addr: 'A202.0', label: 'SPE' },
  { addr: 'A202.1', label: 'SPBE' },
  { addr: 'A202.2', label: 'SPA' },
  { addr: 'A202.3', label: 'SPBA' },
  { addr: 'A202.4', label: '' },
  { addr: 'A202.5', label: '' },
  { addr: 'A202.6', label: '' },
  { addr: 'A202.7', label: '' },
  { addr: 'A203.0', label: 'SOE' },
  { addr: 'A203.1', label: 'SZE' },
  { addr: 'A203.2', label: 'SOA' },
  { addr: 'A203.3', label: 'SZA' },
  { addr: 'A203.4', label: 'SBOE' },
  { addr: 'A203.5', label: 'SBZE' },
  { addr: 'A203.6', label: 'SBOA' },
  { addr: 'A203.7', label: 'SBZA' },
  { addr: 'A204.0', label: '' },
  { addr: 'A204.1', label: 'RFE' },
  { addr: 'A204.2', label: 'RFA' },
  { addr: 'A204.3', label: 'L1' },
  { addr: 'A204.4', label: 'L2' },
  { addr: 'A204.5', label: 'L3' },
  { addr: 'A204.6', label: 'L4' },
  { addr: 'A204.7', label: 'L5' },
  { addr: 'A205.0', label: '' },
  { addr: 'A205.1', label: '' },
  { addr: 'A205.2', label: '' },
  { addr: 'A205.3', label: '' },
  { addr: 'A205.4', label: '' },
  { addr: 'A205.5', label: '' },
  { addr: 'A205.6', label: '' },
  { addr: 'A205.7', label: '' }
]
exports.outputs5 = [
  { addr: 'A210.0', label: 'LC' },
  { addr: 'A210.1', label: 'LA' },
  { addr: 'A210.2', label: 'KBA1' },
  { addr: 'A210.3', label: 'SBK1' },
  { addr: 'A210.4', label: 'SBK2' },
  { addr: 'A210.5', label: '' },
  { addr: 'A210.6', label: '' },
  { addr: 'A210.7', label: '' },
  { addr: 'A211.0', label: 'DYA' },
  { addr: 'A211.1', label: 'DYB' },
  { addr: 'A211.2', label: 'DYC' },
  { addr: 'A211.3', label: 'DYD' },
  { addr: 'A211.4', label: 'AD1' },
  { addr: 'A211.5', label: 'AD2' },
  { addr: 'A211.6', label: 'AD3' },
  { addr: 'A211.7', label: 'STR' },
  { addr: 'A212.0', label: 'SMA' },
  { addr: 'A212.1', label: 'SMB' },
  { addr: 'A212.2', label: 'LA' },
  { addr: 'A212.3', label: '' },
  { addr: 'A212.4', label: '' },
  { addr: 'A212.5', label: '' },
  { addr: 'A212.6', label: '' },
  { addr: 'A212.7', label: '' },
  { addr: 'A213.0', label: '' },
  { addr: 'A213.1', label: '' },
  { addr: 'A213.2', label: '' },
  { addr: 'A213.3', label: '' },
  { addr: 'A213.4', label: '' },
  { addr: 'A213.5', label: '' },
  { addr: 'A213.6', label: '' },
  { addr: 'A213.7', label: '' },
  { addr: 'A214.0', label: 'DYA' },
  { addr: 'A214.1', label: 'DYB' },
  { addr: 'A214.2', label: 'DYC' },
  { addr: 'A214.3', label: 'DYD' },
  { addr: 'A214.4', label: 'AD1' },
  { addr: 'A214.5', label: 'AD2' },
  { addr: 'A214.6', label: 'AD3' },
  { addr: 'A214.7', label: 'STR' },
  { addr: 'A215.0', label: 'LC' },
  { addr: 'A215.1', label: 'LA' },
  { addr: 'A215.2', label: 'KBA2' },
  { addr: 'A215.3', label: 'T101' },
  { addr: 'A215.4', label: 'T102' },
  { addr: 'A215.5', label: 'T2' },
  { addr: 'A215.6', label: 'TRA' },
  { addr: 'A215.7', label: 'TRB' },
  { addr: 'A216.0', label: 'T10F' },
  { addr: 'A216.1', label: 'KCS' },
  { addr: 'A216.2', label: 'KCV' },
  { addr: 'A216.3', label: 'KCH' },
  { addr: 'A216.4', label: '' },
  { addr: 'A216.5', label: '' },
  { addr: 'A216.6', label: '' },
  { addr: 'A216.7', label: '' },
  { addr: 'A217.0', label: '' },
  { addr: 'A217.1', label: '' },
  { addr: 'A217.2', label: '' },
  { addr: 'A217.3', label: '' },
  { addr: 'A217.4', label: '' },
  { addr: 'A217.5', label: '' },
  { addr: 'A217.6', label: '' },
  { addr: 'A217.7', label: '' }
]

exports.EL = [
  { label: 'AL1', i18n: { key: 'al-sil-01', query: {} } },
  { label: 'AL2', i18n: { key: 'al-sil-02', query: {} } },
  { label: 'AL3', i18n: { key: 'al-sil-03', query: {} } },
  { label: 'AL4', i18n: { key: 'al-sil-04', query: {} } },
  { label: 'AL5', i18n: { key: 'al-sil-05', query: {} } },
  { label: 'AL6', i18n: { key: 'al-sil-06', query: {} } },
  { label: 'AL7', i18n: { key: 'al-sil-07', query: {} } },
  { label: 'AL8', i18n: { key: 'al-sil-08', query: {} } },
  { label: 'AL9', i18n: { key: 'al-sil-09', query: {} } },
  { label: 'AL10', i18n: { key: 'al-sil-10', query: {} } },
  { label: 'AL11', i18n: { key: 'al-sil-11', query: {} } },
  { label: 'AL12', i18n: { key: 'al-sil-12', query: {} } },
  { label: 'AL13', i18n: { key: 'al-sil-13', query: {} } },
  { label: 'AL14', i18n: { key: 'al-sil-14', query: {} } },
  { label: 'AL15', i18n: { key: 'al-sil-15', query: {} } },
  { label: 'AL16', i18n: { key: 'al-sil-16', query: {} } },
  { label: 'AL17', i18n: { key: 'al-v-to', query: {} } },
  { label: 'AL18', i18n: { key: 'al-v-fdbk', query: {} } },
  { label: 'AL19', i18n: { key: 'al-lv', query: {} } },
  { label: 'AL20', i18n: { key: 'al-lv-diff', query: {} } },
  { label: 'AL21', i18n: { key: 'al-v-lck-to', query: {} } },
  { label: 'AL22', i18n: { key: 'al-v-lck-fc', query: {} } },
  { label: 'AL23', i18n: { key: 'al-h-to', query: {} } },
  { label: 'AL24', i18n: { key: 'al-lh', query: {} } },
  { label: 'AL25', i18n: { key: 'al-lh-diff', query: {} } },
  { label: 'AL26', i18n: { key: '', query: {} } },
  { label: 'AL27', i18n: { key: '', query: {} } },
  { label: 'AL28', i18n: { key: '', query: {} } },
  { label: 'AL29', i18n: { key: '', query: {} } },
  { label: 'AL30', i18n: { key: '', query: {} } },
  { label: 'AL31', i18n: { key: '', query: {} } },
  { label: 'AL32', i18n: { key: '', query: {} } },
  { label: 'AL33', i18n: { key: '', query: {} } },
  { label: 'AL34', i18n: { key: '', query: {} } },
  { label: 'AL35', i18n: { key: '', query: {} } },
  { label: 'AL36', i18n: { key: '', query: {} } },
  { label: 'AL37', i18n: { key: '', query: {} } },
  { label: 'AL38', i18n: { key: '', query: {} } },
  { label: 'AL39', i18n: { key: '', query: {} } },
  { label: 'AL40', i18n: { key: '', query: {} } },
  { label: 'AL41', i18n: { key: '', query: {} } },
  { label: 'AL42', i18n: { key: '', query: {} } },
  { label: 'AL43', i18n: { key: '', query: {} } },
  { label: 'AL44', i18n: { key: '', query: {} } },
  { label: 'AL45', i18n: { key: '', query: {} } },
  { label: 'AL46', i18n: { key: '', query: {} } },
  { label: 'AL47', i18n: { key: '', query: {} } },
  { label: 'AL48', i18n: { key: '', query: {} } },
  {
    label: 'AL49',
    i18n: { key: 'al-th', query: { thermic: 'FE' } }
  },
  { label: 'AL50', i18n: { key: '', query: {} } },
  {
    label: 'AL51',
    i18n: { key: 'al-th', query: { thermic: 'IV1' } }
  },
  {
    label: 'AL52',
    i18n: { key: 'al-th', query: { thermic: 'RTA' } }
  },
  {
    label: 'AL53',
    i18n: { key: 'al-th', query: { thermic: 'ASBK' } }
  },
  {
    label: 'AL54',
    i18n: { key: 'al-th', query: { thermic: 'ASH' } }
  },
  {
    label: 'AL55',
    i18n: { key: 'al-th', query: { thermic: 'AMM' } }
  },
  {
    label: 'AL56',
    i18n: { key: 'al-th', query: { thermic: 'FE' } }
  },
  {
    label: 'AL57',
    i18n: { key: 'al-th', query: { thermic: 'FE' } }
  },
  {
    label: 'AL58',
    i18n: { key: 'al-th', query: { thermic: 'IV2' } }
  },
  {
    label: 'AL59',
    i18n: { key: 'al-th', query: { thermic: 'AH' } }
  },
  {
    label: 'AL60',
    i18n: { key: 'al-th', query: { thermic: 'MTC' } }
  },
  {
    label: 'AL61',
    i18n: { key: 'al-th', query: { thermic: 'ATF' } }
  },
  { label: 'AL62', i18n: { key: '', query: {} } },
  { label: 'AL63', i18n: { key: '', query: {} } },
  { label: 'AL64', i18n: { key: '', query: {} } }
]

exports.E = [
  { label: 'AL1', i18n: { key: '', query: {} } },
  { label: 'AL2', i18n: { key: '', query: {} } },
  { label: 'AL3', i18n: { key: '', query: {} } },
  { label: 'AL4', i18n: { key: '', query: {} } },
  { label: 'AL5', i18n: { key: '', query: {} } },
  { label: 'AL6', i18n: { key: '', query: {} } },
  { label: 'AL7', i18n: { key: '', query: {} } },
  { label: 'AL8', i18n: { key: '', query: {} } },
  { label: 'AL9', i18n: { key: '', query: {} } },
  { label: 'AL10', i18n: { key: '', query: {} } },
  { label: 'AL11', i18n: { key: '', query: {} } },
  { label: 'AL12', i18n: { key: '', query: {} } },
  { label: 'AL13', i18n: { key: '', query: {} } },
  { label: 'AL14', i18n: { key: '', query: {} } },
  { label: 'AL15', i18n: { key: '', query: {} } },
  { label: 'AL16', i18n: { key: '', query: {} } },
  { label: 'AL17', i18n: { key: 'al-flap-to', query: {} } },
  { label: 'AL18', i18n: { key: 'al-flap-fc', query: {} } },
  { label: 'AL19', i18n: { key: 'al-spe-to', query: {} } },
  { label: 'AL20', i18n: { key: 'al-spe-fc', query: {} } },
  { label: 'AL21', i18n: { key: 'al-spbe-to', query: {} } },
  { label: 'AL22', i18n: { key: 'al-spbe-fc', query: {} } },
  { label: 'AL23', i18n: { key: 'al-r-to', query: {} } },
  { label: 'AL24', i18n: { key: 'al-enr', query: {} } },
  { label: 'AL25', i18n: { key: '', query: {} } },
  { label: 'AL26', i18n: { key: '', query: {} } },
  { label: 'AL27', i18n: { key: '', query: {} } },
  { label: 'AL28', i18n: { key: '', query: {} } },
  { label: 'AL29', i18n: { key: '', query: {} } },
  { label: 'AL30', i18n: { key: '', query: {} } },
  { label: 'AL31', i18n: { key: '', query: {} } },
  { label: 'AL32', i18n: { key: '', query: {} } },
  { label: 'AL33', i18n: { key: '', query: {} } },
  { label: 'AL34', i18n: { key: '', query: {} } },
  { label: 'AL35', i18n: { key: '', query: {} } },
  { label: 'AL36', i18n: { key: '', query: {} } },
  { label: 'AL37', i18n: { key: '', query: {} } },
  { label: 'AL38', i18n: { key: '', query: {} } },
  { label: 'AL39', i18n: { key: '', query: {} } },
  { label: 'AL40', i18n: { key: '', query: {} } },
  { label: 'AL41', i18n: { key: '', query: {} } },
  { label: 'AL42', i18n: { key: '', query: {} } },
  { label: 'AL43', i18n: { key: '', query: {} } },
  { label: 'AL44', i18n: { key: '', query: {} } },
  { label: 'AL45', i18n: { key: '', query: {} } },
  { label: 'AL46', i18n: { key: '', query: {} } },
  { label: 'AL47', i18n: { key: '', query: {} } },
  { label: 'AL48', i18n: { key: '', query: {} } },
  {
    label: 'AL49',
    i18n: { key: 'al-th', query: { thermic: 'FE' } }
  },
  {
    label: 'AL50',
    i18n: { key: 'al-th', query: { thermic: 'APB' } }
  },
  {
    label: 'AL51',
    i18n: { key: 'al-th', query: { thermic: 'AP' } }
  },
  {
    label: 'AL52',
    i18n: { key: 'al-th', query: { thermic: 'RTD' } }
  },
  {
    label: 'AL53',
    i18n: { key: 'al-th', query: { thermic: 'ASR' } }
  },
  {
    label: 'AL54',
    i18n: { key: 'al-th', query: { thermic: 'AMC' } }
  },
  {
    label: 'AL55',
    i18n: { key: 'al-th', query: { thermic: 'IV2' } }
  },
  {
    label: 'AL56',
    i18n: { key: 'al-th', query: { thermic: 'IV3' } }
  },
  { label: 'AL57', i18n: { key: '', query: {} } },
  { label: 'AL58', i18n: { key: '', query: {} } },
  { label: 'AL59', i18n: { key: '', query: {} } },
  { label: 'AL60', i18n: { key: '', query: {} } },
  { label: 'AL61', i18n: { key: '', query: {} } },
  { label: 'AL62', i18n: { key: '', query: {} } },
  { label: 'AL63', i18n: { key: '', query: {} } },
  { label: 'AL64', i18n: { key: '', query: {} } }
]

exports.U = [
  { label: 'AL1', i18n: { key: '', query: {} } },
  { label: 'AL2', i18n: { key: '', query: {} } },
  { label: 'AL3', i18n: { key: '', query: {} } },
  { label: 'AL4', i18n: { key: '', query: {} } },
  { label: 'AL5', i18n: { key: '', query: {} } },
  { label: 'AL6', i18n: { key: '', query: {} } },
  { label: 'AL7', i18n: { key: '', query: {} } },
  { label: 'AL8', i18n: { key: '', query: {} } },
  { label: 'AL9', i18n: { key: '', query: {} } },
  { label: 'AL10', i18n: { key: '', query: {} } },
  { label: 'AL11', i18n: { key: '', query: {} } },
  { label: 'AL12', i18n: { key: '', query: {} } },
  { label: 'AL13', i18n: { key: '', query: {} } },
  { label: 'AL14', i18n: { key: '', query: {} } },
  { label: 'AL15', i18n: { key: '', query: {} } },
  { label: 'AL16', i18n: { key: '', query: {} } },
  { label: 'AL17', i18n: { key: '', query: {} } },
  { label: 'AL18', i18n: { key: '', query: {} } },
  { label: 'AL19', i18n: { key: 'al-spa-to', query: {} } },
  { label: 'AL20', i18n: { key: 'al-spa-fc', query: {} } },
  { label: 'AL21', i18n: { key: 'al-spba-to', query: {} } },
  { label: 'AL22', i18n: { key: 'al-spba-fc', query: {} } },
  { label: 'AL23', i18n: { key: 'al-r-to', query: {} } },
  { label: 'AL24', i18n: { key: 'al-enr', query: {} } },
  { label: 'AL25', i18n: { key: '', query: {} } },
  { label: 'AL26', i18n: { key: '', query: {} } },
  { label: 'AL27', i18n: { key: '', query: {} } },
  { label: 'AL28', i18n: { key: '', query: {} } },
  { label: 'AL29', i18n: { key: '', query: {} } },
  { label: 'AL30', i18n: { key: '', query: {} } },
  { label: 'AL31', i18n: { key: '', query: {} } },
  { label: 'AL32', i18n: { key: '', query: {} } },
  { label: 'AL33', i18n: { key: '', query: {} } },
  { label: 'AL34', i18n: { key: '', query: {} } },
  { label: 'AL35', i18n: { key: '', query: {} } },
  { label: 'AL36', i18n: { key: '', query: {} } },
  { label: 'AL37', i18n: { key: '', query: {} } },
  { label: 'AL38', i18n: { key: '', query: {} } },
  { label: 'AL39', i18n: { key: '', query: {} } },
  { label: 'AL40', i18n: { key: '', query: {} } },
  { label: 'AL41', i18n: { key: '', query: {} } },
  { label: 'AL42', i18n: { key: '', query: {} } },
  { label: 'AL43', i18n: { key: '', query: {} } },
  { label: 'AL44', i18n: { key: '', query: {} } },
  { label: 'AL45', i18n: { key: '', query: {} } },
  { label: 'AL46', i18n: { key: '', query: {} } },
  { label: 'AL47', i18n: { key: '', query: {} } },
  { label: 'AL48', i18n: { key: '', query: {} } },
  {
    label: 'AL49',
    i18n: { key: 'al-th', query: { thermic: 'FE' } }
  },
  {
    label: 'AL50',
    i18n: { key: 'al-th', query: { thermic: 'APB' } }
  },
  {
    label: 'AL51',
    i18n: { key: 'al-th', query: { thermic: 'AP' } }
  },
  {
    label: 'AL52',
    i18n: { key: 'al-th', query: { thermic: 'RTD' } }
  },
  {
    label: 'AL53',
    i18n: { key: 'al-th', query: { thermic: 'ASR' } }
  },
  {
    label: 'AL54',
    i18n: { key: 'al-th', query: { thermic: 'AMC' } }
  },
  {
    label: 'AL55',
    i18n: { key: 'al-th', query: { thermic: 'IV2' } }
  },
  {
    label: 'AL56',
    i18n: { key: 'al-th', query: { thermic: 'IV3' } }
  },
  { label: 'AL57', i18n: { key: '', query: {} } },
  { label: 'AL58', i18n: { key: '', query: {} } },
  { label: 'AL59', i18n: { key: '', query: {} } },
  { label: 'AL60', i18n: { key: '', query: {} } },
  { label: 'AL61', i18n: { key: '', query: {} } },
  { label: 'AL62', i18n: { key: '', query: {} } },
  { label: 'AL63', i18n: { key: '', query: {} } },
  { label: 'AL64', i18n: { key: '', query: {} } }
]
