exports.inputs1 = [
  { addr: 'E0.0', label: '' },
  { addr: 'E0.1', label: '' },
  { addr: 'E0.2', label: '' },
  { addr: 'E0.3', label: '' },
  { addr: 'E0.4', label: '' },
  { addr: 'E0.5', label: '' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' }
]
exports.inputs2 = [
  { addr: 'E10.0', label: '' },
  { addr: 'E10.1', label: '' },
  { addr: 'E10.2', label: '' },
  { addr: 'E10.3', label: '' },
  { addr: 'E10.4', label: '' },
  { addr: 'E10.5', label: '' },
  { addr: 'E10.6', label: '' },
  { addr: 'E10.7', label: '' },
  { addr: 'E11.0', label: '' },
  { addr: 'E11.1', label: '' },
  { addr: 'E11.2', label: '' },
  { addr: 'E11.3', label: '' },
  { addr: 'E11.4', label: '' },
  { addr: 'E11.5', label: '' },
  { addr: 'E11.6', label: '' },
  { addr: 'E11.7', label: '' },
  { addr: 'E12.0', label: '' },
  { addr: 'E12.1', label: '' },
  { addr: 'E12.2', label: '' },
  { addr: 'E12.3', label: '' },
  { addr: 'E12.4', label: '' },
  { addr: 'E12.5', label: '' },
  { addr: 'E12.6', label: '' },
  { addr: 'E12.7', label: '' },
  { addr: 'E13.0', label: '' },
  { addr: 'E13.1', label: '' },
  { addr: 'E13.2', label: '' },
  { addr: 'E13.3', label: '' },
  { addr: 'E13.4', label: '' },
  { addr: 'E13.5', label: '' },
  { addr: 'E13.6', label: '' },
  { addr: 'E13.7', label: '' },
  { addr: 'E14.0', label: '' },
  { addr: 'E14.1', label: '' },
  { addr: 'E14.2', label: '' },
  { addr: 'E14.3', label: '' },
  { addr: 'E14.4', label: '' },
  { addr: 'E14.5', label: '' },
  { addr: 'E14.6', label: '' },
  { addr: 'E14.7', label: '' },
  { addr: 'E15.0', label: '' },
  { addr: 'E15.1', label: '' },
  { addr: 'E15.2', label: '' },
  { addr: 'E15.3', label: '' },
  { addr: 'E15.4', label: '' },
  { addr: 'E15.5', label: '' },
  { addr: 'E15.6', label: '' },
  { addr: 'E15.7', label: '' },
  { addr: 'E16.0', label: '' },
  { addr: 'E16.1', label: '' },
  { addr: 'E16.2', label: '' },
  { addr: 'E16.3', label: '' },
  { addr: 'E16.4', label: '' },
  { addr: 'E16.5', label: '' },
  { addr: 'E16.6', label: '' },
  { addr: 'E16.7', label: '' },
  { addr: 'E17.0', label: '' },
  { addr: 'E17.1', label: '' },
  { addr: 'E17.2', label: '' },
  { addr: 'E17.3', label: '' },
  { addr: 'E17.4', label: '' },
  { addr: 'E17.5', label: '' },
  { addr: 'E17.6', label: '' },
  { addr: 'E17.7', label: '' }
]
exports.inputs3 = [
  { addr: 'E20.0', label: '' },
  { addr: 'E20.1', label: '' },
  { addr: 'E20.2', label: '' },
  { addr: 'E20.3', label: '' },
  { addr: 'E20.4', label: '' },
  { addr: 'E20.5', label: '' },
  { addr: 'E20.6', label: '' },
  { addr: 'E20.7', label: '' },
  { addr: 'E21.0', label: '' },
  { addr: 'E21.1', label: '' },
  { addr: 'E21.2', label: '' },
  { addr: 'E21.3', label: '' },
  { addr: 'E21.4', label: '' },
  { addr: 'E21.5', label: '' },
  { addr: 'E21.6', label: '' },
  { addr: 'E21.7', label: '' },
  { addr: 'E22.0', label: '' },
  { addr: 'E22.1', label: '' },
  { addr: 'E22.2', label: '' },
  { addr: 'E22.3', label: '' },
  { addr: 'E22.4', label: '' },
  { addr: 'E22.5', label: '' },
  { addr: 'E22.6', label: '' },
  { addr: 'E22.7', label: '' },
  { addr: 'E23.0', label: '' },
  { addr: 'E23.1', label: '' },
  { addr: 'E23.2', label: '' },
  { addr: 'E23.3', label: '' },
  { addr: 'E23.4', label: '' },
  { addr: 'E23.5', label: '' },
  { addr: 'E23.6', label: '' },
  { addr: 'E23.7', label: '' },
  { addr: 'E24.0', label: '' },
  { addr: 'E24.1', label: '' },
  { addr: 'E24.2', label: '' },
  { addr: 'E24.3', label: '' },
  { addr: 'E24.4', label: '' },
  { addr: 'E24.5', label: '' },
  { addr: 'E24.6', label: '' },
  { addr: 'E24.7', label: '' },
  { addr: 'E25.0', label: '' },
  { addr: 'E25.1', label: '' },
  { addr: 'E25.2', label: '' },
  { addr: 'E25.3', label: '' },
  { addr: 'E25.4', label: '' },
  { addr: 'E25.5', label: '' },
  { addr: 'E25.6', label: '' },
  { addr: 'E25.7', label: '' },
  { addr: 'E26.0', label: '' },
  { addr: 'E26.1', label: '' },
  { addr: 'E26.2', label: '' },
  { addr: 'E26.3', label: '' },
  { addr: 'E26.4', label: '' },
  { addr: 'E26.5', label: '' },
  { addr: 'E26.6', label: '' },
  { addr: 'E26.7', label: '' },
  { addr: 'E27.0', label: '' },
  { addr: 'E27.1', label: '' },
  { addr: 'E27.2', label: '' },
  { addr: 'E27.3', label: '' },
  { addr: 'E27.4', label: '' },
  { addr: 'E27.5', label: '' },
  { addr: 'E27.6', label: '' },
  { addr: 'E27.7', label: '' }
]
exports.inputs4 = [
  { addr: 'E30.0', label: '' },
  { addr: 'E30.1', label: '' },
  { addr: 'E30.2', label: '' },
  { addr: 'E30.3', label: '' },
  { addr: 'E30.4', label: '' },
  { addr: 'E30.5', label: '' },
  { addr: 'E30.6', label: '' },
  { addr: 'E30.7', label: '' },
  { addr: 'E31.0', label: '' },
  { addr: 'E31.1', label: '' },
  { addr: 'E31.2', label: '' },
  { addr: 'E31.3', label: '' },
  { addr: 'E31.4', label: '' },
  { addr: 'E31.5', label: '' },
  { addr: 'E31.6', label: '' },
  { addr: 'E31.7', label: '' },
  { addr: 'E32.0', label: '' },
  { addr: 'E32.1', label: '' },
  { addr: 'E32.2', label: '' },
  { addr: 'E32.3', label: '' },
  { addr: 'E32.4', label: '' },
  { addr: 'E32.5', label: '' },
  { addr: 'E32.6', label: '' },
  { addr: 'E32.7', label: '' },
  { addr: 'E33.0', label: '' },
  { addr: 'E33.1', label: '' },
  { addr: 'E33.2', label: '' },
  { addr: 'E33.3', label: '' },
  { addr: 'E33.4', label: '' },
  { addr: 'E33.5', label: '' },
  { addr: 'E33.6', label: '' },
  { addr: 'E33.7', label: '' },
  { addr: 'E34.0', label: '' },
  { addr: 'E34.1', label: '' },
  { addr: 'E34.2', label: '' },
  { addr: 'E34.3', label: '' },
  { addr: 'E34.4', label: '' },
  { addr: 'E34.5', label: '' },
  { addr: 'E34.6', label: '' },
  { addr: 'E34.7', label: '' },
  { addr: 'E35.0', label: '' },
  { addr: 'E35.1', label: '' },
  { addr: 'E35.2', label: '' },
  { addr: 'E35.3', label: '' },
  { addr: 'E35.4', label: '' },
  { addr: 'E35.5', label: '' },
  { addr: 'E35.6', label: '' },
  { addr: 'E35.7', label: '' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: '' },
  { addr: 'A0.1', label: '' },
  { addr: 'A0.2', label: '' },
  { addr: 'A0.3', label: '' },
  { addr: 'A0.4', label: '' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A10.0', label: '' },
  { addr: 'A10.1', label: '' },
  { addr: 'A10.2', label: '' },
  { addr: 'A10.3', label: '' },
  { addr: 'A10.4', label: '' },
  { addr: 'A10.5', label: '' },
  { addr: 'A10.6', label: '' },
  { addr: 'A10.7', label: '' },
  { addr: 'A11.0', label: '' },
  { addr: 'A11.1', label: '' },
  { addr: 'A11.2', label: '' },
  { addr: 'A11.3', label: '' },
  { addr: 'A11.4', label: '' },
  { addr: 'A11.5', label: '' },
  { addr: 'A11.6', label: '' },
  { addr: 'A11.7', label: '' },
  { addr: 'A12.0', label: '' },
  { addr: 'A12.1', label: '' },
  { addr: 'A12.2', label: '' },
  { addr: 'A12.3', label: '' },
  { addr: 'A12.4', label: '' },
  { addr: 'A12.5', label: '' },
  { addr: 'A12.6', label: '' },
  { addr: 'A12.7', label: '' },
  { addr: 'A13.0', label: '' },
  { addr: 'A13.1', label: '' },
  { addr: 'A13.2', label: '' },
  { addr: 'A13.3', label: '' },
  { addr: 'A13.4', label: '' },
  { addr: 'A13.5', label: '' },
  { addr: 'A13.6', label: '' },
  { addr: 'A13.7', label: '' },
  { addr: 'A14.0', label: '' },
  { addr: 'A14.1', label: '' },
  { addr: 'A14.2', label: '' },
  { addr: 'A14.3', label: '' },
  { addr: 'A14.4', label: '' },
  { addr: 'A14.5', label: '' },
  { addr: 'A14.6', label: '' },
  { addr: 'A14.7', label: '' },
  { addr: 'A15.0', label: '' },
  { addr: 'A15.1', label: '' },
  { addr: 'A15.2', label: '' },
  { addr: 'A15.3', label: '' },
  { addr: 'A15.4', label: '' },
  { addr: 'A15.5', label: '' },
  { addr: 'A15.6', label: '' },
  { addr: 'A15.7', label: '' },
  { addr: 'A16.0', label: '' },
  { addr: 'A16.1', label: '' },
  { addr: 'A16.2', label: '' },
  { addr: 'A16.3', label: '' },
  { addr: 'A16.4', label: '' },
  { addr: 'A16.5', label: '' },
  { addr: 'A16.6', label: '' },
  { addr: 'A16.7', label: '' },
  { addr: 'A17.0', label: '' },
  { addr: 'A17.1', label: '' },
  { addr: 'A17.2', label: '' },
  { addr: 'A17.3', label: '' },
  { addr: 'A17.4', label: '' },
  { addr: 'A17.5', label: '' },
  { addr: 'A17.6', label: '' },
  { addr: 'A17.7', label: '' }
]
exports.outputs3 = [
  { addr: 'A20.0', label: '' },
  { addr: 'A20.1', label: '' },
  { addr: 'A20.2', label: '' },
  { addr: 'A20.3', label: '' },
  { addr: 'A20.4', label: '' },
  { addr: 'A20.5', label: '' },
  { addr: 'A20.6', label: '' },
  { addr: 'A20.7', label: '' },
  { addr: 'A21.0', label: '' },
  { addr: 'A21.1', label: '' },
  { addr: 'A21.2', label: '' },
  { addr: 'A21.3', label: '' },
  { addr: 'A21.4', label: '' },
  { addr: 'A21.5', label: '' },
  { addr: 'A21.6', label: '' },
  { addr: 'A21.7', label: '' },
  { addr: 'A22.0', label: '' },
  { addr: 'A22.1', label: '' },
  { addr: 'A22.2', label: '' },
  { addr: 'A22.3', label: '' },
  { addr: 'A22.4', label: '' },
  { addr: 'A22.5', label: '' },
  { addr: 'A22.6', label: '' },
  { addr: 'A22.7', label: '' },
  { addr: 'A23.0', label: '' },
  { addr: 'A23.1', label: '' },
  { addr: 'A23.2', label: '' },
  { addr: 'A23.3', label: '' },
  { addr: 'A23.4', label: '' },
  { addr: 'A23.5', label: '' },
  { addr: 'A23.6', label: '' },
  { addr: 'A23.7', label: '' },
  { addr: 'A24.0', label: '' },
  { addr: 'A24.1', label: '' },
  { addr: 'A24.2', label: '' },
  { addr: 'A24.3', label: '' },
  { addr: 'A24.4', label: '' },
  { addr: 'A24.5', label: '' },
  { addr: 'A24.6', label: '' },
  { addr: 'A24.7', label: '' },
  { addr: 'A25.0', label: '' },
  { addr: 'A25.1', label: '' },
  { addr: 'A25.2', label: '' },
  { addr: 'A25.3', label: '' },
  { addr: 'A25.4', label: '' },
  { addr: 'A25.5', label: '' },
  { addr: 'A25.6', label: '' },
  { addr: 'A25.7', label: '' }
]
exports.outputs4 = [
  { addr: 'A30.0', label: '' },
  { addr: 'A30.1', label: '' },
  { addr: 'A30.2', label: '' },
  { addr: 'A30.3', label: '' },
  { addr: 'A30.4', label: '' },
  { addr: 'A30.5', label: '' },
  { addr: 'A30.6', label: '' },
  { addr: 'A30.7', label: '' },
  { addr: 'A31.0', label: '' },
  { addr: 'A31.1', label: '' },
  { addr: 'A31.2', label: '' },
  { addr: 'A31.3', label: '' },
  { addr: 'A31.4', label: '' },
  { addr: 'A31.5', label: '' },
  { addr: 'A31.6', label: '' },
  { addr: 'A31.7', label: '' },
  { addr: 'A32.0', label: '' },
  { addr: 'A32.1', label: '' },
  { addr: 'A32.2', label: '' },
  { addr: 'A32.3', label: '' },
  { addr: 'A32.4', label: '' },
  { addr: 'A32.5', label: '' },
  { addr: 'A32.6', label: '' },
  { addr: 'A32.7', label: '' },
  { addr: 'A33.0', label: '' },
  { addr: 'A33.1', label: '' },
  { addr: 'A33.2', label: '' },
  { addr: 'A33.3', label: '' },
  { addr: 'A33.4', label: '' },
  { addr: 'A33.5', label: '' },
  { addr: 'A33.6', label: '' },
  { addr: 'A33.7', label: '' }
]
exports.alarms1 = [
  { class: '1', label: 'AL1', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL2', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL3', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL4', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL5', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL6', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL7', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL8', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL9', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL10', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL11', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL12', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL13', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL14', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL15', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL16', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL17', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL18', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL19', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL20', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL21', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL22', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL23', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL24', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL25', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL26', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL27', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL28', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL29', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL30', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL31', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL32', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL33', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL34', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL35', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL36', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL37', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL38', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL39', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL40', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL41', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL42', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL43', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL44', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL45', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL46', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL47', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL48', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL49', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL50', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL51', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL52', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL53', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL54', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL55', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL56', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL57', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL58', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL59', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL60', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL61', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL62', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL63', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL64', i18n: { key: '', query: {} } }
]
exports.alarms2 = [
  { class: '2', label: 'AL1', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL2', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL3', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL4', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL5', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL6', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL7', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL8', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL9', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL10', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL11', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL12', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL13', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL14', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL15', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL16', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL17', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL18', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL19', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL20', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL21', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL22', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL23', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL24', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL25', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL26', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL27', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL28', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL29', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL30', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL31', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL32', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL33', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL34', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL35', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL36', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL37', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL38', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL39', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL40', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL41', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL42', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL43', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL44', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL45', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL46', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL47', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL48', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL49', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL50', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL51', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL52', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL53', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL54', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL55', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL56', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL57', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL58', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL59', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL60', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL61', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL62', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL63', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL64', i18n: { key: '', query: {} } }
]
exports.alarms3 = [
  { class: 'A', label: 'AL1', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL2', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL3', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL4', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL5', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL6', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL7', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL8', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL9', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL10', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL11', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL12', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL13', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL14', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL15', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL16', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL17', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL18', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL19', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL20', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL21', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL22', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL23', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL24', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL25', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL26', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL27', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL28', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL29', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL30', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL31', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL32', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL33', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL34', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL35', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL36', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL37', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL38', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL39', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL40', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL41', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL42', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL43', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL44', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL45', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL46', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL47', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL48', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL49', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL50', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL51', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL52', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL53', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL54', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL55', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL56', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL57', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL58', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL59', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL60', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL61', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL62', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL63', i18n: { key: '', query: {} } },
  { class: 'A', label: 'AL64', i18n: { key: '', query: {} } }
]
