exports.inputs1 = [
  { addr: 'E0.0', label: 'A', info: 'RFid reader' },
  { addr: 'E0.1', label: 'B', info: 'RFid reader' },
  { addr: 'E0.2', label: 'C', info: 'RFid reader' },
  { addr: 'E0.3', label: 'D', info: 'RFid reader' },
  { addr: 'E0.4', label: 'STR', info: 'RFid reader' },
  { addr: 'E0.5', label: 'OK', info: 'RFid reader' },
  { addr: 'E0.6', label: 'DAT', info: 'RFid reader' },
  { addr: 'E0.7', label: 'FLP2A', info: 'Back length (A)' },
  { addr: 'E1.0', label: 'A', info: 'RFid reader' },
  { addr: 'E1.1', label: 'B', info: 'RFid reader' },
  { addr: 'E1.2', label: 'C', info: 'RFid reader' },
  { addr: 'E1.3', label: 'D', info: 'RFid reader' },
  { addr: 'E1.4', label: 'STR', info: 'RFid reader' },
  { addr: 'E1.5', label: 'OK', info: 'RFid reader' },
  { addr: 'E1.6', label: 'DAT', info: 'RFid reader' },
  { addr: 'E1.7', label: 'FLP2B', info: 'Back length (B)' },
  { addr: 'E2.0', label: 'A', info: 'RFid reader' },
  { addr: 'E2.1', label: 'B', info: 'RFid reader' },
  { addr: 'E2.2', label: 'C', info: 'RFid reader' },
  { addr: 'E2.3', label: 'D', info: 'RFid reader' },
  { addr: 'E2.4', label: 'STR', info: 'RFid reader' },
  { addr: 'E2.5', label: 'OK', info: 'RFid reader' },
  { addr: 'E2.6', label: 'DAT', info: 'RFid reader' },
  { addr: 'E2.7', label: 'FLP2C', info: 'Back length (C)' },
  { addr: 'E3.0', label: 'A', info: 'RFid reader' },
  { addr: 'E3.1', label: 'B', info: 'RFid reader' },
  { addr: 'E3.2', label: 'C', info: 'RFid reader' },
  { addr: 'E3.3', label: 'D', info: 'RFid reader' },
  { addr: 'E3.4', label: 'STR', info: 'RFid reader' },
  { addr: 'E3.5', label: 'OK', info: 'RFid reader' },
  { addr: 'E3.6', label: 'DAT', info: 'RFid reader' },
  { addr: 'E3.7', label: '', info: '' },
  { addr: 'E4.0', label: 'A', info: '' },
  { addr: 'E4.1', label: 'B', info: '' },
  { addr: 'E4.2', label: 'C', info: '' },
  { addr: 'E4.3', label: 'D', info: '' },
  { addr: 'E4.4', label: 'OK', info: '' },
  { addr: 'E4.5', label: 'S1T1', info: '' },
  { addr: 'E4.6', label: 'S1T1', info: '' },
  { addr: 'E4.7', label: 'S1T1', info: '' },
  { addr: 'E5.0', label: 'ST1', info: '' },
  { addr: 'E5.1', label: 'ST1', info: '' },
  { addr: 'E5.2', label: 'ST2', info: '' },
  { addr: 'E5.3', label: 'ST2', info: '' },
  { addr: 'E5.4', label: 'ASKD', info: '' },
  { addr: 'E5.5', label: 'S1T2', info: '' },
  { addr: 'E5.6', label: 'S1T2', info: '' },
  { addr: 'E5.7', label: 'S1T2', info: '' },
  { addr: 'E6.0', label: '', info: '' },
  { addr: 'E6.1', label: '', info: '' },
  { addr: 'E6.2', label: '', info: '' },
  { addr: 'E6.3', label: '', info: '' },
  { addr: 'E6.4', label: 'OK-EM', info: '' },
  { addr: 'E6.5', label: '', info: '' },
  { addr: 'E6.6', label: '', info: '' },
  { addr: 'E6.7', label: '', info: '' },
  { addr: 'E7.0', label: 'EM-A', info: '' },
  { addr: 'E7.1', label: 'EM-B', info: '' },
  { addr: 'E7.2', label: 'EM-C', info: '' },
  { addr: 'E7.3', label: 'RSI', info: '' },
  { addr: 'E7.4', label: 'S-ABC', info: '' },
  { addr: 'E7.5', label: 'S-ABC', info: '' },
  { addr: 'E7.6', label: '', info: '' },
  { addr: 'E7.7', label: 'UC', info: 'Control confirmatio' },
  { addr: 'E8.0', label: 'IV', info: 'Inverter ready' },
  { addr: 'E8.1', label: 'EPA', info: '' },
  { addr: 'E8.2', label: 'RX', info: 'Radar' },
  { addr: 'E8.3', label: 'SPR', info: 'Vehicle detection loop' },
  { addr: 'E8.4', label: '', info: '' },
  { addr: 'E8.5', label: 'S1', info: 'Switch function key' },
  { addr: 'E8.6', label: 'S1', info: 'Switch function key' },
  { addr: 'E8.7', label: 'S1', info: 'Switch function key' },
  { addr: 'E9.0', label: 'MDR', info: 'Turntable position' },
  { addr: 'E9.1', label: 'MDL', info: 'Turntable position' },
  { addr: 'E9.2', label: 'EDR', info: 'Turntable position check' },
  { addr: 'E9.3', label: 'EDL', info: 'Turntable position check' },
  { addr: 'E9.4', label: 'EPB', info: '' },
  { addr: 'E9.5', label: 'ECA', info: 'Flap high position' },
  { addr: 'E9.6', label: 'ECB', info: 'Flap low position' },
  { addr: 'E9.7', label: 'AMC', info: 'Flap motor protection' },
  { addr: 'E10.0', label: 'EPZV', info: 'Wheel detection front' },
  { addr: 'E10.1', label: 'EPZH', info: 'Wheel detection back' },
  { addr: 'E10.2', label: 'FLP', info: 'Back length detection' },
  { addr: 'E10.3', label: 'FPE', info: 'Car presence' },
  { addr: 'E10.4', label: 'FDR', info: 'Car right width check' },
  { addr: 'E10.5', label: 'FDL', info: 'Car left width check' },
  { addr: 'E10.6', label: 'FTA1', info: 'Car max height detection' },
  { addr: 'E10.7', label: 'FTA2', info: 'Car height detection' },
  { addr: 'E11.0', label: 'EZE', info: 'Door closed' },
  { addr: 'E11.1', label: 'EOE', info: 'Door opened' },
  { addr: 'E11.2', label: 'FBE', info: 'Door safety sensor' },
  { addr: 'E11.3', label: 'APE', info: 'Door motor protection' },
  { addr: 'E11.4', label: 'EBZE', info: 'Gate closed' },
  { addr: 'E11.5', label: 'EBOE', info: 'Gate opened' },
  { addr: 'E11.6', label: 'FBBE', info: 'Gate safety sensor' },
  { addr: 'E11.7', label: 'APBE', info: 'Gate motor protection' },
  { addr: 'E12.0', label: 'IV', info: 'Inverter ready' },
  { addr: 'E12.1', label: 'EPA', info: '' },
  { addr: 'E12.2', label: 'RX', info: 'Radar' },
  { addr: 'E12.3', label: 'SPR', info: 'Vehicle detection loop' },
  { addr: 'E12.4', label: '', info: '' },
  { addr: 'E12.5', label: 'S1', info: '' },
  { addr: 'E12.6', label: 'S1', info: '' },
  { addr: 'E12.7', label: 'S1', info: '' },
  { addr: 'E13.0', label: 'MDR', info: 'Turntable position' },
  { addr: 'E13.1', label: 'MDL', info: 'Turntable position' },
  { addr: 'E13.2', label: 'EDR', info: 'Turntable position check' },
  { addr: 'E13.3', label: 'EDL', info: 'Turntable position check' },
  { addr: 'E13.4', label: 'EPB', info: '' },
  { addr: 'E13.5', label: 'ECA', info: 'Flap high position' },
  { addr: 'E13.6', label: 'ECB', info: 'Flap low position' },
  { addr: 'E13.7', label: 'AMC', info: 'Flap motor protection' },
  { addr: 'E14.0', label: 'EPZV', info: 'Wheel detection front' },
  { addr: 'E14.1', label: 'EPZH', info: 'Wheel detection back' },
  { addr: 'E14.2', label: 'FLP', info: 'Back length detection' },
  { addr: 'E14.3', label: 'FPE', info: 'Car presence' },
  { addr: 'E14.4', label: 'FDR', info: 'Car right width check' },
  { addr: 'E14.5', label: 'FDL', info: 'Car left width check' },
  { addr: 'E14.6', label: 'FTA1', info: 'Car max height detection' },
  { addr: 'E14.7', label: 'FTA2', info: 'Car height detection' },
  { addr: 'E15.0', label: 'EZE', info: 'Door closed' },
  { addr: 'E15.1', label: 'EOE', info: 'Door opened' },
  { addr: 'E15.2', label: 'FBE', info: 'Door safety sensor' },
  { addr: 'E15.3', label: 'APE', info: 'Door motor protection' },
  { addr: 'E15.4', label: 'EBZE', info: 'Gate closed' },
  { addr: 'E15.5', label: 'EBOE', info: 'Gate opened' },
  { addr: 'E15.6', label: 'FBBE', info: 'Gate safety sensor' },
  { addr: 'E15.7', label: 'APBE', info: 'Gate motor protection' },
  { addr: 'E16.0', label: 'IV', info: 'Inverter ready' },
  { addr: 'E16.1', label: 'EPA', info: '' },
  { addr: 'E16.2', label: 'RX', info: 'Radar' },
  { addr: 'E16.3', label: 'SPR', info: 'Vehicle detection loop' },
  { addr: 'E16.4', label: '', info: '' },
  { addr: 'E16.5', label: 'S1', info: '' },
  { addr: 'E16.6', label: 'S1', info: '' },
  { addr: 'E16.7', label: 'S1', info: '' },
  { addr: 'E17.0', label: 'MDR', info: 'Turntable position' },
  { addr: 'E17.1', label: 'MDL', info: 'Turntable position' },
  { addr: 'E17.2', label: 'EDR', info: 'Turntable position check' },
  { addr: 'E17.3', label: 'EDL', info: 'Turntable position check' },
  { addr: 'E17.4', label: 'EPB', info: '' },
  { addr: 'E17.5', label: 'ECA', info: 'Flap high position' },
  { addr: 'E17.6', label: 'ECB', info: 'Flap low position' },
  { addr: 'E17.7', label: 'AMC', info: 'Flap motor protection' },
  { addr: 'E18.0', label: 'EPZV', info: 'Wheel detection front' },
  { addr: 'E18.1', label: 'EPZH', info: 'Wheel detection back' },
  { addr: 'E18.2', label: 'FLP', info: 'Back length detection' },
  { addr: 'E18.3', label: 'FPE', info: 'Car presence' },
  { addr: 'E18.4', label: 'FDR', info: 'Car right width check' },
  { addr: 'E18.5', label: 'FDL', info: 'Car left width check' },
  { addr: 'E18.6', label: 'FTA1', info: 'Car max height detection' },
  { addr: 'E18.7', label: 'FTA2', info: 'Car height detection' },
  { addr: 'E19.0', label: 'EZE', info: 'Door closed' },
  { addr: 'E19.1', label: 'EOE', info: 'Door opened' },
  { addr: 'E19.2', label: 'FBE', info: 'Door safety sensor' },
  { addr: 'E19.3', label: 'APE', info: 'Door motor protection' },
  { addr: 'E19.4', label: 'EBZE', info: 'Gate closed' },
  { addr: 'E19.5', label: 'EBOE', info: 'Gate opened' },
  { addr: 'E19.6', label: 'FBBE', info: 'Gate safety sensor' },
  { addr: 'E19.7', label: 'APBE', info: 'Gate motor protection' }
]
exports.inputs2 = [
  { addr: 'E20.0', label: 'A', info: 'Mobile keyboard' },
  { addr: 'E20.1', label: 'B', info: 'Mobile keyboard' },
  { addr: 'E20.2', label: 'C', info: 'Mobile keyboard' },
  { addr: 'E20.3', label: 'D', info: 'Mobile keyboard' },
  { addr: 'E20.4', label: 'OK', info: 'Mobile keyboard' },
  { addr: 'E20.5', label: 'S2', info: 'Switch function mode' },
  { addr: 'E20.6', label: 'S2', info: 'Switch function mode' },
  { addr: 'E20.7', label: 'S2', info: 'Switch function mode' },
  { addr: 'E21.0', label: 'FTV', info: 'Car detection in stall (front)' },
  { addr: 'E21.1', label: 'FTH1', info: 'Car detection in stall (back)' },
  { addr: 'E21.2', label: 'EOM', info: 'Locking pin opened' },
  { addr: 'E21.3', label: 'EZM', info: 'Locking pin closed' },
  { addr: 'E21.4', label: 'FEMV', info: 'Silomat center position' },
  { addr: 'E21.5', label: 'FEMH', info: 'Silomat center position' },
  { addr: 'E21.6', label: 'FTXV', info: 'Tower interference check (front)' },
  { addr: 'E21.7', label: 'FTXH', info: 'Tower interference check (back)' },
  { addr: 'E22.0', label: 'RMV', info: 'Silomat front position' },
  { addr: 'E22.1', label: 'RMH', info: 'Silomat back position' },
  { addr: 'E22.2', label: 'RES', info: 'Silomat low' },
  { addr: 'E22.3', label: 'REH', info: 'Silomat high' },
  { addr: 'E22.4', label: 'RCV', info: 'Silomat front centering closed' },
  { addr: 'E22.5', label: 'REAV', info: 'Silomat front centered' },
  { addr: 'E22.6', label: 'REAH', info: 'Silomat back centered' },
  { addr: 'E22.7', label: 'RCH', info: 'Silomat back centering closed' },
  { addr: 'E23.0', label: 'IV1', info: 'Inverter 1 ready' },
  { addr: 'E23.1', label: 'IV2', info: 'Inverter 2 ready' },
  { addr: 'E23.2', label: 'S1', info: 'Man/Aut' },
  { addr: 'E23.3', label: 'RSI', info: 'System ready' },
  { addr: 'E23.4', label: 'DB32', info: 'Enable data intro (1)' },
  { addr: 'E23.5', label: 'DBHZ', info: 'Enable data intro (2)' },
  { addr: 'E23.6', label: 'FTH2', info: 'Car detection in stall (back)' },
  { addr: 'E23.7', label: 'UC', info: 'Control confirmation' },
  { addr: 'E24.0', label: 'EFR', info: 'Tower travelling max position check' },
  { addr: 'E24.1', label: 'EFL', info: 'Tower travelling max position check' },
  { addr: 'E24.2', label: 'EHP', info: 'Tower travelling VG position check' },
  { addr: 'E24.3', label: 'EXPV', info: 'Tower vertical VG position check' },
  { addr: 'E24.4', label: 'ASBK2', info: 'Tower motor brake protection' },
  { addr: 'E24.5', label: 'TCR', info: 'Cable-reel feddback' },
  { addr: 'E24.6', label: 'AH', info: 'Tower travelling motors protection' },
  { addr: 'E24.7', label: 'MTC', info: 'Silomat motors protection' },
  { addr: 'E25.0', label: 'EFA', info: 'Tower hoisting max position check' },
  { addr: 'E25.1', label: 'EFB', info: 'Tower hoisting max position check' },
  { addr: 'E25.2', label: 'EXV', info: 'Tower level position check' },
  { addr: 'E25.3', label: 'FDBK', info: 'Tower hoisting feedback' },
  { addr: 'E25.4', label: 'ASBK', info: 'Hoisting motors brake protection' },
  { addr: 'E25.5', label: 'RTA', info: 'Hoisting motors protection' },
  { addr: 'E25.6', label: 'TJ2', info: 'Inverter 2 on' },
  { addr: 'E25.7', label: 'AMM', info: 'Locking pin motor protection' }
]
exports.inputs3 = [
  { addr: 'E26.0', label: 'A', info: 'Mobile keyboard' },
  { addr: 'E26.1', label: 'B', info: 'Mobile keyboard' },
  { addr: 'E26.2', label: 'C', info: 'Mobile keyboard' },
  { addr: 'E26.3', label: 'D', info: 'Mobile keyboard' },
  { addr: 'E26.4', label: 'OK', info: 'Mobile keyboard' },
  { addr: 'E26.5', label: 'S2', info: 'Switch function mode' },
  { addr: 'E26.6', label: 'S2', info: 'Switch function mode' },
  { addr: 'E26.7', label: 'S2', info: 'Switch function mode' },
  { addr: 'E27.0', label: 'FTV', info: 'Car detection in stall (front)' },
  { addr: 'E27.1', label: 'FTH1', info: 'Car detection in stall (back)' },
  { addr: 'E27.2', label: 'EOM', info: 'Locking pin opened' },
  { addr: 'E27.3', label: 'EZM', info: 'Locking pin closed' },
  { addr: 'E27.4', label: 'FEMV', info: 'Silomat center position' },
  { addr: 'E27.5', label: 'FEMH', info: 'Silomat center position' },
  { addr: 'E27.6', label: 'FTXV', info: 'Tower interference check (front)' },
  { addr: 'E27.7', label: 'FTXH', info: 'Tower interference check (back)' },
  { addr: 'E28.0', label: 'RMV', info: 'Silomat front position' },
  { addr: 'E28.1', label: 'RMH', info: 'Silomat back position' },
  { addr: 'E28.2', label: 'RES', info: 'Silomat low' },
  { addr: 'E28.3', label: 'REH', info: 'Silomat high' },
  { addr: 'E28.4', label: 'RCV', info: 'Silomat front centering closed' },
  { addr: 'E28.5', label: 'REAV', info: 'Silomat front centered' },
  { addr: 'E28.6', label: 'REAH', info: 'Silomat back centered' },
  { addr: 'E28.7', label: 'RCH', info: 'Silomat back centering closed' },
  { addr: 'E29.0', label: 'IV1', info: 'Inverter 1 ready' },
  { addr: 'E29.1', label: 'IV2', info: 'Inverter 2 ready' },
  { addr: 'E29.2', label: 'S1', info: 'Man/Aut' },
  { addr: 'E29.3', label: 'RSI', info: 'System ready' },
  { addr: 'E29.4', label: 'DB32', info: 'Enable data intro (1)' },
  { addr: 'E29.5', label: 'DBHZ', info: 'Enable data intro (2)' },
  { addr: 'E29.6', label: 'FTH2', info: 'Car detection in stall (back)' },
  { addr: 'E29.7', label: 'UC', info: 'Control confirmation' },
  { addr: 'E30.0', label: 'EFR', info: 'Tower travelling max position check' },
  { addr: 'E30.1', label: 'EFL', info: 'Tower travelling max position check' },
  { addr: 'E30.2', label: 'EHP', info: 'Tower travelling VG position check' },
  { addr: 'E30.3', label: 'EXPV', info: 'Tower vertical VG position check' },
  { addr: 'E30.4', label: 'ASBK2', info: 'Tower motor brake protection' },
  { addr: 'E30.5', label: 'TCR', info: 'Cable-reel feddback' },
  { addr: 'E30.6', label: 'AH', info: 'Tower travelling motors protection' },
  { addr: 'E30.7', label: 'MTC', info: 'Silomat motors protection' },
  { addr: 'E31.0', label: 'EFA', info: 'Tower hoisting max position check' },
  { addr: 'E31.1', label: 'EFB', info: 'Tower hoisting max position check' },
  { addr: 'E31.2', label: 'EXV', info: 'Tower level position check' },
  { addr: 'E31.3', label: 'FDBK', info: 'Tower hoisting feedback' },
  { addr: 'E31.4', label: 'ASBK', info: 'Hoisting motors brake protection' },
  { addr: 'E31.5', label: 'RTA', info: 'Hoisting motors protection' },
  { addr: 'E31.6', label: 'TJ2', info: 'Inverter 2 on' },
  { addr: 'E31.7', label: 'AMM', info: 'Locking pin motor protection' }
]
exports.inputs4 = [
  { addr: 'E32.0', label: '', info: '' },
  { addr: 'E32.1', label: '', info: '' },
  { addr: 'E32.2', label: '', info: '' },
  { addr: 'E32.3', label: '', info: '' },
  { addr: 'E32.4', label: '', info: '' },
  { addr: 'E32.5', label: '', info: '' },
  { addr: 'E32.6', label: '', info: '' },
  { addr: 'E32.7', label: '', info: '' },
  { addr: 'E33.0', label: '', info: '' },
  { addr: 'E33.1', label: '', info: '' },
  { addr: 'E33.2', label: '', info: '' },
  { addr: 'E33.3', label: '', info: '' },
  { addr: 'E33.4', label: '', info: '' },
  { addr: 'E33.5', label: '', info: '' },
  { addr: 'E33.6', label: '', info: '' },
  { addr: 'E33.7', label: '', info: '' },
  { addr: 'E34.0', label: '', info: '' },
  { addr: 'E34.1', label: '', info: '' },
  { addr: 'E34.2', label: '', info: '' },
  { addr: 'E34.3', label: '', info: '' },
  { addr: 'E34.4', label: '', info: '' },
  { addr: 'E34.5', label: '', info: '' },
  { addr: 'E34.6', label: '', info: '' },
  { addr: 'E34.7', label: '', info: '' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'LK', info: 'Enter PIN code' },
  { addr: 'A0.1', label: 'LE', info: 'Error' },
  { addr: 'A0.2', label: 'LB', info: 'In operation' },
  { addr: 'A0.3', label: 'RDY', info: 'RFid reader' },
  { addr: 'A0.4', label: 'RST', info: 'RFid reader' },
  { addr: 'A0.5', label: '', info: '' },
  { addr: 'A0.6', label: '', info: '' },
  { addr: 'A0.7', label: 'RBE', info: '24VDC RFid reader' },
  { addr: 'A1.0', label: 'LK', info: 'Enter PIN code' },
  { addr: 'A1.1', label: 'LE', info: 'Error' },
  { addr: 'A1.2', label: 'LB', info: 'In operation' },
  { addr: 'A1.3', label: 'RDY', info: 'RFid reader' },
  { addr: 'A1.4', label: 'RST', info: 'RFid reader' },
  { addr: 'A1.5', label: '', info: '' },
  { addr: 'A1.6', label: 'LA', info: 'Alarm' },
  { addr: 'A1.7', label: 'RBE', info: '24VDC RFid reader' },
  { addr: 'A2.0', label: 'LK', info: 'Enter PIN code' },
  { addr: 'A2.1', label: 'LE', info: 'Error' },
  { addr: 'A2.2', label: 'LB', info: 'In operation' },
  { addr: 'A2.3', label: 'RDY', info: 'RFid reader' },
  { addr: 'A2.4', label: 'RST', info: 'RFid reader' },
  { addr: 'A2.5', label: '', info: '' },
  { addr: 'A2.6', label: '', info: '' },
  { addr: 'A2.7', label: 'RBE', info: '24VDC RFid reader' },
  { addr: 'A3.0', label: 'LK', info: 'Enter PIN code' },
  { addr: 'A3.1', label: 'LE', info: 'Error' },
  { addr: 'A3.2', label: 'LB', info: 'In operation' },
  { addr: 'A3.3', label: 'RDY', info: 'RFid reader' },
  { addr: 'A3.4', label: 'RST', info: 'RFid reader' },
  { addr: 'A3.5', label: 'LCT1', info: '' },
  { addr: 'A3.6', label: 'LCT2', info: '' },
  { addr: 'A3.7', label: 'RBE', info: '24VDC RFid reader' },
  { addr: 'A4.0', label: 'SCA', info: 'Flap up' },
  { addr: 'A4.1', label: 'SCB', info: 'Flap down' },
  { addr: 'A4.2', label: 'TD', info: 'Turntable rotation' },
  { addr: 'A4.3', label: 'SP', info: 'Line door' },
  { addr: 'A4.4', label: 'SZ', info: 'Close door' },
  { addr: 'A4.5', label: 'SO', info: 'Open door' },
  { addr: 'A4.6', label: 'SBZ', info: 'Close gate' },
  { addr: 'A4.7', label: 'SBO', info: 'Open gate' },
  { addr: 'A5.0', label: 'L1', info: 'Light panel' },
  { addr: 'A5.1', label: 'L2', info: 'Light panel' },
  { addr: 'A5.2', label: 'L3', info: 'Light panel' },
  { addr: 'A5.3', label: 'L4', info: 'Light panel' },
  { addr: 'A5.4', label: 'L5', info: 'Light panel' },
  { addr: 'A5.5', label: 'RFE', info: 'Traffic light' },
  { addr: 'A5.6', label: 'RLN', info: 'Light' },
  { addr: 'A5.7', label: 'KBA', info: 'Inverter enable' },
  { addr: 'A6.0', label: 'SCA', info: 'Flap up' },
  { addr: 'A6.1', label: 'SCB', info: 'Flap down' },
  { addr: 'A6.2', label: 'TD', info: 'Turntable rotation' },
  { addr: 'A6.3', label: 'SP', info: 'Line door' },
  { addr: 'A6.4', label: 'SZ', info: 'Close door' },
  { addr: 'A6.5', label: 'SO', info: 'Open door' },
  { addr: 'A6.6', label: 'SBZ', info: 'Close gate' },
  { addr: 'A6.7', label: 'SBO', info: 'Open gate' },
  { addr: 'A7.0', label: 'L1', info: 'Light panel' },
  { addr: 'A7.1', label: 'L2', info: 'Light panel' },
  { addr: 'A7.2', label: 'L3', info: 'Light panel' },
  { addr: 'A7.3', label: 'L4', info: 'Light panel' },
  { addr: 'A7.4', label: 'L5', info: 'Light panel' },
  { addr: 'A7.5', label: 'RFE', info: 'Traffic light' },
  { addr: 'A7.6', label: 'RLN', info: 'Light' },
  { addr: 'A7.7', label: 'KBA', info: 'Inverter enable' },
  { addr: 'A8.0', label: 'SCA', info: 'Flap up' },
  { addr: 'A8.1', label: 'SCB', info: 'Flap down' },
  { addr: 'A8.2', label: 'TD', info: 'Turntable rotation' },
  { addr: 'A8.3', label: 'SP', info: 'Line door' },
  { addr: 'A8.4', label: 'SZ', info: 'Close door' },
  { addr: 'A8.5', label: 'SO', info: 'Open door' },
  { addr: 'A8.6', label: 'SBZ', info: 'Close gate' },
  { addr: 'A8.7', label: 'SBO', info: 'Open gate' },
  { addr: 'A9.0', label: 'L1', info: 'Light panel' },
  { addr: 'A9.1', label: 'L2', info: 'Light panel' },
  { addr: 'A9.2', label: 'L3', info: 'Light panel' },
  { addr: 'A9.3', label: 'L4', info: 'Light panel' },
  { addr: 'A9.4', label: 'L5', info: 'Light panel' },
  { addr: 'A9.5', label: 'RFE', info: 'Traffic light' },
  { addr: 'A9.6', label: 'RLN', info: 'Light' },
  { addr: 'A9.7', label: 'KBA', info: 'Inverter enable' },
  { addr: 'A10.0', label: 'A', info: 'Display' },
  { addr: 'A10.1', label: 'B', info: 'Display' },
  { addr: 'A10.2', label: 'C', info: 'Display' },
  { addr: 'A10.3', label: 'D', info: 'Display' },
  { addr: 'A10.4', label: 'AD1', info: 'Display' },
  { addr: 'A10.5', label: 'AD2', info: 'Display' },
  { addr: 'A10.6', label: 'AD3', info: 'Display' },
  { addr: 'A10.7', label: 'STR', info: 'Display' },
  { addr: 'A11.0', label: 'A', info: 'Display' },
  { addr: 'A11.1', label: 'B', info: 'Display' },
  { addr: 'A11.2', label: 'C', info: 'Display' },
  { addr: 'A11.3', label: 'D', info: 'Display' },
  { addr: 'A11.4', label: 'AD1', info: 'Display' },
  { addr: 'A11.5', label: 'AD2', info: 'Display' },
  { addr: 'A11.6', label: 'AD3', info: 'Display' },
  { addr: 'A11.7', label: 'STR', info: 'Display' }
]
exports.outputs2 = [
  { addr: 'A20.0', label: 'KBA1', info: 'Inverter 1 enable' },
  { addr: 'A20.1', label: 'SBK1', info: 'Hoisting motor brake' },
  { addr: 'A20.2', label: 'SMA', info: 'Lock' },
  { addr: 'A20.3', label: 'SMB', info: 'Unlock' },
  { addr: 'A20.4', label: '', info: '' },
  { addr: 'A20.5', label: '', info: '' },
  { addr: 'A20.6', label: '', info: '' },
  { addr: 'A20.7', label: '', info: '' },
  { addr: 'A21.0', label: 'KBA2', info: 'Inverter 2 enable' },
  { addr: 'A21.1', label: 'SBK2', info: 'Hoisting motor brake' },
  { addr: 'A21.2', label: 'T10F', info: 'Tower travelling brake' },
  { addr: 'A21.3', label: '', info: '' },
  { addr: 'A21.4', label: '', info: '' },
  { addr: 'A21.5', label: '', info: '' },
  { addr: 'A21.6', label: '', info: '' },
  { addr: 'A21.7', label: 'LC', info: 'System ready' },
  { addr: 'A22.0', label: 'A', info: 'Display' },
  { addr: 'A22.1', label: 'B', info: 'Display' },
  { addr: 'A22.2', label: 'C', info: 'Display' },
  { addr: 'A22.3', label: 'D', info: 'Display' },
  { addr: 'A22.4', label: 'AD1', info: 'Display' },
  { addr: 'A22.5', label: 'AD2', info: 'Display' },
  { addr: 'A22.6', label: 'AD3', info: 'Display' },
  { addr: 'A22.7', label: 'STR', info: 'Display' },
  { addr: 'A23.0', label: 'T10', info: 'Tower travelling' },
  { addr: 'A23.1', label: 'T2', info: 'Silomat travelling' },
  { addr: 'A23.2', label: 'TRA', info: 'Silomat FWD' },
  { addr: 'A23.3', label: 'TRB', info: 'Silomat BWD' },
  { addr: 'A23.4', label: 'KCS', info: 'Silomat hoisting' },
  { addr: 'A23.5', label: 'KCV', info: 'Silomat centering front' },
  { addr: 'A23.6', label: 'KCH', info: 'Silomat centering back' },
  { addr: 'A23.7', label: 'TCR', info: 'Cable-reel' }
]
exports.outputs3 = [
  { addr: 'A26.0', label: 'KBA1', info: 'Inverter 1 enable' },
  { addr: 'A26.1', label: 'SBK1', info: 'Hoisting motor brake' },
  { addr: 'A26.2', label: 'SMA', info: 'Lock' },
  { addr: 'A26.3', label: 'SMB', info: 'Unlock' },
  { addr: 'A26.4', label: '', info: '' },
  { addr: 'A26.5', label: '', info: '' },
  { addr: 'A26.6', label: '', info: '' },
  { addr: 'A26.7', label: '', info: '' },
  { addr: 'A27.0', label: 'KBA2', info: 'Inverter 2 enable' },
  { addr: 'A27.1', label: 'SBK2', info: 'Hoisting motor brake' },
  { addr: 'A27.2', label: 'T10F', info: 'Tower travelling brake' },
  { addr: 'A27.3', label: '', info: '' },
  { addr: 'A27.4', label: '', info: '' },
  { addr: 'A27.5', label: '', info: '' },
  { addr: 'A27.6', label: '', info: '' },
  { addr: 'A27.7', label: 'LC', info: 'System ready' },
  { addr: 'A28.0', label: 'A', info: 'Display' },
  { addr: 'A28.1', label: 'B', info: 'Display' },
  { addr: 'A28.2', label: 'C', info: 'Display' },
  { addr: 'A28.3', label: 'D', info: 'Display' },
  { addr: 'A28.4', label: 'AD1', info: 'Display' },
  { addr: 'A28.5', label: 'AD2', info: 'Display' },
  { addr: 'A28.6', label: 'AD3', info: 'Display' },
  { addr: 'A28.7', label: 'STR', info: 'Display' },
  { addr: 'A29.0', label: 'T10', info: 'Tower travelling' },
  { addr: 'A29.1', label: 'T2', info: 'Silomat travelling' },
  { addr: 'A29.2', label: 'TRA', info: 'Silomat FWD' },
  { addr: 'A29.3', label: 'TRB', info: 'Silomat BWD' },
  { addr: 'A29.4', label: 'KCS', info: 'Silomat hoisting' },
  { addr: 'A29.5', label: 'KCV', info: 'Silomat centering front' },
  { addr: 'A29.6', label: 'KCH', info: 'Silomat centering back' },
  { addr: 'A29.7', label: 'TCR', info: 'Cable-reel' }
]
exports.outputs4 = [
  { addr: 'A32.0', label: '', info: '' },
  { addr: 'A32.1', label: '', info: '' },
  { addr: 'A32.2', label: '', info: '' },
  { addr: 'A32.3', label: '', info: '' },
  { addr: 'A32.4', label: '', info: '' },
  { addr: 'A32.5', label: '', info: '' },
  { addr: 'A32.6', label: '', info: '' },
  { addr: 'A32.7', label: '', info: '' },
  { addr: 'A33.0', label: '', info: '' },
  { addr: 'A33.1', label: '', info: '' },
  { addr: 'A33.2', label: '', info: '' },
  { addr: 'A33.3', label: '', info: '' },
  { addr: 'A33.4', label: '', info: '' },
  { addr: 'A33.5', label: '', info: '' },
  { addr: 'A33.6', label: '', info: '' },
  { addr: 'A33.7', label: '', info: '' }
]
exports.T = [
  { class: '1', label: 'AL1', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL2', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL3', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL4', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL5', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL6', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL7', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL8', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL9', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL10', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL11', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL12', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL13', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL14', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL15', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL16', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL17', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL18', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL19', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL20', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL21', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL22', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL23', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL24', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL25', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL26', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL27', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL28', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL29', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL30', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL31', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL32', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL33', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL34', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL35', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL36', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL37', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL38', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL39', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL40', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL41', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL42', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL43', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL44', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL45', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL46', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL47', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL48', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL49', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL50', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL51', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL52', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL53', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL54', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL55', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL56', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL57', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL58', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL59', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL60', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL61', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL62', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL63', i18n: { key: '', query: {} } },
  { class: '1', label: 'AL64', i18n: { key: '', query: {} } }
]
exports.VG = [
  { class: '2', label: 'AL1', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL2', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL3', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL4', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL5', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL6', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL7', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL8', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL9', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL10', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL11', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL12', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL13', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL14', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL15', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL16', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL17', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL18', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL19', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL20', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL21', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL22', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL23', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL24', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL25', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL26', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL27', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL28', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL29', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL30', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL31', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL32', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL33', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL34', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL35', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL36', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL37', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL38', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL39', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL40', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL41', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL42', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL43', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL44', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL45', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL46', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL47', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL48', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL49', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL50', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL51', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL52', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL53', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL54', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL55', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL56', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL57', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL58', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL59', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL60', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL61', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL62', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL63', i18n: { key: '', query: {} } },
  { class: '2', label: 'AL64', i18n: { key: '', query: {} } }
]
