exports.inputs1 = [
  { addr: 'E0.0', label: 'BA' },
  { addr: 'E0.1', label: 'BB' },
  { addr: 'E0.2', label: 'BC' },
  { addr: 'E0.3', label: 'BD' },
  { addr: 'E0.4', label: 'BSTR' },
  { addr: 'E0.5', label: 'BOK' },
  { addr: 'E0.6', label: 'BDAT' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: 'BA' },
  { addr: 'E1.1', label: 'BB' },
  { addr: 'E1.2', label: 'BC' },
  { addr: 'E1.3', label: 'BD' },
  { addr: 'E1.4', label: 'BSTR' },
  { addr: 'E1.5', label: 'BOK' },
  { addr: 'E1.6', label: 'BDAT' },
  { addr: 'E1.7', label: '' },
  { addr: 'E2.0', label: 'SFA' },
  { addr: 'E2.1', label: 'SFB' },
  { addr: 'E2.2', label: 'SFC' },
  { addr: 'E2.3', label: 'SFT1' },
  { addr: 'E2.4', label: 'SFT2' },
  { addr: 'E2.5', label: 'SFT3' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: 'RSI' },
  { addr: 'E3.0', label: '' },
  { addr: 'E3.1', label: '' },
  { addr: 'E3.2', label: '' },
  { addr: 'E3.3', label: '' },
  { addr: 'E3.4', label: '' },
  { addr: 'E3.5', label: '' },
  { addr: 'E3.6', label: '' },
  { addr: 'E3.7', label: 'FE' }
]
exports.inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: 'A' },
  { addr: 'E101.1', label: 'B' },
  { addr: 'E101.2', label: 'C' },
  { addr: 'E101.3', label: 'D' },
  { addr: 'E101.4', label: 'STR' },
  { addr: 'E101.5', label: 'OK' },
  { addr: 'E101.6', label: 'DAT' },
  { addr: 'E101.7', label: '' },
  { addr: 'E102.0', label: 'KEXPV' },
  { addr: 'E102.1', label: 'FTC' },
  { addr: 'E102.2', label: 'EXPV' },
  { addr: 'E102.3', label: 'EFB' },
  { addr: 'E102.4', label: 'ECA' },
  { addr: 'E102.5', label: 'ECB' },
  { addr: 'E102.6', label: 'AMC' },
  { addr: 'E102.7', label: 'APE' },
  { addr: 'E103.0', label: 'FTXV' },
  { addr: 'E103.1', label: 'FTXH' },
  { addr: 'E103.2', label: 'RS3' },
  { addr: 'E103.3', label: 'RS12' },
  { addr: 'E103.4', label: 'DB32' },
  { addr: 'E103.5', label: 'DBHZ' },
  { addr: 'E103.6', label: 'KXPE' },
  { addr: 'E103.7', label: 'AF7' },
  { addr: 'E104.0', label: 'FKBA' },
  { addr: 'E104.1', label: 'ASBK2' },
  { addr: 'E104.2', label: 'SRL' },
  { addr: 'E104.3', label: 'IV1' },
  { addr: 'E104.4', label: 'FSBK' },
  { addr: 'E104.5', label: 'ASBK1' },
  { addr: 'E104.6', label: 'RTA' },
  { addr: 'E104.7', label: 'SQA' },
  { addr: 'E105.0', label: 'FE12' },
  { addr: 'E105.1', label: 'AD' },
  { addr: 'E105.2', label: 'EXD' },
  { addr: 'E105.3', label: 'EOM' },
  { addr: 'E105.4', label: 'EZM' },
  { addr: 'E105.5', label: 'AMM' },
  { addr: 'E105.6', label: '' },
  { addr: 'E105.7', label: '' },
  { addr: 'E106.0', label: 'EZE' },
  { addr: 'E106.1', label: 'EOE' },
  { addr: 'E106.2', label: 'FBE' },
  { addr: 'E106.3', label: 'FPE' },
  { addr: 'E106.4', label: 'FDR1' },
  { addr: 'E106.5', label: 'FDL1' },
  { addr: 'E106.6', label: 'FTA1' },
  { addr: 'E106.7', label: 'FTA2' },
  { addr: 'E107.0', label: 'FLP1' },
  { addr: 'E107.1', label: 'FLP2' },
  { addr: 'E107.2', label: 'FLA' },
  { addr: 'E107.3', label: '' },
  { addr: 'E107.4', label: '' },
  { addr: 'E107.5', label: 'FRE' },
  { addr: 'E107.6', label: 'RX1' },
  { addr: 'E107.7', label: 'RX2' },
  { addr: 'E108.0', label: 'EOMD' },
  { addr: 'E108.1', label: 'EZMD' },
  { addr: 'E108.2', label: 'AMD' },
  { addr: 'E108.3', label: 'SPR' },
  { addr: 'E108.4', label: '' },
  { addr: 'E108.5', label: '' },
  { addr: 'E108.6', label: '' },
  { addr: 'E108.7', label: '' },
  { addr: 'E109.0', label: '' },
  { addr: 'E109.1', label: '' },
  { addr: 'E109.2', label: '' },
  { addr: 'E109.3', label: '' },
  { addr: 'E109.4', label: '' },
  { addr: 'E109.5', label: '' },
  { addr: 'E109.6', label: '' },
  { addr: 'E109.7', label: '' }
]
exports.inputs5 = [
  { addr: 'E400.0', label: 'FTACR' },
  { addr: 'E400.1', label: '' },
  { addr: 'E400.2', label: 'FTACL' },
  { addr: 'E400.3', label: '' },
  { addr: 'E400.4', label: '' },
  { addr: 'E400.5', label: '' },
  { addr: 'E400.6', label: 'FE1' },
  { addr: 'E400.7', label: 'AF7' },
  { addr: 'E401.0', label: 'IV1' },
  { addr: 'E401.1', label: 'IV2' },
  { addr: 'E401.2', label: '' },
  { addr: 'E401.3', label: 'RS12' },
  { addr: 'E401.4', label: 'RS3' },
  { addr: 'E401.5', label: 'AH' },
  { addr: 'E401.6', label: 'AGF' },
  { addr: 'E401.7', label: 'AKKP' }
]
exports.inputs6 = [
  { addr: 'E410.0', label: 'A' },
  { addr: 'E410.1', label: 'B' },
  { addr: 'E410.2', label: 'C' },
  { addr: 'E410.3', label: 'D' },
  { addr: 'E410.4', label: 'OK' },
  { addr: 'E410.5', label: 'S2' },
  { addr: 'E410.6', label: 'S2' },
  { addr: 'E410.7', label: 'S2' },
  { addr: 'E411.0', label: 'EM' },
  { addr: 'E411.1', label: 'EXPV' },
  { addr: 'E411.2', label: 'FSBK' },
  { addr: 'E411.3', label: 'ASBK1' },
  { addr: 'E411.4', label: 'FTCR' },
  { addr: 'E411.5', label: 'AGH' },
  { addr: 'E411.6', label: 'FTXV' },
  { addr: 'E411.7', label: 'FTXH' },
  { addr: 'E412.0', label: 'RMV' },
  { addr: 'E412.1', label: 'RMH' },
  { addr: 'E412.2', label: 'RES' },
  { addr: 'E412.3', label: 'REH' },
  { addr: 'E412.4', label: 'RCV' },
  { addr: 'E412.5', label: 'REAV' },
  { addr: 'E412.6', label: 'REAH' },
  { addr: 'E412.7', label: 'RCH' },
  { addr: 'E413.0', label: '' },
  { addr: 'E413.1', label: '' },
  { addr: 'E413.2', label: 'SRL' },
  { addr: 'E413.3', label: '' },
  { addr: 'E413.4', label: 'DB32' },
  { addr: 'E413.5', label: 'DBHZ' },
  { addr: 'E413.6', label: 'FTM' },
  { addr: 'E413.7', label: 'UC' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'LK' },
  { addr: 'A0.1', label: 'LE' },
  { addr: 'A0.2', label: 'LB' },
  { addr: 'A0.3', label: 'RDY' },
  { addr: 'A0.4', label: 'RST' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: 'LA' },
  { addr: 'A0.7', label: 'RBU' },
  { addr: 'A1.0', label: 'LK' },
  { addr: 'A1.1', label: 'LE' },
  { addr: 'A1.2', label: 'LB' },
  { addr: 'A1.3', label: 'RDY' },
  { addr: 'A1.4', label: 'RST' },
  { addr: 'A1.5', label: 'LSA' },
  { addr: 'A1.6', label: 'LSB' },
  { addr: 'A1.7', label: 'LSC' },
  { addr: 'A2.0', label: '' },
  { addr: 'A2.1', label: '' },
  { addr: 'A2.2', label: '' },
  { addr: 'A2.3', label: '' },
  { addr: 'A2.4', label: '' },
  { addr: 'A2.5', label: 'LST1' },
  { addr: 'A2.6', label: 'LST2' },
  { addr: 'A2.7', label: 'LST3' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A100.0', label: '' },
  { addr: 'A100.1', label: 'KBA' },
  { addr: 'A100.2', label: 'SBK1' },
  { addr: 'A100.3', label: 'KXPE' },
  { addr: 'A100.4', label: 'SZE' },
  { addr: 'A100.5', label: 'SOE' },
  { addr: 'A100.6', label: 'LA' },
  { addr: 'A100.7', label: 'LC' },
  { addr: 'A101.0', label: 'L1' },
  { addr: 'A101.1', label: 'L2' },
  { addr: 'A101.2', label: 'L3' },
  { addr: 'A101.3', label: 'L4' },
  { addr: 'A101.4', label: 'L5' },
  { addr: 'A101.5', label: 'RFE' },
  { addr: 'A101.6', label: 'RLN' },
  { addr: 'A101.7', label: 'RBE' },
  { addr: 'A102.0', label: 'SMA' },
  { addr: 'A102.1', label: 'SMB' },
  { addr: 'A102.2', label: 'KQA' },
  { addr: 'A102.3', label: '' },
  { addr: 'A102.4', label: 'SCA' },
  { addr: 'A102.5', label: 'SCB' },
  { addr: 'A102.6', label: 'TD' },
  { addr: 'A102.7', label: 'SPE' },
  { addr: 'A103.0', label: 'LK' },
  { addr: 'A103.1', label: 'LE' },
  { addr: 'A103.2', label: 'LB' },
  { addr: 'A103.3', label: 'RDY' },
  { addr: 'A103.4', label: 'RST' },
  { addr: 'A103.5', label: 'SBK2' },
  { addr: 'A103.6', label: '' },
  { addr: 'A103.7', label: 'KEM' },
  { addr: 'A104.0', label: 'DYA' },
  { addr: 'A104.1', label: 'DYB' },
  { addr: 'A104.2', label: 'DYC' },
  { addr: 'A104.3', label: 'DYD' },
  { addr: 'A104.4', label: 'AD1' },
  { addr: 'A104.5', label: 'AD2' },
  { addr: 'A104.6', label: 'AD3' },
  { addr: 'A104.7', label: 'STR' },
  { addr: 'A105.0', label: 'SMAD' },
  { addr: 'A105.1', label: 'SMBD' },
  { addr: 'A105.2', label: '' },
  { addr: 'A105.3', label: '' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: '' },
  { addr: 'A106.0', label: '' },
  { addr: 'A106.1', label: '' },
  { addr: 'A106.2', label: '' },
  { addr: 'A106.3', label: '' },
  { addr: 'A106.4', label: '' },
  { addr: 'A106.5', label: '' },
  { addr: 'A106.6', label: '' },
  { addr: 'A106.7', label: '' },
  { addr: 'A107.0', label: '' },
  { addr: 'A107.1', label: '' },
  { addr: 'A107.2', label: '' },
  { addr: 'A107.3', label: '' },
  { addr: 'A107.4', label: '' },
  { addr: 'A107.5', label: '' },
  { addr: 'A107.6', label: '' },
  { addr: 'A107.7', label: '' },
  { addr: 'A108.0', label: '' },
  { addr: 'A108.1', label: '' },
  { addr: 'A108.2', label: '' },
  { addr: 'A108.3', label: '' },
  { addr: 'A108.4', label: '' },
  { addr: 'A108.5', label: '' },
  { addr: 'A108.6', label: '' },
  { addr: 'A108.7', label: '' },
  { addr: 'A109.0', label: '' },
  { addr: 'A109.1', label: '' },
  { addr: 'A109.2', label: '' },
  { addr: 'A109.3', label: '' },
  { addr: 'A109.4', label: '' },
  { addr: 'A109.5', label: '' },
  { addr: 'A109.6', label: '' },
  { addr: 'A109.7', label: '' }
]
exports.outputs5 = [
  { addr: 'A400.0', label: '' },
  { addr: 'A400.1', label: '' },
  { addr: 'A400.2', label: '' },
  { addr: 'A400.3', label: '' },
  { addr: 'A400.4', label: '' },
  { addr: 'A400.5', label: '' },
  { addr: 'A400.6', label: '' },
  { addr: 'A400.7', label: '' },
  { addr: 'A401.0', label: 'T101' },
  { addr: 'A401.1', label: 'T2' },
  { addr: 'A401.2', label: 'T10F' },
  { addr: 'A401.3', label: 'T102' },
  { addr: 'A401.4', label: 'KBA1' },
  { addr: 'A401.5', label: 'KBA2' },
  { addr: 'A401.6', label: '' },
  { addr: 'A401.7', label: '' }
]
exports.outputs6 = [
  { addr: 'A410.0', label: 'DYA' },
  { addr: 'A410.1', label: 'DYB' },
  { addr: 'A410.2', label: 'DYC' },
  { addr: 'A410.3', label: 'DYD' },
  { addr: 'A410.4', label: 'AD1' },
  { addr: 'A410.5', label: 'AD2' },
  { addr: 'A410.6', label: 'AD3' },
  { addr: 'A410.7', label: 'STR' },
  { addr: 'A411.0', label: 'SBK1' },
  { addr: 'A411.1', label: '' },
  { addr: 'A411.2', label: 'TRA' },
  { addr: 'A411.3', label: 'TRB' },
  { addr: 'A411.4', label: 'TCS' },
  { addr: 'A411.5', label: 'TCV' },
  { addr: 'A411.6', label: 'TCH' },
  { addr: 'A411.7', label: 'TCR' },
  { addr: 'A412.0', label: 'SBK2' },
  { addr: 'A412.1', label: '' },
  { addr: 'A412.2', label: '' },
  { addr: 'A412.3', label: '' },
  { addr: 'A412.4', label: '' },
  { addr: 'A412.5', label: '' },
  { addr: 'A412.6', label: 'LA' },
  { addr: 'A412.7', label: 'LC' },
  { addr: 'A413.0', label: '' },
  { addr: 'A413.1', label: '' },
  { addr: 'A413.2', label: '' },
  { addr: 'A413.3', label: '' },
  { addr: 'A413.4', label: '' },
  { addr: 'A413.5', label: '' },
  { addr: 'A413.6', label: '' },
  { addr: 'A413.7', label: '' }
]
exports.EL = [
  { class: 'EL1', label: 'AL1', i18n: { key: 'al-sil-01', query: {} } },
  { class: 'EL1', label: 'AL2', i18n: { key: 'al-sil-02', query: {} } },
  { class: 'EL1', label: 'AL3', i18n: { key: 'al-sil-03', query: {} } },
  { class: 'EL1', label: 'AL4', i18n: { key: 'al-sil-04', query: {} } },
  { class: 'EL1', label: 'AL5', i18n: { key: 'al-sil-05', query: {} } },
  { class: 'EL1', label: 'AL6', i18n: { key: 'al-sil-06', query: {} } },
  { class: 'EL1', label: 'AL7', i18n: { key: 'al-sil-07', query: {} } },
  { class: 'EL1', label: 'AL8', i18n: { key: 'al-sil-08', query: {} } },
  { class: 'EL1', label: 'AL9', i18n: { key: 'al-sil-09', query: {} } },
  { class: 'EL1', label: 'AL10', i18n: { key: 'al-sil-10', query: {} } },
  { class: 'EL1', label: 'AL11', i18n: { key: 'al-sil-11', query: {} } },
  { class: 'EL1', label: 'AL12', i18n: { key: 'al-sil-12', query: {} } },
  { class: 'EL1', label: 'AL13', i18n: { key: 'al-sil-13', query: {} } },
  { class: 'EL1', label: 'AL14', i18n: { key: 'al-sil-14', query: {} } },
  { class: 'EL1', label: 'AL15', i18n: { key: 'al-sil-15', query: {} } },
  { class: 'EL1', label: 'AL16', i18n: { key: 'al-sil-16', query: {} } },
  { class: 'EL1', label: 'AL17', i18n: { key: 'al-v-to', query: {} } },
  { class: 'EL1', label: 'AL18', i18n: { key: 'al-v-fdbk', query: {} } },
  { class: 'EL1', label: 'AL19', i18n: { key: 'al-lv', query: {} } },
  { class: 'EL1', label: 'AL20', i18n: { key: 'al-v-lck-to', query: {} } },
  { class: 'EL1', label: 'AL21', i18n: { key: 'al-v-lck-fc', query: {} } },
  { class: 'EL1', label: 'AL22', i18n: { key: 'al-r-to', query: {} } },
  { class: 'EL1', label: 'AL23', i18n: { key: 'al-enr', query: {} } },
  { class: 'EL1', label: 'AL24', i18n: { key: 'al-r-lck-to', query: {} } },
  { class: 'EL1', label: 'AL25', i18n: { key: 'al-r-lck-fc', query: {} } },
  { class: 'EL1', label: 'AL26', i18n: { key: 'al-flap-to', query: {} } },
  { class: 'EL1', label: 'AL27', i18n: { key: 'al-flap-fc', query: {} } },
  { class: 'EL1', label: 'AL28', i18n: { key: 'al-sp-to', query: {} } },
  { class: 'EL1', label: 'AL29', i18n: { key: 'al-sp-fc', query: {} } },
  { class: 'EL1', label: 'AL30', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL31', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL32', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL33', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL34', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL35', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL36', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL37', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL38', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL39', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL40', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL41', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL42', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL43', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL44', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL45', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL46', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL47', i18n: { key: '', query: {} } },
  {
    class: 'EL1',
    label: 'AL48',
    i18n: { key: '', query: {} }
  },
  {
    class: 'EL1',
    label: 'AL49',
    i18n: { key: 'al-th', query: { name: 'AMC' } }
  },
  {
    class: 'EL1',
    label: 'AL50',
    i18n: { key: 'al-th', query: { name: 'APE' } }
  },
  {
    class: 'EL1',
    label: 'AL51',
    i18n: { key: 'al-th', query: { name: 'AF7' } }
  },
  {
    class: 'EL1',
    label: 'AL52',
    i18n: { key: 'al-th', query: { name: 'ASBK2' } }
  },
  {
    class: 'EL1',
    label: 'AL53',
    i18n: { key: 'al-th', query: { name: 'ASBK' } }
  },
  {
    class: 'EL1',
    label: 'AL54',
    i18n: { key: 'al-th', query: { name: 'RT' } }
  },
  {
    class: 'EL1',
    label: 'AL55',
    i18n: { key: 'al-th', query: { name: 'FE1' } }
  },
  {
    class: 'EL1',
    label: 'AL56',
    i18n: { key: 'al-th', query: { name: 'AD' } }
  },
  {
    class: 'EL1',
    label: 'AL57',
    i18n: { key: 'al-th', query: { name: 'AMM' } }
  },
  {
    class: 'EL1',
    label: 'AL58',
    i18n: { key: 'al-th', query: { name: 'AMD' } }
  },
  { class: 'EL1', label: 'AL59', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL60', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL61', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL62', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL63', i18n: { key: '', query: {} } },
  { class: 'EL1', label: 'AL64', i18n: { key: '', query: {} } }
]
exports.T = [
  { class: 'T1', label: 'AL1', i18n: { key: 'al-sil-01', query: {} } },
  { class: 'T1', label: 'AL2', i18n: { key: 'al-sil-02', query: {} } },
  { class: 'T1', label: 'AL3', i18n: { key: 'al-sil-03', query: {} } },
  { class: 'T1', label: 'AL4', i18n: { key: 'al-sil-04', query: {} } },
  { class: 'T1', label: 'AL5', i18n: { key: 'al-sil-05', query: {} } },
  { class: 'T1', label: 'AL6', i18n: { key: 'al-sil-06', query: {} } },
  { class: 'T1', label: 'AL7', i18n: { key: 'al-sil-07', query: {} } },
  { class: 'T1', label: 'AL8', i18n: { key: 'al-sil-08', query: {} } },
  { class: 'T1', label: 'AL9', i18n: { key: 'al-sil-09', query: {} } },
  { class: 'T1', label: 'AL10', i18n: { key: 'al-sil-10', query: {} } },
  { class: 'T1', label: 'AL11', i18n: { key: 'al-sil-11', query: {} } },
  { class: 'T1', label: 'AL12', i18n: { key: 'al-sil-12', query: {} } },
  { class: 'T1', label: 'AL13', i18n: { key: 'al-sil-13', query: {} } },
  { class: 'T1', label: 'AL14', i18n: { key: 'al-sil-14', query: {} } },
  { class: 'T1', label: 'AL15', i18n: { key: 'al-sil-15', query: {} } },
  { class: 'T1', label: 'AL16', i18n: { key: 'al-sil-16', query: {} } },
  { class: 'T1', label: 'AL17', i18n: { key: 'al-v-to', query: {} } },
  { class: 'T1', label: 'AL18', i18n: { key: 'al-v-fdbk', query: {} } },
  { class: 'T1', label: 'AL19', i18n: { key: 'al-lv', query: {} } },
  { class: 'T1', label: 'AL20', i18n: { key: 'al-lv-diff', query: {} } },
  { class: 'T1', label: 'AL21', i18n: { key: 'al-h-to', query: {} } },
  { class: 'T1', label: 'AL22', i18n: { key: 'al-lh', query: {} } },
  { class: 'T1', label: 'AL23', i18n: { key: 'al-lh-diff', query: {} } },
  { class: 'T1', label: 'AL24', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL25', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL26', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL27', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL28', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL29', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL30', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL31', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL32', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL33', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL34', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL35', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL36', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL37', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL38', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL39', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL40', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL41', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL42', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL43', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL44', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL45', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL46', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL47', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL48', i18n: { key: '', query: {} } },
  {
    class: 'T1',
    label: 'AL49',
    i18n: { key: 'al-th', query: { name: 'FE1' } }
  },
  {
    class: 'T1',
    label: 'AL50',
    i18n: { key: 'al-th', query: { name: 'AF7' } }
  },
  {
    class: 'T1',
    label: 'AL51',
    i18n: { key: 'al-th', query: { name: 'AH' } }
  },
  {
    class: 'T1',
    label: 'AL52',
    i18n: { key: 'al-th', query: { name: 'AGF' } }
  },
  {
    class: 'T1',
    label: 'AL53',
    i18n: { key: 'al-th', query: { name: 'AKKP' } }
  },
  {
    class: 'T1',
    label: 'AL54',
    i18n: { key: 'al-th', query: { name: 'ASBK' } }
  },
  {
    class: 'T1',
    label: 'AL55',
    i18n: { key: 'al-th', query: { name: 'MTC' } }
  },
  { class: 'T1', label: 'AL56', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL57', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL58', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL59', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL60', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL61', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL62', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL63', i18n: { key: '', query: {} } },
  { class: 'T1', label: 'AL64', i18n: { key: '', query: {} } }
]
