exports.inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'STR' },
  { addr: 'E0.5', label: 'OK' },
  { addr: 'E0.6', label: 'DAT' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: 'A' },
  { addr: 'E1.1', label: 'B' },
  { addr: 'E1.2', label: 'C' },
  { addr: 'E1.3', label: 'D' },
  { addr: 'E1.4', label: 'STR' },
  { addr: 'E1.5', label: 'OK' },
  { addr: 'E1.6', label: 'DAT' },
  { addr: 'E1.7', label: '' },
  { addr: 'E2.0', label: 'A' },
  { addr: 'E2.1', label: 'B' },
  { addr: 'E2.2', label: 'C' },
  { addr: 'E2.3', label: 'D' },
  { addr: 'E2.4', label: 'STR' },
  { addr: 'E2.5', label: 'OK' },
  { addr: 'E2.6', label: 'DAT' },
  { addr: 'E2.7', label: '' },
  { addr: 'E3.0', label: 'A' },
  { addr: 'E3.1', label: 'B' },
  { addr: 'E3.2', label: 'C' },
  { addr: 'E3.3', label: 'D' },
  { addr: 'E3.4', label: 'STR' },
  { addr: 'E3.5', label: 'OK' },
  { addr: 'E3.6', label: 'DAT' },
  { addr: 'E3.7', label: '' },
  { addr: 'E4.0', label: 'A' },
  { addr: 'E4.1', label: 'B' },
  { addr: 'E4.2', label: 'C' },
  { addr: 'E4.3', label: 'D' },
  { addr: 'E4.4', label: 'STR' },
  { addr: 'E4.5', label: 'OK' },
  { addr: 'E4.6', label: 'DAT' },
  { addr: 'E4.7', label: '' },
  { addr: 'E5.0', label: 'PS1' },
  { addr: 'E5.1', label: 'PS2' },
  { addr: 'E5.2', label: 'PS3' },
  { addr: 'E5.3', label: 'PS4' },
  { addr: 'E5.4', label: 'PS5' },
  { addr: 'E5.5', label: 'PS6' },
  { addr: 'E5.6', label: 'FA1' },
  { addr: 'E5.7', label: 'FE12' }
]
exports.inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: 'EZA' },
  { addr: 'E101.1', label: 'EOA' },
  { addr: 'E101.2', label: 'FBA' },
  { addr: 'E101.3', label: 'APA' },
  { addr: 'E101.4', label: 'AGF' },
  { addr: 'E101.5', label: 'AKKM' },
  { addr: 'E101.6', label: 'APE' },
  { addr: 'E101.7', label: 'UC' },
  { addr: 'E102.0', label: 'IV2' },
  { addr: 'E102.1', label: 'ASBK2' },
  { addr: 'E102.2', label: '' },
  { addr: 'E102.3', label: 'IV1' },
  { addr: 'E102.4', label: 'FDBK' },
  { addr: 'E102.5', label: 'ASBK' },
  { addr: 'E102.6', label: 'RT12' },
  { addr: 'E102.7', label: 'FSQA' },
  { addr: 'E103.0', label: 'FE1' },
  { addr: 'E103.1', label: '' },
  { addr: 'E103.2', label: 'EXD' },
  { addr: 'E103.3', label: 'RS12' },
  { addr: 'E103.4', label: 'DB32' },
  { addr: 'E103.5', label: 'DBHZ' },
  { addr: 'E103.6', label: '' },
  { addr: 'E103.7', label: 'AF7' },
  { addr: 'E104.0', label: 'FTS1' },
  { addr: 'E104.1', label: 'FTS2' },
  { addr: 'E104.2', label: '' },
  { addr: 'E104.3', label: '' },
  { addr: 'E104.4', label: '' },
  { addr: 'E104.5', label: '' },
  { addr: 'E104.6', label: '' },
  { addr: 'E104.7', label: '' },
  { addr: 'E105.0', label: '' },
  { addr: 'E105.1', label: '' },
  { addr: 'E105.2', label: '' },
  { addr: 'E105.3', label: '' },
  { addr: 'E105.4', label: '' },
  { addr: 'E105.5', label: '' },
  { addr: 'E105.6', label: '' },
  { addr: 'E105.7', label: '' },
  { addr: 'E106.0', label: 'EZE' },
  { addr: 'E106.1', label: 'EOE' },
  { addr: 'E106.2', label: 'FBE' },
  { addr: 'E106.3', label: 'FPE' },
  { addr: 'E106.4', label: 'FDR1' },
  { addr: 'E106.5', label: 'FDL1' },
  { addr: 'E106.6', label: 'FTA1' },
  { addr: 'E106.7', label: 'FTA2' },
  { addr: 'E107.0', label: 'FLP1' },
  { addr: 'E107.1', label: 'FLP2' },
  { addr: 'E107.2', label: 'FLA' },
  { addr: 'E107.3', label: 'FTA1-1' },
  { addr: 'E107.4', label: 'FTA2-1' },
  { addr: 'E107.5', label: 'LOOP' },
  { addr: 'E107.6', label: 'RX1' },
  { addr: 'E107.7', label: 'RX2' }
]
exports.inputs3 = [
  { addr: 'E110.0', label: 'ECA' },
  { addr: 'E110.1', label: 'ECB' },
  { addr: 'E110.2', label: 'AMC' },
  { addr: 'E110.3', label: 'EOM' },
  { addr: 'E110.4', label: 'EZM' },
  { addr: 'E110.5', label: 'AMM' },
  { addr: 'E110.6', label: 'FRE' },
  { addr: 'E110.7', label: '' },
  { addr: 'E111.0', label: 'EM' },
  { addr: 'E111.1', label: 'EXPV' },
  { addr: 'E111.2', label: 'EFB' },
  { addr: 'E111.3', label: 'K12' },
  { addr: 'E111.4', label: 'TCR' },
  { addr: 'E111.5', label: 'MTC' },
  { addr: 'E111.6', label: 'FTXV' },
  { addr: 'E111.7', label: 'FTXH' },
  { addr: 'E112.0', label: 'RMV' },
  { addr: 'E112.1', label: 'RMH' },
  { addr: 'E112.2', label: 'RES' },
  { addr: 'E112.3', label: 'REH' },
  { addr: 'E112.4', label: 'RCV' },
  { addr: 'E112.5', label: 'REAV' },
  { addr: 'E112.6', label: 'REAH' },
  { addr: 'E112.7', label: 'RCH' }
]
// ...
exports.inputs8 = [
  { addr: 'E400.0', label: 'A' },
  { addr: 'E400.1', label: 'B' },
  { addr: 'E400.2', label: 'C' },
  { addr: 'E400.3', label: 'D' },
  { addr: 'E400.4', label: 'OK' },
  { addr: 'E400.5', label: 'S2' },
  { addr: 'E400.6', label: 'S2' },
  { addr: 'E400.7', label: 'S2' },
  { addr: 'E401.0', label: 'FE1' },
  { addr: 'E401.1', label: 'IV1' },
  { addr: 'E401.2', label: '' },
  { addr: 'E401.3', label: 'K12' },
  { addr: 'E401.4', label: 'FDBK' },
  { addr: 'E401.5', label: 'ASBK' },
  { addr: 'E401.6', label: 'RT12' },
  { addr: 'E401.7', label: 'UC' },
  { addr: 'E402.0', label: '' },
  { addr: 'E402.1', label: '' },
  { addr: 'E402.2', label: '' },
  { addr: 'E402.3', label: '' },
  { addr: 'E402.4', label: '' },
  { addr: 'E402.5', label: '' },
  { addr: 'E402.6', label: '' },
  { addr: 'E402.7', label: '' },
  { addr: 'E403.0', label: '' },
  { addr: 'E403.1', label: '' },
  { addr: 'E403.2', label: '' },
  { addr: 'E403.3', label: '' },
  { addr: 'E403.4', label: '' },
  { addr: 'E403.5', label: '' },
  { addr: 'E403.6', label: '' },
  { addr: 'E403.7', label: '' }
]
exports.inputs9 = [
  { addr: 'E404.0', label: '' },
  { addr: 'E404.1', label: 'ACR' },
  { addr: 'E404.2', label: 'FTCR' },
  { addr: 'E404.3', label: 'FE3' },
  { addr: 'E404.4', label: '' },
  { addr: 'E404.5', label: '' },
  { addr: 'E404.6', label: 'K12' },
  { addr: 'E404.7', label: '' },
  { addr: 'E405.0', label: '' },
  { addr: 'E405.1', label: '' },
  { addr: 'E405.2', label: 'AMM' },
  { addr: 'E405.3', label: 'EOM' },
  { addr: 'E405.4', label: 'EZM' },
  { addr: 'E405.5', label: 'EMC' },
  { addr: 'E405.6', label: '' },
  { addr: 'E405.7', label: '' }
]
exports.inputs10 = [
  { addr: 'E410.0', label: 'A' },
  { addr: 'E410.1', label: 'B' },
  { addr: 'E410.2', label: 'C' },
  { addr: 'E410.3', label: 'D' },
  { addr: 'E410.4', label: 'OK' },
  { addr: 'E410.5', label: 'S2' },
  { addr: 'E410.6', label: 'S2' },
  { addr: 'E410.7', label: 'S2' },
  { addr: 'E411.0', label: 'FE4' },
  { addr: 'E411.1', label: '' },
  { addr: 'E411.2', label: '' },
  { addr: 'E411.3', label: 'EM' },
  { addr: 'E411.4', label: '' },
  { addr: 'E411.5', label: '' },
  { addr: 'E411.6', label: 'FTXV' },
  { addr: 'E411.7', label: 'FTXH' },
  { addr: 'E412.0', label: 'RMV' },
  { addr: 'E412.1', label: 'RMH' },
  { addr: 'E412.2', label: 'RES' },
  { addr: 'E412.3', label: 'REH' },
  { addr: 'E412.4', label: 'RCV' },
  { addr: 'E412.5', label: 'REAV' },
  { addr: 'E412.6', label: 'REAH' },
  { addr: 'E412.7', label: 'RCH' },
  { addr: 'E413.0', label: 'IV2' },
  { addr: 'E413.1', label: '' },
  { addr: 'E413.2', label: '' },
  { addr: 'E413.3', label: 'RS12' },
  { addr: 'E413.4', label: 'DB32' },
  { addr: 'E413.5', label: 'DBHZ' },
  { addr: 'E413.6', label: 'FTAC' },
  { addr: 'E413.7', label: 'UC' },
  { addr: 'E414.0', label: 'AF7' },
  { addr: 'E414.1', label: '' },
  { addr: 'E414.2', label: 'FTM1' },
  { addr: 'E414.3', label: 'FTM2' },
  { addr: 'E414.4', label: 'FTM3' },
  { addr: 'E414.5', label: 'FTCR' },
  { addr: 'E414.6', label: 'AH' },
  { addr: 'E414.7', label: 'MTC' }
]
// ...
exports.outputs1 = [
  { addr: 'A0.0', label: 'LK' },
  { addr: 'A0.1', label: 'LE' },
  { addr: 'A0.2', label: 'LB' },
  { addr: 'A0.3', label: 'RDY' },
  { addr: 'A0.4', label: 'RST' },
  { addr: 'A0.5', label: 'LSK' },
  { addr: 'A0.6', label: 'LA' },
  { addr: 'A0.7', label: 'RBU' },
  { addr: 'A1.0', label: 'LK' },
  { addr: 'A1.1', label: 'LE' },
  { addr: 'A1.2', label: 'LB' },
  { addr: 'A1.3', label: 'RDY' },
  { addr: 'A1.4', label: 'RST' },
  { addr: 'A1.5', label: 'LS1' },
  { addr: 'A1.6', label: 'LS2' },
  { addr: 'A1.7', label: 'LS3' },
  { addr: 'A2.0', label: 'LK' },
  { addr: 'A2.1', label: 'LE' },
  { addr: 'A2.2', label: 'LB' },
  { addr: 'A2.3', label: 'RDY' },
  { addr: 'A2.4', label: 'RST' },
  { addr: 'A2.5', label: '' },
  { addr: 'A2.6', label: '' },
  { addr: 'A2.7', label: 'RBE1' },
  { addr: 'A3.0', label: 'LK' },
  { addr: 'A3.1', label: 'LE' },
  { addr: 'A3.2', label: 'LB' },
  { addr: 'A3.3', label: 'RDY' },
  { addr: 'A3.4', label: 'RST' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: 'RBE2' },
  { addr: 'A4.0', label: 'LK' },
  { addr: 'A4.1', label: 'LE' },
  { addr: 'A4.2', label: 'LB' },
  { addr: 'A4.3', label: 'RDY' },
  { addr: 'A4.4', label: 'RST' },
  { addr: 'A4.5', label: '' },
  { addr: 'A4.6', label: '' },
  { addr: 'A4.7', label: 'RBE3' },
  { addr: 'A5.0', label: 'LS4' },
  { addr: 'A5.1', label: 'LS5' },
  { addr: 'A5.2', label: 'LS6' },
  { addr: 'A5.3', label: '' },
  { addr: 'A5.4', label: '' },
  { addr: 'A5.5', label: '' },
  { addr: 'A5.6', label: '' },
  { addr: 'A5.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A100.0', label: 'T2' },
  { addr: 'A100.1', label: 'KBA1' },
  { addr: 'A100.2', label: 'SBK1' },
  { addr: 'A100.3', label: 'KBA2' },
  { addr: 'A100.4', label: 'SZE' },
  { addr: 'A100.5', label: 'SOE' },
  { addr: 'A100.6', label: 'LA' },
  { addr: 'A100.7', label: 'LC' },
  { addr: 'A101.0', label: 'L1' },
  { addr: 'A101.1', label: 'L2' },
  { addr: 'A101.2', label: 'L3' },
  { addr: 'A101.3', label: 'L4' },
  { addr: 'A101.4', label: 'L5' },
  { addr: 'A101.5', label: 'RFE' },
  { addr: 'A101.6', label: 'RLN' },
  { addr: 'A101.7', label: 'RFA' },
  { addr: 'A102.0', label: 'SZA' },
  { addr: 'A102.1', label: 'SOA' },
  { addr: 'A102.2', label: 'KQA' },
  { addr: 'A102.3', label: 'SPA' },
  { addr: 'A102.4', label: 'SBK2' },
  { addr: 'A102.5', label: '' },
  { addr: 'A102.6', label: 'TD' },
  { addr: 'A102.7', label: 'SPE' },
  { addr: 'A103.0', label: 'A' },
  { addr: 'A103.1', label: 'B' },
  { addr: 'A103.2', label: 'C' },
  { addr: 'A103.3', label: 'D' },
  { addr: 'A103.4', label: 'AD1' },
  { addr: 'A103.5', label: 'AD2' },
  { addr: 'A103.6', label: 'AD3' },
  { addr: 'A103.7', label: 'STR' }
]
exports.outputs3 = [
  { addr: 'A110.0', label: '' },
  { addr: 'A110.1', label: '' },
  { addr: 'A110.2', label: 'TRA' },
  { addr: 'A110.3', label: 'TRB' },
  { addr: 'A110.4', label: 'KCS' },
  { addr: 'A110.5', label: 'KCV' },
  { addr: 'A110.6', label: 'KCH' },
  { addr: 'A110.7', label: 'TCR' },
  { addr: 'A111.0', label: 'SMA' },
  { addr: 'A111.1', label: 'SMB' },
  { addr: 'A111.2', label: 'SCA' },
  { addr: 'A111.3', label: 'SCB' },
  { addr: 'A111.4', label: '' },
  { addr: 'A111.5', label: '' },
  { addr: 'A111.6', label: '' },
  { addr: 'A111.7', label: '' }
]
// ...
exports.outputs8 = [
  { addr: 'A400.0', label: 'SBK2' },
  { addr: 'A400.1', label: 'KBA' },
  { addr: 'A400.2', label: '' },
  { addr: 'A400.3', label: '' },
  { addr: 'A400.4', label: '' },
  { addr: 'A400.5', label: 'RFE1' },
  { addr: 'A400.6', label: 'LA' },
  { addr: 'A400.7', label: 'LC' },
  { addr: 'A401.0', label: 'A' },
  { addr: 'A401.1', label: 'B' },
  { addr: 'A401.2', label: 'C' },
  { addr: 'A401.3', label: 'D' },
  { addr: 'A401.4', label: 'AD1' },
  { addr: 'A401.5', label: 'AD2' },
  { addr: 'A401.6', label: 'AD3' },
  { addr: 'A401.7', label: 'STR' }
]
exports.outputs9 = [
  { addr: 'A404.0', label: 'SMA' },
  { addr: 'A404.1', label: 'SMB' },
  { addr: 'A404.2', label: 'FTCR' },
  { addr: 'A404.3', label: 'KSH' },
  { addr: 'A404.4', label: '' },
  { addr: 'A404.5', label: '' },
  { addr: 'A404.6', label: 'LA' },
  { addr: 'A404.7', label: '' }
]
exports.outputs10 = [
  { addr: 'A410.0', label: 'A' },
  { addr: 'A410.1', label: 'B' },
  { addr: 'A410.2', label: 'C' },
  { addr: 'A410.3', label: 'D' },
  { addr: 'A410.4', label: 'AD1' },
  { addr: 'A410.5', label: 'AD2' },
  { addr: 'A410.6', label: 'ADR' },
  { addr: 'A410.7', label: 'STR' },
  { addr: 'A411.0', label: 'T101' },
  { addr: 'A411.1', label: 'T2' },
  { addr: 'A411.2', label: 'TRA' },
  { addr: 'A411.3', label: 'TRB' },
  { addr: 'A411.4', label: 'KCS' },
  { addr: 'A411.5', label: 'KCV' },
  { addr: 'A411.6', label: 'KCH' },
  { addr: 'A411.7', label: 'TCR' },
  { addr: 'A412.0', label: 'KBA2' },
  { addr: 'A412.1', label: '' },
  { addr: 'A412.2', label: '' },
  { addr: 'A412.3', label: '' },
  { addr: 'A412.4', label: 'T102' },
  { addr: 'A412.5', label: 'T10F' },
  { addr: 'A412.6', label: 'LA' },
  { addr: 'A412.7', label: 'LC' }
]
// ...
exports.alarms1 = [
  { class: 'EVT1', label: 'AL1', i18n: { key: 'al-sil-01', query: {} } },
  { class: 'EVT1', label: 'AL2', i18n: { key: 'al-sil-02', query: {} } },
  { class: 'EVT1', label: 'AL3', i18n: { key: 'al-sil-03', query: {} } },
  { class: 'EVT1', label: 'AL4', i18n: { key: 'al-sil-04', query: {} } },
  { class: 'EVT1', label: 'AL5', i18n: { key: 'al-sil-05', query: {} } },
  { class: 'EVT1', label: 'AL6', i18n: { key: 'al-sil-06', query: {} } },
  { class: 'EVT1', label: 'AL7', i18n: { key: 'al-sil-07', query: {} } },
  { class: 'EVT1', label: 'AL8', i18n: { key: 'al-sil-08', query: {} } },
  { class: 'EVT1', label: 'AL9', i18n: { key: 'al-sil-09', query: {} } },
  { class: 'EVT1', label: 'AL10', i18n: { key: 'al-sil-10', query: {} } },
  { class: 'EVT1', label: 'AL11', i18n: { key: 'al-sil-11', query: {} } },
  { class: 'EVT1', label: 'AL12', i18n: { key: 'al-sil-12', query: {} } },
  { class: 'EVT1', label: 'AL13', i18n: { key: 'al-sil-13', query: {} } },
  { class: 'EVT1', label: 'AL14', i18n: { key: 'al-sil-14', query: {} } },
  { class: 'EVT1', label: 'AL15', i18n: { key: 'al-sil-15', query: {} } },
  { class: 'EVT1', label: 'AL16', i18n: { key: 'al-sil-16', query: {} } },
  { class: 'EVT1', label: 'AL17', i18n: { key: 'al-v-to', query: {} } },
  { class: 'EVT1', label: 'AL18', i18n: { key: 'al-v-fdbk', query: {} } },
  { class: 'EVT1', label: 'AL19', i18n: { key: 'al-lv', query: {} } },
  { class: 'EVT1', label: 'AL20', i18n: { key: 'al-v-lck-to', query: {} } },
  { class: 'EVT1', label: 'AL21', i18n: { key: 'al-v-lck-fc', query: {} } },
  { class: 'EVT1', label: 'AL22', i18n: { key: 'al-r-to', query: {} } },
  { class: 'EVT1', label: 'AL23', i18n: { key: 'al-enr', query: {} } },
  { class: 'EVT1', label: 'AL24', i18n: { key: 'al-flap-to', query: {} } },
  { class: 'EVT1', label: 'AL25', i18n: { key: 'al-flap-fc', query: {} } },
  { class: 'EVT1', label: 'AL26', i18n: { key: 'al-spe-to', query: {} } },
  { class: 'EVT1', label: 'AL27', i18n: { key: 'al-spe-fc', query: {} } },
  { class: 'EVT1', label: 'AL28', i18n: { key: 'al-spa-to', query: {} } },
  { class: 'EVT1', label: 'AL29', i18n: { key: 'al-spa-fc', query: {} } },
  { class: 'EVT1', label: 'AL30', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL31', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL32', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL33', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL34', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL35', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL36', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL37', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL38', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL39', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL40', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL41', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL42', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL43', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL44', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL45', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL46', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL47', i18n: { key: '', query: {} } },
  {
    class: 'EVT1',
    label: 'AL48',
    i18n: { key: 'al-th', query: { thermic: 'AMC' } }
  },
  { class: 'EVT1', label: 'AL49', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL50', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL51', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL52', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL53', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL54', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL55', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL56', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL57', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL58', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL59', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL60', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL61', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL62', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL63', i18n: { key: '', query: {} } },
  { class: 'EVT1', label: 'AL64', i18n: { key: '', query: {} } }
]
exports.alarms4 = [
  { class: 'IVT1', label: 'AL1', i18n: { key: 'al-sil-01', query: {} } },
  { class: 'IVT1', label: 'AL2', i18n: { key: 'al-sil-02', query: {} } },
  { class: 'IVT1', label: 'AL3', i18n: { key: 'al-sil-03', query: {} } },
  { class: 'IVT1', label: 'AL4', i18n: { key: 'al-sil-04', query: {} } },
  { class: 'IVT1', label: 'AL5', i18n: { key: 'al-sil-05', query: {} } },
  { class: 'IVT1', label: 'AL6', i18n: { key: 'al-sil-06', query: {} } },
  { class: 'IVT1', label: 'AL7', i18n: { key: 'al-sil-07', query: {} } },
  { class: 'IVT1', label: 'AL8', i18n: { key: 'al-sil-08', query: {} } },
  { class: 'IVT1', label: 'AL9', i18n: { key: 'al-sil-09', query: {} } },
  { class: 'IVT1', label: 'AL10', i18n: { key: 'al-sil-10', query: {} } },
  { class: 'IVT1', label: 'AL11', i18n: { key: 'al-sil-11', query: {} } },
  { class: 'IVT1', label: 'AL12', i18n: { key: 'al-sil-12', query: {} } },
  { class: 'IVT1', label: 'AL13', i18n: { key: 'al-sil-13', query: {} } },
  { class: 'IVT1', label: 'AL14', i18n: { key: 'al-sil-14', query: {} } },
  { class: 'IVT1', label: 'AL15', i18n: { key: 'al-sil-15', query: {} } },
  { class: 'IVT1', label: 'AL16', i18n: { key: 'al-sil-16', query: {} } },
  { class: 'IVT1', label: 'AL17', i18n: { key: 'al-v-to', query: {} } },
  { class: 'IVT1', label: 'AL18', i18n: { key: 'al-v-fdbk', query: {} } },
  { class: 'IVT1', label: 'AL19', i18n: { key: 'al-lv', query: {} } },
  { class: 'IVT1', label: 'AL20', i18n: { key: 'al-lv-diff', query: {} } },
  { class: 'IVT1', label: 'AL21', i18n: { key: 'al-v-lck-to', query: {} } },
  { class: 'IVT1', label: 'AL22', i18n: { key: 'al-v-lck-fc', query: {} } },
  { class: 'IVT1', label: 'AL23', i18n: { key: 'al-h-to', query: {} } },
  { class: 'IVT1', label: 'AL24', i18n: { key: 'al-lh', query: {} } },
  { class: 'IVT1', label: 'AL25', i18n: { key: 'al-lh-diff', query: {} } },
  { class: 'IVT1', label: 'AL26', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL27', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL28', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL29', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL30', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL31', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL32', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL33', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL34', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL35', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL36', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL37', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL38', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL39', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL40', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL41', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL42', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL43', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL44', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL45', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL46', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL47', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL48', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL49', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL50', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL51', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL52', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL53', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL54', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL55', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL56', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL57', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL58', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL59', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL60', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL61', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL62', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL63', i18n: { key: '', query: {} } },
  { class: 'IVT1', label: 'AL64', i18n: { key: '', query: {} } }
]
